### ISSUE TITLE
some tests failed on arm arch

### ISSUE THREAD

**Issue by changtimwu** [laverdet/node-fibers#108]
NodeJS: v0.10
CPU arch: ARM5TE
build node-fibers with: 
```
node-gyp rebuild --arch arm
```

when running `node test.js`, most tests pass except the following two

* `pool.js` :   _segmentation fault_ !  This can be fixed by reducing the inner loop count from 200 to 120.  
* `stack-overflow2.js` :  _RangeError: Maximum call stack size exceeded_ .  This can be fixed by changing `wasteStack(max - 32);` to `wasteStack(max - 1024);`.   The value of __max__ inspected at runtime is 13852.

**Comment by TomFreudenberg** [comment]
Hi Marcel ( @laverdet )

you closed that issue - Did you got some conclusions on the _segmentation fault_ problem?

Thanks for a short note
Tom

**Comment by laverdet** [comment]
I didn't get any more information on the issue and as I don't have any arm machines it's very difficult for me to test.

**Comment by TomFreudenberg** [comment]
I have an ARM environment on scaleway (https://scaleway.com) where you simple may create your own or I can give you root access to one of my testing servers (just need a ssh public key from you).

There I have a very small source snippet that produces the error in its loop.

I would be happy to assist you if you are interested in.

Tom

**Comment by TomFreudenberg** [comment]
![image](https://cloud.githubusercontent.com/assets/410087/10146866/475097a8-662b-11e5-898f-f83f410a6d0d.png)

this is the small code example I started running with meteor (https://meteor.com)

```
if (Meteor.isServer) {
  for (var i = 0; i<2000; ++i) {console.log(i)}
}
```

Cheers
Tom

**Comment by TomFreudenberg** [comment]
Hi Marcel ( @laverdet )

have you got my previous posts? How may I support you to test this bug?

Thanks for some comment
Tom

**Comment by laverdet** [comment]
I did but it's concert season here in Austin so I've been drunk for the past 10 days. Thank you for the scaleway lead, I'll take a look when I get a chance.

**Comment by TomFreudenberg** [comment]
:-)

**Comment by laverdet** [comment]
If you comment out lines 47 and 48 (comment with #) and run `node build -f` again it should work (tested on a scaleway system). I suspect there is some resource acquisition failing with the default build, but if your application runs with those lines commented out it's much better than default anyway.

**Comment by laverdet** [comment]
In binding.gyp, sorry forgot to mention which file you should touch

**Comment by TomFreudenberg** [comment]
Hi Marcel ( @laverdet )

great to hear that from you. I will check that out within the next days. Is there any option that you provide "a kind of optional" behavior in the fiber package? Otherwise we have to include some patch option to the build process in meteor.

Cheers
Tom

**Comment by TomFreudenberg** [comment]
Hi Marcel, as meteor use currently a fork from node-fibers, I have patched and linked that to my fork for running meteor on arm

https://github.com/4commerce-technologies-AG/node-fibers/commits/master

Q: Will you change the compiler directives for arm in upcoming releases of node-fibers so that I may return to "official" branch once or do I have to maintain that fork in future myself?

Thanks for a short note.
Tom

**Comment by laverdet** [comment]
I need to look into it further because it shouldn't be causing these problems with either compiler flag and I'm concerned there may be a greater underlying issue

**Comment by TomFreudenberg** [comment]
Ok, so it would be nice if you would keep me informed about your finally decisions. For the moment, the fix is doing its job.

Thanks
Tom

**Comment by TomFreudenberg** [comment]
Hi Marcel ( @laverdet )

tonight I finished the for for meteor 1.3.3.1 on ARM. This time the node version v0.10.45 from nodejs.org and node-fibers 1.0.13 is used.

I can confirm that I have not envolved any patch or different compiler directives.

The tests are running without any additional actions from my side.

Do you have any explanation for that behavior ?

Thanks for some feedback
Tom

**Comment by TomFreudenberg** [comment]
Add: the npm release is: 2.15.1

**Comment by TomFreudenberg** [comment]
Hi Marcel,

I am pretty sure that this can be closed and how that conflict in last version occurs.

When previously building the meteor dev-bundle, the attached fibers was the one forked by meteor and had a patch applied from sashko:

https://github.com/meteor/node-fibers/commit/d519f0c5971c33d99c902dad346b817e84bab001

That was the issue raiser on the arm-architecture. So if I drop that commit from Sashko and just use your original release, the segmentation had never happen, even not when I undo my changes at the bindings.gyp.

So resume: All the time your library was working without any changes. Only the applied patches had made it corrupt on the arm architecture.

Sorry and thanks for help
Tom

**Comment by laverdet** [comment]
Oh cool, I'm glad you got it working!
