### ISSUE TITLE
assert(floor_thread_key != 0x7777) fails in coroutine.cc line 49

### ISSUE THREAD

**Issue by jraller** [laverdet/node-fibers#122]
Using syncronize 0.5.2 (https://npmjs.org/package/synchronize) which depends on fibers 1.0.1 I'm able to run just fine on one Windows 7 machine (AMD), but another (Intel) throws a Microsoft Visual C++ Runtime Library error:

```
Assertion failed!
Program:...e_modules\fibers\bin\win32-x64-v8-3.14\fibers.node
File: ..\src\coroutine.cc
Line: 49

Expression: floor_thread_key != 0
```

But line 49 is:

```
assert(floor_thread_key != 0x7777);
```

When installing synchronize the node build.js for fibers reports:

```
`win32-x6-v8-3.14` exists; testing
Binary is fine; exiting
```

I haven't had success yet with using node-gyp to force a build of fibers.node on the machine that fibers isn't working on.

**Comment by dennohdee** [comment]
I had struggled with everything,but installing 'previous version' or node js  I had worked.
