### ISSUE TITLE
How is Future.wrap supposed to be used?

### ISSUE THREAD

**Issue by fresheneesz** [laverdet/node-fibers#127]
It seems like you use Future.wrap like this:

var f = Future.wrap(someAsyncFunction, 2)('a', 'b');

If I don't specify idx, running it always gives the error: "function expects no more than -1 arguments". This seems wrong...

But why require specifying the number of parameters in the first place? Couldn't you rewrite like this without any real downside?:

```
function(fn) {
  return function() {
    var args = Array.prototype.slice.call(arguments);
    var future = new Future;
    args.push(future.resolver());
    fn.apply(this, args);
    return future;
  };
};
```

I wrote a function I like a little better:

```
// either used like futureWrap(function(){ ... })(arg1,arg2,etc) or
//  futureWrap(object, 'methodName')(arg1,arg2,etc)
Future.wrap = function() {
    // function
    if(arguments.length === 1) {
        var fn = arguments[0];
        var object = undefined;

    // object, function
    } else {
        var object = arguments[0];
        var fn = object[arguments[1]];
    }

    return function() {
        var args = Array.prototype.slice.call(arguments);
        var future = new Future;
        args.push(future.resolver());
        var me = this;
        if(object) me = object;
        fn.apply(me, args);
        return future;
    };
};
```

That way you can also call object methods pretty directly:

```
var db = mongo.db('localhost/local', {journal: true});
Future.wrap(db.collection('user').find(), 'toArray')().wait()
```

Thoughts?

**Comment by JThobbyist** [comment]
can somebody please explain how to use future.wrap with a function that takes 'arg1' as an argument and has a callback(error,response,body)?

**Comment by laverdet** [comment]
`multi` is a boolean which when set will cause the future to resolve to an array of non-err arguments. If the callback signatures is `function(err, response, body)` and you wrap the async function with `multi:true`, the future will resolve to `[response, body]`.
