### ISSUE TITLE
"Can't wait without a fiber" - when waiting in asynchronous callback 

### ISSUE THREAD

**Issue by fresheneesz** [laverdet/node-fibers#139]
Maybe I'm misunderstanding how Fibers works, but I would have expected this to be fine:

```
var Fiber = require("fibers")
var Future = require("fibers/future")

Fiber(function() {
    var f = new Future
    setTimeout(function() {
        f.wait()
    },1000)  
}).run()
```

Instead it throw an exception: "Can't wait without a fiber". Do I really need to create another instance of fiber for every asynchronous callback?

Windows 8, node v0.10.18, fibers 1.0.1

**Comment by laverdet** [comment]
You can't invoke `wait` without first being in a fiber. Your example should be written as:

```js
var funcy = function(arg) { return arg + 1; }.future();
Future.task(function() {
  funcy(1).wait();
}).detach();
```

**Comment by jianmin-zhao** [comment]
Thanks laverdet a lot. But the example I listed was cut from the document.

**Comment by laverdet** [comment]
All the documentation in the readme uses `new Fiber(...)` or `Future.task(...)`.
