### ISSUE TITLE
Node executable is `nodejs` not `node` in Debian and Ubuntu

### ISSUE THREAD

**Issue by detro** [laverdet/node-fibers#180]
Please, update the install/build script to handle this.

**Comment by laverdet** [comment]
Yeah on my Ubuntu boxes that's the first thing I do. I could maybe change the install script to do: `$(which nodejs || which node) build`

**Comment by danieleds** [comment]
There is another situation in which the install script can't see node. For example, if I do not install it through the repos but use the precompiled binaries from the website instead.

I can't find a way to make it work with that setup.

**Comment by danieleds** [comment]
Ok, my problem is easily fixed. Assuming node is downloaded to /tmp/node-linux/, run npm like this:

    PATH='/tmp/node-linux/bin':$PATH /tmp/node-linux/bin/npm install fibers

**Comment by detro** [comment]
Nice
