### ISSUE TITLE
How many pthreads per a fiber does it use?

### ISSUE THREAD

**Issue by sergeych** [laverdet/node-fibers#199]
I took a look to the fiber/coroutine sources and it seems to use pthreads intensively, therefore I would love to known, how many posix threads will be created to serve, say 10k active fibers? This is a very important question as performance for 10k threads is quite different from 10k of real thin fibers (working over a single thread).

**Comment by laverdet** [comment]
No threads are used. The pthread code you see there is to trick v8 into doing things it doesn't want to do.

**Comment by sergeych** [comment]
well done! I dug into v8 a little some time ago and it tricked me how anyone could make it run finer (not thread) :) thanks!=
