### ISSUE TITLE
Supports parallel calls?

### ISSUE THREAD

**Issue by totty90** [laverdet/node-fibers#204]
I would like make 2 parallel calls

     var users = Users.get().wait();
     var jobs = Jobs.get().wait();
     // Both of them can be run in parallel how to do it?

**Comment by bjouhier** [comment]
``` javascript
var usersFuture = Users.get();
var jobsFuture = Jobs.get();
var users = usersFuture.wait();
var jobs = jobsFuture.wait();
```

**Comment by totty90** [comment]
Thanks, would be nice to add this to the doc.

Also telling that `Users.get()` will start right away to query. It wasn't obvious at first.

There should be a lib to do something like this:

    var data = someLib({
        users: Users.get(),
        jobs: Jobs.get(),
    })
    and then get data.users and data.jobs

**Comment by laverdet** [comment]
I didn't write `Users.get()`, you did (or some other library your using did). Why would I add it to my documentation??

**Comment by totty90** [comment]
Something general not `Users.get()`. Just to understand how your lib works, not mine. You could say that by doing `Users.get()` after is wrapped it will actually run the `get()` method and the `.wait()` will block from coming.

I know you already somehow write that in the doc, but I couldn't figure out easily. IMO newcomers will find useful such examples.
