### ISSUE TITLE
Option to throw the exact error returned in callback

### ISSUE THREAD

**Issue by totty90** [laverdet/node-fibers#206]
I have errors with more information than just a string and I would like to make it work with fibers. Currently my input can be `{message: 'My Message', code: 'someCode'}` and the fibers just gives me `[object Object]`

**Comment by laverdet** [comment]
Meteor is doing some fancy serialization stuff which causes some lost information. meteor/meteor#2774 is the relevant issue there. @mitar had a solution that could make this work in #144, but I'd have to do some testing and tweaking there.

**Comment by estark37** [comment]
@laverdet https://github.com/meteor/meteor/issues/2774 doesn't have much to do with serialization. (And  doesn't have much to do with Meteor at all, I think.) The user is basically noticing that you can't usefully `console.log` errors that are thrown through futures.
