### ISSUE TITLE
User field in fiber?

### ISSUE THREAD

**Issue by jpaulm** [laverdet/node-fibers#207]
Hi @laverdet,  it would be great to have a user field in fiber that I can access from JavaScript...  Is there one now, or any possibility of getting one?  TIA

**Comment by laverdet** [comment]
I don't know what you are asking for.

**Comment by veselov** [comment]
Fiber.currentFiber.userField? :)

**Comment by jpaulm** [comment]
Actually `fiber.userField` - for any fiber.  That would be great!  Right now I have a class `Process` which has a link to the process's fiber and I have to keep track of that independently of currentFiber (I think) - a userField would let me piggyback on your tracking of currentFiber.  TIA

**Comment by veselov** [comment]
On Wed, Feb 4, 2015 at 7:01 AM, jpaulm <notifications@github.com> wrote:

> Actually fiber.userField - for any fiber. That would be great! Right now
> I have a class Process which has a link to the process's fiber and I have
> to keep track of that independently of currentFiber (I think) - a userField
> would let me piggyback on your tracking of currentFiber. TIA
>

So what's preventing you to do this right now?

var Fiber = require(...);

function callback() {
  var process = Fiber.current.myStuff;
}

Fiber(function(){
  Fiber.current.myStuff = new Process();
  AsyncOperation(things, callback);
}).run();

**Comment by jpaulm** [comment]
Thanks, Pawel, didn't know you could do that!  I don't know much JS!

Are you essentially adding a field to Fiber?  I tend to think of JS classes as Java classes, so this syntax is new to me.  What does Fiber(function(){...}) do?  Seems to return a fiber...

**Comment by veselov** [comment]
On Wed, Feb 4, 2015 at 12:23 PM, jpaulm <notifications@github.com> wrote:

> Thanks, Pawel, didn't know you could do that! I don't know much JS!
>
Sorry if this comes out preachy, but nodejs really does require advanced
j/s skills, fibers is even more advanced concept, so you should invest some
time into going through fully understanding how j/s works if you are
planning to write nodejs code, it packs quite a lot of surprises if you are
coming from any other language, or even basic browser level j/s.

> Are you essentially adding a field to Fiber?
>
Adding a field to whatever object that Fiber() returned. This object is
what will be returned from Fiber.current, if the code is running within
that particular fiber.

> I tend to think of JS classes as Java classes, so this syntax is new to
> me. What does Fiber(function(){...}) do? Seems to return a fiber...
>
Fiber (in my code snippet) is a function (returned from require('fibers')).
You can invoke it directly (Fiber()) or as a constructor (new Fiber()).
This explains the difference:
http://programmers.stackexchange.com/questions/182433/fundamental-difference-between-fn-and-new-fn-in-javascript

In all case, this is definitely an off-topic for node-fibers at this point.

**Comment by jpaulm** [comment]
No problem!  Thanks for the tips!  Actually, I find node-fibers pretty straight-forward - it's the basic JavaScript stuff that I'm weak on!  Still, there's so much material out there about it that I'm sure it's just a matter of slogging away!  After 50+ years in the programming business I ought to be able to pick up another language!  :-)

Thanks again, and regards,

Paul
