### ISSUE TITLE
Weird bugs trying to install fibers

### ISSUE THREAD

**Issue by jpaulm** [laverdet/node-fibers#212]
I am getting a weird bug trying to install fibers on my Win7 machine:

https://github.com/jpaulm/jsfbp/pull/9#issuecomment-73722147

Help would be appreciated!

Paul M.

**Comment by jpaulm** [comment]
Sorry, @laverdet, my output is at https://github.com/jpaulm/jsfbp/pull/9#issuecomment-73636730  - the previous one I gave was from @comfreek, who is also having problems...

**Comment by alexlamsl** [comment]
`node 0.12` has updated the version of their underlying `v8` engine, so the bundled binary from the current `fibers` package won't work.

One way to work around this is to install Python and Visual Studio to let `node-gyp` perform the compilation. Another way is to wait patiently for the updated `fibers` package to include the latest version of binaries to work with the new `v8`.

**Comment by jpaulm** [comment]
Hi @alexlamsl , I installed python, and also node-gyp and they look good.  Doing my npm install, I get

```
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.Cpp.InvalidPlatform
.Targets(23,7): error MSB8007: The Platform for project 'fibers.vcxproj' is inv
alid.  Platform='x64'. You may be seeing this message because you are trying to
 build a project without a solution file, and have specified a non-default Plat
form that doesn't exist for this project. [C:\Users\Paul\Documents\GitHub\FBP-R
epos\jsfbp-master\node_modules\fibers\build\fibers.vcxproj]

```

Is this to do with Visual Studio - I think I have that, so do I need the Python plug-in?  Sorry to be rather obtuse... :-)

**Comment by alexlamsl** [comment]
That's okay, I don't find it all that intuitive either ;-)

Instructions detailed within `node-gyp`'s `README.md`:
https://github.com/TooTallNate/node-gyp#installation

**Comment by alexlamsl** [comment]
Looking at your message, it would seem that you are using a 32-bit Visual Studio to build a 64-bit solution file, which isn't going to fly...

**Comment by jpaulm** [comment]
Though the odd thing is that it looks like I am able to install node-gyp, although I get a warning about global being preferable. When I do npm install, I still get the message about invalid vcxproj ...???

**Comment by alexlamsl** [comment]
That global warning from `node-gyp` is benign. The problem is with your copy of Visual Studio - it's a 32-bit version, and as your OS is 64-bit, `fibers` needs to compile its binary accordingly, which your copy of Visual Studio does not support.

If you follow the instructions on `node-gyp` and install the version of Visual Studio as they suggest, then it should work.

**Comment by jpaulm** [comment]
Thanks Alex, I'll give that a try when I get back!  Thanks for your help!

**Comment by jpaulm** [comment]
Hi @alexlamsl it turns out that the problem is with node 12.0 - @tlrobinson figured it out, and when I tried 11.16, `npm install` worked!   @comfreek , did you try this - if so, can we close this issue?

**Comment by laverdet** [comment]
0.10.x has binaries distributed with it, 0.12.x does not. I'll release binaries at some point, or you can fix your Visual Studio configuration if you need it now.

**Comment by ComFreek** [comment]
I didn't want to install an old Node.js system-wide, so I download an old Node.js MSI package, extracted `node.exe`, placed it inside my project folder and created a startup script (which prepends the location of the old Node.js to the PATH). A guide can be found here: https://gist.github.com/ComFreek/c341bacfaae3aca887df

**Comment by jpaulm** [comment]
Maybe I should try that, and update my Readme accordingly...

Thanks,

Paul

**Comment by laverdet** [comment]
1.0.6 w/ new binaries is live on npm
