### ISSUE TITLE
only install with python 2.7

### ISSUE THREAD

**Issue by brianehlert** [laverdet/node-fibers#218]
The install fails with python version greater than 3
It should be updated for Python 3

The only way around is to install python 2.7 side by side and use the --python=python2.7 argument when installing.

**Comment by emgee3** [comment]
This isn't a node-fibers specific limitation, but rather the entire binary module system for node uses python 2.7.

**Comment by brianehlert** [comment]
Unfortunately, I had no issues with other modules.  it was not until I installed fibers that I had any issue.

**Comment by laverdet** [comment]
The key word in @emgee3's comment is "binary". node-fibers has a compilation stage which needs to invoke gyp.

See: [gyp issue #36](https://code.google.com/p/gyp/issues/detail?id=36)
