### ISSUE TITLE
Resetting the fiber and all sub-fibers

### ISSUE THREAD

**Issue by mitar** [laverdet/node-fibers#219]
Currently it does not seem there is a way to reset the fiber and make also all the fibers which were spawned from inside that fiber be automatically reset as well? The only way is to manually keep track of those fibers? But I worry that then there could some references to fibers kept which would then make memory leaks. Could that be something this package would provide?

**Comment by laverdet** [comment]
All fibers are created equally; there is no internal hierarchy or parent\child relationships. That's why they're called coroutines and not subroutines :)
