### ISSUE TITLE
Error while executing 'npm install fibers'

### ISSUE THREAD

**Issue by bondden** [laverdet/node-fibers#222]
## Steps to reproduce:
```npm install fibers```

## npm-debug.log:
https://gist.github.com/bondden/a00e0b19454fc7ce4b84#file-npm-debug-log-1

## Context:
| S/w param | S/w param value |
|--- |--- |
|OS |Windows 8.1|
|Terminal |CMD.exe|
|node version | 0.12.2|
|npm version | 2.7.4|

| Environment param | Env. param value |
|--- |--- |
|PYTHON | B:\p32\python2 |
|PATH | B:\p32\python2\;B:\p32\python2\Scripts;B:\p32\python3\;B:\p32\python3\Scripts;C:\Perl64\site\bin;C:\Perl64\bin;B:\pd\Oracle\Java\javapath;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;B:\p\nodejs\;B:\p\TortoiseHg\;B:\p32\Graphviz\bin;B:\p32\Git\cmd;B:\p32\GitExtensions\; |

**Comment by DBeardionaire** [comment]
I'm having the same log errors on my local windows machine(node v0.12.0) and on azure websites(Paas) node v0.10.32

I'm trying to build and deploy a demeteorized application on azure websites

**Comment by hyobyun** [comment]
I'm getting the same error on windows 7.

**Comment by laverdet** [comment]
Can you tell me what happens if you clone the project from github and run `node build` from that directory

**Comment by hyobyun** [comment]
I resoled the issue. I had changed the default directory of the command line on windows by editing HKEY_CURRENT_USER\Software\Microsoft\Command Processor "Autorun". Removing the Autorun variable resolved the problem.

**Comment by laverdet** [comment]
Got it. Once I get around to pushing out binaries for Node 0.12.x I think this will be fine.

**Comment by CTimmerman** [comment]
I guess i'm having the same issue with [Node 10 and Node 12 on Azure Web App](http://stackoverflow.com/questions/30775583/npm-install-g-fibers-fails-on-azure-web-app/30777580).

**Comment by laverdet** [comment]
1.0.6 w/ new binaries is live on npm
