### ISSUE TITLE
SLES 11.3 won't install

### ISSUE THREAD

**Issue by SparserLogic** [laverdet/node-fibers#224]
avadevimg1:/data/ava_file_server # npm install -g fibers
|
> fibers@1.0.5 install /root/.nvm/v0.10.36/lib/node_modules/fibers
> node ./build.js

sh: node: command not found

npm ERR! fibers@1.0.5 install: `node ./build.js`
npm ERR! Exit status 127
npm ERR!
npm ERR! Failed at the fibers@1.0.5 install script.
npm ERR! This is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.0.101-0.46-default
npm ERR! command "/root/.nvm/v0.10.36/bin/node" "/root/.nvm/v0.10.36/bin/npm" "install" "-g" "fibers"
npm ERR! cwd /data/ava_file_server
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

**Comment by danieleds** [comment]
Same for me on Ubuntu 15.04:
```
$ npm install fibers
\
> fibers@1.0.5 install /tmp/node_modules/fibers
> node ./build.js

sh: 1: node: not found
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! fibers@1.0.5 install: `node ./build.js`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the fibers@1.0.5 install script.
npm ERR! This is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.19.0-18-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "fibers"
npm ERR! cwd /tmp
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /tmp/npm-debug.log
npm ERR! not ok code 0
```

**Comment by SparserLogic** [comment]
Try a chmod 0777 on the nose executable or the parent directory.

The issue is that npm is trying to install fibers globally under a
different account.

**Comment by danieleds** [comment]
Tried, but I get the same issue :/
But maybe the problem isn't related to node-fibers: I noticed that it happens with "deasync" too...

**Comment by laverdet** [comment]
I don't think it's permission-related. I think the issue is that some distros use `nodejs` instead of `node`, which causes all kinds of headaches. This is being tracked in #180.

I believe if you do this:
`sudo ln -s /usr/bin/nodejs /usr/bin/node`

And try again it will work, assuming you have all the build tools installed as well.

**Comment by danieleds** [comment]
Perfect, it worked!
There's still another related issue, but I'll write in #180

**Comment by laverdet** [comment]
1.0.6 w/ new binaries is live on npm
