### ISSUE TITLE
Can't find "msbuild.exe" Error

### ISSUE THREAD

**Issue by tj-redwolf** [laverdet/node-fibers#225]
Hi, 
I am trying to install node-fibers, but I am getting error at msbuild.exe

C:\Users\TJ\codestation\NodeJs\testing\node-fibers>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\no
de-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )  else (rebuild --release )
gyp ERR! build error
gyp ERR! stack Error: Can't find "msbuild.exe". Do you have Microsoft Visual Studio C++ 2008+ installed?
gyp ERR! stack     at findMsbuild (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:121:23)

Though i was able to install node-gyp module separately, also I have MS Visual Studio 2013 Ultimate with update 4 on my machine. I am not able to think of possible cause of this issue during the installation.
Using node version : 0.12.2 
Let me know if you need any further details 

Regards,
Tushar Jain
tushar-jain@live.com

**Comment by tj-redwolf** [comment]
Also, node build gives following error:


child_process: customFds option is deprecated, use stdio instead.
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn node-gyp.cmd ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by laverdet** [comment]
Sounds like a problem with your build environment. Missing binaries is being tracked in #222, after I get around to fixing that it won't be an issue anymore regardless of broken environments.
