### ISSUE TITLE
Should add tarballs not just build script

### ISSUE THREAD

**Issue by inf3rno** [laverdet/node-fibers#228]
Building on windows is a nightmare, you should add binaries. Something like this:
```
"fibers": "https://github.com/icenium/node-fibers/tarball/v1.0.5.1",
```

**Comment by inf3rno** [comment]
Can't you use something else than node-gyp? It is hard to install and the result probably won't work on travis either.

**Comment by inf3rno** [comment]
I found that there is a tarball for linux:
```
"fibers": "https://github.com/icenium/node-fibers/tarball/v1.0.5.1",
```
isn't there something similar for windows?

**Comment by laverdet** [comment]
1.0.6 w/ new binaries is live on npm
