### ISSUE TITLE
Upload binaries please

### ISSUE THREAD

**Issue by layane** [laverdet/node-fibers#229]
I have a lot of problems to compile on win7 32bits and 64bits. Could you upload the binaries for 64/32 bits versions please?

Errors: https://gist.github.com/layane/6abf29f1040f1ec27d5c

Thanks for all

**Comment by laverdet** [comment]
Sorry this is taking so long. I got a new laptop which wiped out my bootcamp installation and then I lost all my USB drives so I can't reinstall. I have a new one coming from Amazon so hopefully I can get all that set up over the next week.

**Comment by laverdet** [comment]
1.0.6 w/ new binaries is live on npm
