### ISSUE TITLE
Missing binaries for v8-4.3

### ISSUE THREAD

**Issue by fbrinker** [laverdet/node-fibers#230]
Hello,

I try to use the node-sync module in my electron project. This depends on node-fibers. 
Now there is a problem... when i try to require Sync (or an installation of Fibers directly), i get the following error:
> \node_modules\fibers\bin\win32-x64-v8-4.3\fibers.node is missing. Try reinstalling `node-fibers`

There are only win32-x64-v8-4.2 binaries available :(

To see what i have already tried, please see my following two questions / threads:
http://stackoverflow.com/questions/31215400/nodejs-sync-cannot-find-fibers-binaries
and https://discuss.atom.io/t/synchronizing-tasks-with-electron-fibers-not-working/18472

* Is there any solution or sth. i could try to solve this problem?
* Is it possible to compile fibers for v8-4.3? I guess the problem is, that electron uses io.js 2.3.1 but with v8 4.3, not 4.2 as usual (when downloading io.js from the official website).

**Comment by laverdet** [comment]
Just build the binaries yourself. It's not too hard. Install Python 2.7, Visual Studio Express, and the 64-bit SDK (all free). Guide is here: https://github.com/TooTallNate/node-gyp

Then just clone the repo and type `node build` in the fibers directory

**Comment by fbrinker** [comment]
Thanks it's working now. I did the following:
```
cd ~/my-project-root/
npm install sync
cd ./node_modules/sync/node_modules/fibers
node-gyp configure
HOME=~/.electron-gyp node-gyp rebuild --target=0.29.1 --arch=x64 --dist-url=https://atom.io/download/atom-shell
```
Then i've created the missing directory and moved the new binary there:
```
mkdir bin/win32-x64-v8-4.3
mv build/Release/fibers.node bin/win32-x64-v8-4.3/fibers.node
```

Now Sync works like a charm. Thank you. Was this the correct way, or is there a better way or best practice? Is there a way to publish this binary for other electron users?

**Comment by laverdet** [comment]
When I'm building binaries I just do `node build` and it drops the binary in the right place. build.js is a script in the root directory of the repo that just calls `node-gyp rebuild` and then moves the file like you did manually.

The only way to get the binaries into npm is if I personally support them. And currently I'm supporting latest Node, the previous Node, and the latest io.js. And I'm also supporting 3 OSs and 2 architectures, it's already out of control. Wayy too many binaries for me to keep track of and personally test. The build process is fairly painless though, so I'd encourage you to either publish a `fibers-electron` to npm with binaries or just tell people how to build it themselves.

If there's bugs you find from a fresh compilation I'll look into those; I just don't want to support a binary release of 20+ builds :(

**Comment by fbrinker** [comment]
Ah i understand. Thanks :)

**Comment by blue7wings** [comment]
@fbrinker Thank you, Work for me!
