### ISSUE TITLE
Installation fails in AIX

### ISSUE THREAD

**Issue by gireeshpunathil** [laverdet/node-fibers#231]
bash-4.2$ npm install fibers
\
> fibers@1.0.6 install /home/gireesh/aix/xlc/statsd/node/node_modules/fibers
> node build.js || nodejs build.js

  CXX(target) Release/obj.target/fibers/src/fibers.o
In file included from ../src/coroutine.h:4:0,
                 from ../src/fibers.cc:1:
../src/libcoro/coro.h:302:25: error: missing ')' in expression
../src/libcoro/coro.h:313:1: error: 'error' does not name a type
In file included from ../src/fibers.cc:1:0:
../src/coroutine.h:14:16: error: field 'context' has incomplete type
gmake: *** [Release/obj.target/fibers/src/fibers.o] Error 1
...

The root cause is basically two problems in the source: (line 302 and 313 of the module fibers/src/libcoro/coro.h)

  +298  #if !defined CORO_LOSER      && !defined CORO_UCONTEXT \
  +299      && !defined CORO_SJLJ    && !defined CORO_LINUX \
  +300      && !defined CORO_IRIX    && !defined CORO_ASM \
  +301      && !defined CORO_PTHREAD && !defined CORO_FIBER
  +302  # if defined WINDOWS && (defined __i386 || (__x86_64 || defined _M_IX86 || defined _M_AMD64)
  +303  #  define CORO_ASM 1
  +304  # elif defined WINDOWS || defined _WIN32
  +305  #  define CORO_LOSER 1 /* you don't win with windoze */
  +306  # elif __linux && (__i386 || (__x86_64 && !__ILP32))
  +307  #  define CORO_ASM 1
  +308  # elif defined HAVE_UCONTEXT_H
  +309  #  define CORO_UCONTEXT 1
  +310  # elif defined HAVE_SETJMP_H && defined HAVE_SIGALTSTACK
  +311  #  define CORO_SJLJ 1
  +312  # else
  +313  error unknown or unsupported architecture
  +314  # endif
  +315  #endif

An obvious typo in 302, a matching close bracket is missing in the line.

As we are AIX, none of the #if defined ladders matches and the compiler lands up in line 313, which by all means should have been a #errror compiler directive, but as the # is missing, it was treated as a program token, and hence the error.

**Comment by gireeshpunathil** [comment]
Any updates please?

**Comment by laverdet** [comment]
If think this guy fixed your problem https://github.com/laverdet/node-fibers/pull/279

**Comment by gireeshpunathil** [comment]
Yes, it has. Thank you!
