### ISSUE TITLE
V 1.0.5 binaries for windows no longer on npm? 

### ISSUE THREAD

**Issue by sjmcdowall** [laverdet/node-fibers#239]
I am using Meteor, which has a dependency on Fibers@1.0.5.  When I try to npm install -- I get an error due to Python not being found (and it's not there, so that makes sense) because it doesn't appear to be able to find a compiled binary for windows?  This is Windows 7 - node 0.10.36 - x64 bit machine -- but x32 binary I think? 

Ok -- So looking into this more, I'm more confused.  I downloaded by hand the TGZ file for 1.0.5 and I certainly see a nice looking win32-x64-v8-3.14  which should match (and does actually I ran node in REPL mode and compared) the version.  So now I have no idea why it doesn't claim to find a binary version ..

**Comment by laverdet** [comment]
What does npm install tell you?

**Comment by sjmcdowall** [comment]
Here is the output from the npm install -- as you can see it doesn't match the test (for whatever reason) to see if the binary is there ... so attempts to compile which won't work because this isn't a development machine... 

C:\deploy\Galaxy\RTViewer\programs\server>npm install
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
/
> fibers@1.0.5 install C:\deploy\Galaxy\RTViewer\programs\server\node_modules\
bers
> node ./build.js


C:\deploy\Galaxy\RTViewer\programs\server\node_modules\fibers>node "C:\Program
iles\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin
ode-gyp.js" rebuild --release
Building the projects in this solution one at a time. To enable parallel build
please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe"
 To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visu
l Studio 2005 or 3) add the location of the component to the system path if it
is installed elsewhere.  [C:\deploy\Galaxy\RTViewer\programs\server\node_modul
s\fibers\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.e
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_module
npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:82
12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_mo
les\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd C:\deploy\Galaxy\RTViewer\programs\server\node_modules\fibers
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok
Build failed

npm ERR! fibers@1.0.5 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fibers@1.0.5 install script.
npm ERR! This is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\n
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\deploy\Galaxy\RTViewer\programs\server
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

**Comment by sjmcdowall** [comment]
Oh bother -- never mind.  You can close this.  It appears that in their wondrous rationale -- Meteor has a specific forked version of node-fibers in their own github repository -- and it's THAT fibers that's being used .. and doesn't have a binary .. sigh.. sorry for the inconvenience..
