### ISSUE TITLE
Fiber Priority Queue

### ISSUE THREAD

**Issue by ccorcos** [laverdet/node-fibers#240]
I have a bunch of background process spawning into fibers. I call this defer function periodically i the background process to free up time for foreground processes.

```
defer = function (ms) {
  var fiber = Fiber.current;
  setTimeout(function() {
    fiber.run();
  }, ms);
  Fiber.yield();
};
```

However, I'm afraid I just end up with foreground processes littered throughout my background processes which is annoying. Is there any way to prioritize fibers? I need the foreground processes to always run before the background processes....

Thanks

**Comment by laverdet** [comment]
Fibers are considered "cooperative multitasking" which means you have full control over which fibers run and when. It's important to note that multitasking and parallelism are *not* the same thing, and it sounds like parallelism is what you are looking for. If you are looking to run multiple scripts at once you should look into either the `cluster` module or the Web Workers API.

**Comment by ccorcos** [comment]
cluster module?
