### ISSUE TITLE
Crash when used with lwip on Windows

### ISSUE THREAD

**Issue by medatech** [laverdet/node-fibers#241]
Found a weird issue that you get C++ Runtime error when node-fibers is used with the lwip project
https://github.com/EyalAr/lwip

![image](https://cloud.githubusercontent.com/assets/1839214/9607315/5b98410a-50c0-11e5-8d8d-a4a094ad28b9.png)

Steps to reproduce:

1. Install the two modules together
```
npm install lwip
npm install fibers
```

2. Run this script

```
require('lwip');
require('fibers');
```

Changing the order of which the two modules are included appears to have an impact in that the crash doesn't not occur.

**Comment by laverdet** [comment]
This is a known issue. It's best to include fibers before you include any other binary extensions.

Also you may try applying this patch and recompiling and it may fix your issue:
https://github.com/meteor/node-fibers/commit/d519f0c5971c33d99c902dad346b817e84bab001#commitcomment-12591271

**Comment by medatech** [comment]
Thanks @laverdet, I've managed to work around this by including fibers first.  If I get a bit of time I will see if I can figure out how to patch it and see what that does :)
