### ISSUE TITLE
Requesting one additional release on binaries for transition

### ISSUE THREAD

**Issue by BobDickinson** [laverdet/node-fibers#245]
I think the plan going forward in terms of binary support as stated in https://github.com/laverdet/node-fibers/issues/236 makes sense in general, and I sympathize with the work involved in maintaining all those binaries.  However, in the very near term, it presents somewhat of a problem for us.

We're using 1.0.7 now for 0.10.x and 0.12.x and the pre-built binaries work great (thanks!).  But our concern is that it is reasonable that someone might be running 4.0.x now and 1.0.7 doesn't contain those binaries.  If there is a near term release that has only the 4.0.x binaries, that's going to be a problem with those still running 0.10.x/0.12.x, and I guess iojs (which, at least in the near term, isn't totally unreasonable).  

What we would really appreciate is a new release that had the current binaries plus 4.0.x binaries.  That would allow us to support everything that's relatively reasonable (including 4.0.0) right now, and give us until April-ish to adopt the stance that we only support the current and previous releases of Node (by that time, that will be a reasonable position).  And after this proposed "ALL THE BINARIES" release, going to your proposed binary support strategy would be fine for us.  So anyway, please consider a one-more-time-only all the binaries release including the 4.0.x binaries once those are ready.

**Comment by BobDickinson** [comment]
Not sure if this is helpful, but I built Win64 for 4.0.0.  I ran into a known node-gyp issue:

https://github.com/nodejs/node-gyp/issues/724

After manually upgrading node-gyp, I was able to build.  I got some warnings, as below, which I assume are normal:
```
c:\Dev\Test\scratch\node_modules\fibers>node "C:\Users\Bob\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --release
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  fibers.cc
  coroutine.cc
..\src\fibers.cc(727): warning C4244: 'argument' : conversion from 'size_t' to 'double', possible loss of data [c:\Dev\Test\scratch\node_modules\fibers\build\fibers.vcxproj]
..\src\fibers.cc(731): warning C4244: '=' : conversion from 'double' to 'size_t', possible loss of data [c:\Dev\Test\scratch\node_modules\fibers\build\fibers.vcxproj]
..\src\fibers.cc(738): warning C4244: 'argument' : conversion from 'size_t' to 'double', possible loss of data [c:\Dev\Test\scratch\node_modules\fibers\build\fibers.vcxproj]
..\src\coroutine.cc(110): warning C4552: '!' : operator has no effect; expected operator with side-effect [c:\Dev\Test\scratch\node_modules\fibers\build\fibers.vcxproj]
..\src\coroutine.cc(186): warning C4267: 'argument' : conversion from 'size_t' to 'unsigned int', possible loss of data [c:\Dev\Test\scratch\node_modules\fibers\build\fibers.vcxproj]
  coro.c
  win_delay_load_hook.c
     Creating library c:\Dev\Test\scratch\node_modules\fibers\build\Release\fibers.lib and object c:\Dev\Test\scratch\node_modules\fibers\build\Release\fibers.exp
  Generating code
  Finished generating code
  fibers.vcxproj -> c:\Dev\Test\scratch\node_modules\fibers\build\Release\\fibers.node
Installed in `c:\Dev\Test\scratch\node_modules\fibers\bin\win32-x64-v8-4.5\fibers.node`
fibers@1.0.7 node_modules\fibers
```
Test results were:
```
already-running.js: pass
bad-context.js: pass
child-process.js: pass
current.js: pass
exec.js: pass
exit.js: pass
fibonacci.js: pass
finish-multiple.js: pass
future-exception.js: pass
future.js: pass
illegal-yield.js: pass
pool.js: pass
process-title.js: pass
stack-overflow.js: pass
stack-overflow2.js: *fail*
code: 3221225477
stderr:
stdout:
stack-overflow3.js: *fail*
code: 3221225477
stderr:
stdout:
started.js: pass
unwind.js: pass
```
OSX built clean on 4.0.0, and the tests on that platform looked like:
```
already-running.js: pass
bad-context.js: pass
child-process.js: pass
current.js: pass
exec.js: pass
exit.js: pass
fibonacci.js: pass
finish-multiple.js: pass
future-exception.js: pass
future.js: pass
illegal-yield.js: pass
pool.js: pass
process-title.js: pass
stack-overflow.js: pass
stack-overflow2.js: *fail*
code: null
stderr: 
stdout: 
stack-overflow3.js: *fail*
code: null
stderr: 
stdout: 
started.js: pass
unwind.js: pass
```

**Comment by BobDickinson** [comment]
Trying not to be a pain in the ass, but just curious about whether this is in the plans, and if so, if there is any rough timeframe for such a release.  If not, we'll probably attempt the route of building the 4.0 binaries ourselves and distributing fibers as a bundledDependency in the short term, but that's a little scary/creepy for us for any number of reasons.

**Comment by laverdet** [comment]
Binaries are in npm for v5.1.0
