### ISSUE TITLE
Binary missing

### ISSUE THREAD

**Issue by rclai** [laverdet/node-fibers#247]
`Error: /root/fibers-test/node_modules/fibers/bin/linux-x64-v8-4.5/fibers.node is missing. Try reinstalling node-fibers?`

I'm running on a 14.04. The latest binary that I see on the `bin` folder is `linux-x64-v8-4.2`.

And I was also trying to run this using Node 4.1.0. Don't know if this makes a difference?

**Comment by laverdet** [comment]
Run `node build` in the fibers directory to rebuild your binary.

**Comment by Mysterius** [comment]
I have this problem too and "node build" says the following :
*linux-x64-v8-3.14` exists; testing
Binary is fine; exiting*

I don't understand.

**Comment by tampham47** [comment]
I got the same issue, I am running on Centos7, below is my node & npm version:
node version: 4.4.7
npm version: 2.15.8
