### ISSUE TITLE
Build on Node.js 4.1 at Travis CI does not work

### ISSUE THREAD

**Issue by kaplas** [laverdet/node-fibers#249]
Our (private) project depends on [`sync`](https://github.com/ybogdanov/node-sync), which depends on `fibers`. Everything works on our OSX dev laptops as well as at Heroku, where apparently there are pre-built binaries available for `fibers`. However, apparenly pre-built binaries are not available at Travis CI, as manual build of the package is triggered instead. And that does not work.

I created a test repository for showcasing this problem:
[kaplas/node-fibers-testing-at-travis](https://github.com/kaplas/node-fibers-testing-at-travis)

The corresponding Travis CI build log is here:
[kaplas/node-fibers-testing-at-travis build #1](https://travis-ci.org/kaplas/node-fibers-testing-at-travis/builds/81554149)

Snippet from the beginning of problems:
```
In file included from /home/travis/.node-gyp/4.1.0/include/node/node.h:42:0,
                 from ../src/coroutine.h:1,
                 from ../src/fibers.cc:1:
/home/travis/.node-gyp/4.1.0/include/node/v8.h:336:1: error: expected unqualified-id before ‘using’
/home/travis/.node-gyp/4.1.0/include/node/v8.h:469:1: error: expected unqualified-id before ‘using’
/home/travis/.node-gyp/4.1.0/include/node/v8.h:852:1: error: expected unqualified-id before ‘using’
../src/fibers.cc:40:58: error: ‘Handle’ has not been declared
../src/fibers.cc:40:64: error: expected ‘,’ or ‘...’ before ‘<’ token
../src/fibers.cc: In function ‘void uni::Reset(v8::Isolate*, v8::Persistent<T, v8::NonCopyablePersistentTraits<T> >&, int)’:
../src/fibers.cc:41:29: error: ‘handle’ was not declared in this scope

... and so on
```

I don't really understand what is happening there, but apparently the compiling step is going horribly wrong. Any idea if I'm doing something wrong here, or if this is a problem of Travis CI?

Thanx for your help in advance :)

**Comment by cismous** [comment]
+1

**Comment by m1kc** [comment]
Same problem. It looks like g++ on Travis is kinda outdated.

**Comment by kaplas** [comment]
@m1kc Thanx for leading me to the right tracks!

The problem really is that GCC version is outdated in the current Travis CI Node.js 4.x build pack. Here is the related issue on their GitHub:
https://github.com/travis-ci/travis-ci/issues/4771

For the time being, this problem can be hack-fixed by setting the GCC version manually. In practise, add these lines to your `.travis.yml`:
```
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
```

...and the world will be fine. [Here's my test commit](https://github.com/kaplas/node-fibers-testing-at-travis/commit/885f329e93fb6710cade3926c7e62d1cd966182c) and [it really fixed my test build](https://travis-ci.org/kaplas/node-fibers-testing-at-travis/builds/82686882).

**Comment by laverdet** [comment]
Awesome, glad you got it fixed!
