### ISSUE TITLE
Cant install fibers on windows npm coommand

### ISSUE THREAD

**Issue by retslig** [laverdet/node-fibers#251]
I am not seeing anything that sticks in the log about the error what is wrong?

C:\Program Files\nodejs>npm install fibers --save
\
> fibers@1.0.7 install C:\Program Files\nodejs\node_modules\fibers
> node build.js || nodejs build.js

C:\Program Files\nodejs\node_modules\fibers>node "C:\Users\nmg.RAVEN\AppData\Roa
ming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node
-gyp.js" rebuild --release
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 404 status code downloading SHASUMS.txt
gyp ERR! stack     at Request.<anonymous> (C:\Users\nmg.RAVEN\AppData\Roaming\np
m\node_modules\npm\node_modules\node-gyp\lib\install.js:316:18)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onResponse (C:\Users\nmg.RAVEN\AppData\Roaming\npm
\node_modules\npm\node_modules\request\request.js:832:10)
gyp ERR! stack     at ClientRequest.g (events.js:260:16)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:415:21)

gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)

gyp ERR! stack     at Socket.socketOnData (_http_client.js:305:20)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\nmg.RAVEN\\Ap
pData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js
" "rebuild" "--release"
gyp ERR! cwd C:\Program Files\nodejs\node_modules\fibers
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v0.13.1
gyp ERR! not ok
Build failed
'nodejs' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! fibers@1.0.7 install: `node build.js || nodejs build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fibers@1.0.7 install script.
npm ERR! This is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js || nodejs build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\nmg.RAVEN\\Ap
pData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "fibers" "--s
ave"
npm ERR! cwd C:\Program Files\nodejs
npm ERR! node -v v4.2.1
npm ERR! npm -v 1.4.16
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Program Files\nodejs\npm-debug.log
npm ERR! not ok code 0

C:\Program Files\nodejs>

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\nmg.RAVEN\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'fibers',
1 verbose cli   '--save' ]
2 info using npm@1.4.16
3 info using node@v4.2.1
4 verbose cache add [ 'fibers', null ]
5 verbose cache add name=undefined spec="fibers" args=["fibers",null]
6 verbose parsed url Url {
6 verbose parsed url   protocol: null,
6 verbose parsed url   slashes: null,
6 verbose parsed url   auth: null,
6 verbose parsed url   host: null,
6 verbose parsed url   port: null,
6 verbose parsed url   hostname: null,
6 verbose parsed url   hash: null,
6 verbose parsed url   search: null,
6 verbose parsed url   query: null,
6 verbose parsed url   pathname: 'fibers',
6 verbose parsed url   path: 'fibers',
6 verbose parsed url   href: 'fibers' }
7 silly lockFile d3d85a22-fibers fibers
8 verbose lock fibers C:\Users\nmg.RAVEN\AppData\Roaming\npm-cache\d3d85a22-fibers.lock
9 silly lockFile d3d85a22-fibers fibers
10 silly lockFile d3d85a22-fibers fibers
11 verbose addNamed [ 'fibers', '' ]
12 verbose addNamed [ null, '*' ]
13 silly lockFile 0ebffbee-fibers fibers@
14 verbose lock fibers@ C:\Users\nmg.RAVEN\AppData\Roaming\npm-cache\0ebffbee-fibers.lock
15 silly addNameRange { name: 'fibers', range: '*', hasData: false }
16 verbose request where is /fibers
17 verbose request registry https://registry.npmjs.org/
18 verbose request id 9170bfcae8cffa25
19 verbose url raw /fibers
20 verbose url resolving [ 'https://registry.npmjs.org/', './fibers' ]
21 verbose url resolved https://registry.npmjs.org/fibers
22 verbose request where is https://registry.npmjs.org/fibers
23 info trying registry request attempt 1 at 4:04:42 PM
24 verbose etag "EVWXHE5K16HTS5BY9L958MZ0K"
25 http GET https://registry.npmjs.org/fibers
26 http 304 https://registry.npmjs.org/fibers
27 silly registry.get cb [ 304,
27 silly registry.get   { date: 'Thu, 15 Oct 2015 21:04:42 GMT',
27 silly registry.get     via: '1.1 varnish',
27 silly registry.get     'cache-control': 'max-age=60',
27 silly registry.get     etag: '"EVWXHE5K16HTS5BY9L958MZ0K"',
27 silly registry.get     age: '25',
27 silly registry.get     connection: 'close',
27 silly registry.get     'x-served-by': 'cache-dfw1833-DFW',
27 silly registry.get     'x-cache': 'HIT',
27 silly registry.get     'x-cache-hits': '1',
27 silly registry.get     'x-timer': 'S1444943082.941361,VS0,VE0',
27 silly registry.get     vary: 'Accept' } ]
28 verbose etag https://registry.npmjs.org/fibers from cache
29 silly addNameRange number 2 { name: 'fibers', range: '*', hasData: true }
30 silly addNameRange versions [ 'fibers',
30 silly addNameRange   [ '0.1.0',
30 silly addNameRange     '0.1.1',
30 silly addNameRange     '0.1.2',
30 silly addNameRange     '0.1.3',
30 silly addNameRange     '0.1.4',
30 silly addNameRange     '0.1.6',
30 silly addNameRange     '0.1.7',
30 silly addNameRange     '0.1.8',
30 silly addNameRange     '0.2.0',
30 silly addNameRange     '0.2.1',
30 silly addNameRange     '0.2.2',
30 silly addNameRange     '0.2.3',
30 silly addNameRange     '0.2.4',
30 silly addNameRange     '0.2.5',
30 silly addNameRange     '0.2.6',
30 silly addNameRange     '0.5.0',
30 silly addNameRange     '0.6.0',
30 silly addNameRange     '0.5.1',
30 silly addNameRange     '0.6.1',
30 silly addNameRange     '0.6.2',
30 silly addNameRange     '0.6.3',
30 silly addNameRange     '0.6.4',
30 silly addNameRange     '0.6.5',
30 silly addNameRange     '0.6.6',
30 silly addNameRange     '0.6.7',
30 silly addNameRange     '0.6.8',
30 silly addNameRange     '0.6.9',
30 silly addNameRange     '1.0.0',
30 silly addNameRange     '1.0.1',
30 silly addNameRange     '1.0.2',
30 silly addNameRange     '1.0.4',
30 silly addNameRange     '1.0.5',
30 silly addNameRange     '1.0.6-b',
30 silly addNameRange     '1.0.7' ] ]
31 verbose addNamed [ 'fibers', '1.0.7' ]
32 verbose addNamed [ '1.0.7', '1.0.7' ]
33 silly lockFile 062b402d-fibers-1-0-7 fibers@1.0.7
34 verbose lock fibers@1.0.7 C:\Users\nmg.RAVEN\AppData\Roaming\npm-cache\062b402d-fibers-1-0-7.lock
35 silly lockFile 062b402d-fibers-1-0-7 fibers@1.0.7
36 silly lockFile 062b402d-fibers-1-0-7 fibers@1.0.7
37 silly lockFile 0ebffbee-fibers fibers@
38 silly lockFile 0ebffbee-fibers fibers@
39 silly resolved [ { name: 'fibers',
39 silly resolved     version: '1.0.7',
39 silly resolved     description: 'Cooperative multi-tasking for Javascript',
39 silly resolved     keywords:
39 silly resolved      [ 'fiber',
39 silly resolved        'fibers',
39 silly resolved        'coroutine',
39 silly resolved        'thread',
39 silly resolved        'async',
39 silly resolved        'parallel',
39 silly resolved        'worker',
39 silly resolved        'future',
39 silly resolved        'promise' ],
39 silly resolved     homepage: 'https://github.com/laverdet/node-fibers',
39 silly resolved     author:
39 silly resolved      { name: 'Marcel Laverdet',
39 silly resolved        email: 'marcel@laverdet.com',
39 silly resolved        url: 'https://github.com/laverdet/' },
39 silly resolved     main: 'fibers',
39 silly resolved     scripts:
39 silly resolved      { install: 'node build.js || nodejs build.js',
39 silly resolved        test: 'node test.js || nodejs test.js' },
39 silly resolved     repository:
39 silly resolved      { type: 'git',
39 silly resolved        url: 'git://github.com/laverdet/node-fibers.git' },
39 silly resolved     license: 'MIT',
39 silly resolved     engines: { node: '>=0.5.2' },
39 silly resolved     gitHead: '8c591087fcc5768d209ff8a30979c9257503d13f',
39 silly resolved     bugs: { url: 'https://github.com/laverdet/node-fibers/issues' },
39 silly resolved     _id: 'fibers@1.0.7',
39 silly resolved     _shasum: '7dabae2b238188caa3748a8968c3c9df91752982',
39 silly resolved     _from: 'fibers@',
39 silly resolved     _npmVersion: '2.11.3',
39 silly resolved     _nodeVersion: '2.3.2',
39 silly resolved     _npmUser: { name: 'laverdet', email: 'marcel.npm@laverdet.com' },
39 silly resolved     maintainers: [ [Object] ],
39 silly resolved     dist:
39 silly resolved      { shasum: '7dabae2b238188caa3748a8968c3c9df91752982',
39 silly resolved        tarball: 'http://registry.npmjs.org/fibers/-/fibers-1.0.7.tgz' },
39 silly resolved     directories: {},
39 silly resolved     _resolved: 'https://registry.npmjs.org/fibers/-/fibers-1.0.7.tgz',
39 silly resolved     readme: 'ERROR: No README data found!' } ]
40 info install fibers@1.0.7 into C:\Program Files\nodejs
41 info installOne fibers@1.0.7
42 verbose node_modules\fibers unbuild
43 verbose tar unpack C:\Users\nmg.RAVEN\AppData\Roaming\npm-cache\fibers\1.0.7\package.tgz
44 silly lockFile f69f53e3-Files-nodejs-node-modules-fibers tar://C:\Program Files\nodejs\node_modules\fibers
45 verbose lock tar://C:\Program Files\nodejs\node_modules\fibers C:\Users\nmg.RAVEN\AppData\Roaming\npm-cache\f69f53e3-Files-nodejs-node-modules-fibers.lock
46 silly lockFile e73f3909-m-cache-fibers-1-0-7-package-tgz tar://C:\Users\nmg.RAVEN\AppData\Roaming\npm-cache\fibers\1.0.7\package.tgz
47 verbose lock tar://C:\Users\nmg.RAVEN\AppData\Roaming\npm-cache\fibers\1.0.7\package.tgz C:\Users\nmg.RAVEN\AppData\Roaming\npm-cache\e73f3909-m-cache-fibers-1-0-7-package-tgz.lock
48 silly gunzTarPerm modes [ '755', '644' ]
49 silly gunzTarPerm extractEntry package.json
50 silly gunzTarPerm extractEntry .npmignore
51 silly gunzTarPerm extractEntry README.md
52 silly gunzTarPerm extractEntry LICENSE
53 silly gunzTarPerm extractEntry quick-test.js
54 silly gunzTarPerm extractEntry future.js
55 silly gunzTarPerm extractEntry build.js
56 silly gunzTarPerm extractEntry test.js
57 silly gunzTarPerm extractEntry fibers.js
58 silly gunzTarPerm extractEntry binding.gyp
59 silly gunzTarPerm extractEntry bin/.npmignore
60 silly gunzTarPerm extractEntry bin/win32-x64-v8-4.2/fibers.node
61 silly gunzTarPerm extractEntry bin/darwin-ia32-v8-3.28/fibers.node
62 silly gunzTarPerm extractEntry bin/darwin-ia32-v8-4.2/fibers.node
63 silly gunzTarPerm extractEntry bin/darwin-x64-v8-3.14/fibers.node
64 silly gunzTarPerm extractEntry bin/darwin-x64-v8-3.28/fibers.node
65 silly gunzTarPerm extractEntry bin/darwin-x64-v8-4.2/fibers.node
66 silly gunzTarPerm extractEntry bin/linux-ia32-v8-3.14/fibers.node
67 silly gunzTarPerm extractEntry bin/linux-ia32-v8-3.28/fibers.node
68 silly gunzTarPerm extractEntry bin/linux-ia32-v8-4.2/fibers.node
69 silly gunzTarPerm extractEntry bin/darwin-ia32-v8-3.14/fibers.node
70 silly gunzTarPerm extractEntry bin/linux-x64-v8-3.28/fibers.node
71 silly gunzTarPerm extractEntry bin/linux-x64-v8-4.2/fibers.node
72 silly gunzTarPerm extractEntry bin/repl
73 silly gunzTarPerm extractEntry bin/win32-ia32-v8-3.14/fibers.node
74 silly gunzTarPerm extractEntry bin/win32-ia32-v8-3.28/fibers.node
75 silly gunzTarPerm extractEntry bin/win32-ia32-v8-4.2/fibers.node
76 silly gunzTarPerm extractEntry bin/win32-x64-v8-3.14/fibers.node
77 silly gunzTarPerm extractEntry bin/win32-x64-v8-3.28/fibers.node
78 silly gunzTarPerm extractEntry bin/linux-x64-v8-3.14/fibers.node
79 silly gunzTarPerm extractEntry src/coroutine.cc
80 silly gunzTarPerm extractEntry src/coroutine.h
81 silly gunzTarPerm extractEntry src/fibers.cc
82 silly gunzTarPerm extractEntry src/libcoro/README
83 silly gunzTarPerm extractEntry src/libcoro/LICENSE
84 silly gunzTarPerm extractEntry src/libcoro/conftest.c
85 silly gunzTarPerm extractEntry src/libcoro/coro.c
86 silly gunzTarPerm extractEntry src/libcoro/coro.h
87 silly gunzTarPerm extractEntry test/already-running.js
88 silly gunzTarPerm extractEntry test/exit.js
89 silly gunzTarPerm extractEntry test/fibonacci.js
90 silly gunzTarPerm extractEntry test/finish-multiple.js
91 silly gunzTarPerm extractEntry test/future-exception.js
92 silly gunzTarPerm extractEntry test/exec.js
93 silly gunzTarPerm extractEntry test/illegal-yield.js
94 silly gunzTarPerm extractEntry test/pool.js
95 silly gunzTarPerm extractEntry test/process-title.js
96 silly gunzTarPerm extractEntry test/stack-overflow.js
97 silly gunzTarPerm extractEntry test/stack-overflow2.js
98 silly gunzTarPerm extractEntry test/current.js
99 silly gunzTarPerm extractEntry test/stack-overflow3.js
100 silly gunzTarPerm extractEntry test/child-process.js
101 silly gunzTarPerm extractEntry test/started.js
102 silly gunzTarPerm extractEntry test/bad-context.js
103 silly gunzTarPerm extractEntry test/unwind.js
104 silly gunzTarPerm extractEntry test/future.js
105 silly lockFile f69f53e3-Files-nodejs-node-modules-fibers tar://C:\Program Files\nodejs\node_modules\fibers
106 silly lockFile f69f53e3-Files-nodejs-node-modules-fibers tar://C:\Program Files\nodejs\node_modules\fibers
107 silly lockFile e73f3909-m-cache-fibers-1-0-7-package-tgz tar://C:\Users\nmg.RAVEN\AppData\Roaming\npm-cache\fibers\1.0.7\package.tgz
108 silly lockFile e73f3909-m-cache-fibers-1-0-7-package-tgz tar://C:\Users\nmg.RAVEN\AppData\Roaming\npm-cache\fibers\1.0.7\package.tgz
109 info preinstall fibers@1.0.7
110 verbose readDependencies using package.json deps
111 verbose readDependencies using package.json deps
112 silly resolved []
113 verbose about to build C:\Program Files\nodejs\node_modules\fibers
114 info build C:\Program Files\nodejs\node_modules\fibers
115 verbose linkStuff [ false, false, false, 'C:\\Program Files\\nodejs\\node_modules' ]
116 info linkStuff fibers@1.0.7
117 verbose linkBins fibers@1.0.7
118 verbose linkMans fibers@1.0.7
119 verbose rebuildBundles fibers@1.0.7
120 info install fibers@1.0.7
121 verbose unsafe-perm in lifecycle true
122 info fibers@1.0.7 Failed to exec install script
123 verbose node_modules\fibers unbuild
124 info preuninstall fibers@1.0.7
125 info uninstall fibers@1.0.7
126 verbose true,C:\Program Files\nodejs\node_modules,C:\Program Files\nodejs\node_modules unbuild fibers@1.0.7
127 info postuninstall fibers@1.0.7
128 error fibers@1.0.7 install: `node build.js || nodejs build.js`
128 error Exit status 1
129 error Failed at the fibers@1.0.7 install script.
129 error This is most likely a problem with the fibers package,
129 error not with npm itself.
129 error Tell the author that this fails on your system:
129 error     node build.js || nodejs build.js
129 error You can get their info via:
129 error     npm owner ls fibers
129 error There is likely additional logging output above.
130 error System Windows_NT 6.1.7601
131 error command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\nmg.RAVEN\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "fibers" "--save"
132 error cwd C:\Program Files\nodejs
133 error node -v v4.2.1
134 error npm -v 1.4.16
135 error code ELIFECYCLE
136 verbose exit [ 1, true ]

**Comment by laverdet** [comment]
Please install node v5.1.0 and try again
