### ISSUE TITLE
fibers (breaks in near future) on NetBSD

### ISSUE THREAD

**Issue by TomFreudenberg** [laverdet/node-fibers#253]
Hi Marcel ( @laverdet )

Again coming from porting meteor now on NetBSD there are some conflicts. This time it is not node-fibers directly the case but it will become a case for node-fibers as well.

node-gyp does currently not support a proper OS value when using on NetBSD. The result is `linux` what is wrong.

I send in a [PR to chromium](https://codereview.chromium.org/1421073004/) as well as to [the node-gyp maintainer](https://github.com/nodejs/node-gyp/pull/803). Hopefully they will merge, I can't see why not.

In case of the merge, node-fibers will break on NetBSD because of missing define – `OS=="linux"` will not match anymore, the new value is `OS=="netbsd"`:

https://github.com/laverdet/node-fibers/blob/master/binding.gyp#L41-L43

**My question is now:**

In which line, respective what define, is important to NetBSD

1. 'CORO_UCONTEXT'
1. 'CORO_SJLJ'
1. 'CORO_ASM'

I tried all 3 and all worked on NetBSD but I am not sure what this does change on fibers. Could you please advise me, what define to use.

I will prepare a PR if things go in place.

Thanks for a short feedback
Tom

**Comment by TomFreudenberg** [comment]
Hi Marcel ( @laverdet ) , could you be so kind and give me a short hint what "define" from above I should use on NetBSD to finish the update on that OS. 

Thanks for your time in advance
Tom

**Comment by laverdet** [comment]
I prefer UCONTEXT because it's pretty standard, but there's not a whole lot of differences between the 3 if they all work. Supposedly ASM is "fastest" but not a whole lot of time is spent in that code anyway so it shouldn't make a difference.

Documentation for each define is in src/libcoro/coro.h

**Comment by TomFreudenberg** [comment]
Hi Marcel, thanks for your feedback again
