### ISSUE TITLE
Issues installing version 1.0.8 in elastic beanstalk on AWS

### ISSUE THREAD

**Issue by rjerrems** [laverdet/node-fibers#257]
Hi There,

We are currently experiencing issues when installing the latest version of fibers on Amazon Linux with the following output: 

```shell
npm ERR! fibers@1.0.8 install: `node build.js || nodejs build.js`
  npm ERR! Exit status 127
  npm ERR!
  npm ERR! Failed at the fibers@1.0.8 install script.
  npm ERR! This is most likely a problem with the fibers package,
  npm ERR! not with npm itself.
  npm ERR! Tell the author that this fails on your system:
  npm ERR!     node build.js || nodejs build.js
  npm ERR! You can get their info via:
  npm ERR!     npm owner ls fibers
  npm ERR! There is likely additional logging output above.
  npm ERR! System Linux 3.14.42-31.38.amzn1.x86_64
  npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "fibers" "semver" "source-map-support" "underscore"
  npm ERR! cwd /tmp/deployment/application/bundle
  npm ERR! node -v v0.10.40
  npm ERR! npm -v 1.4.28
  npm ERR! code ELIFECYCLE
  npm ERR! not ok code 0
```

When rolling back to the previous version fibers@1.0.7, npm install runs without any issues. Let me know if I can provide any additional information to help debug.

Thanks,
Rohan

**Comment by jimgeiger** [comment]
We're also having this problem on Windows Server 2012 when running in Bamboo.  Our case it hangs when apparently trying to run build.js.

**Comment by laverdet** [comment]
Please use either node version 4.x or 5.x. If you want to use another version you will need to setup g++ on your system.
