### ISSUE TITLE
Cant install fibers: Exit status 127

### ISSUE THREAD

**Issue by dmitrika** [laverdet/node-fibers#258]
Trying to deploy Meteor APP on server.

Have: Red Hat OS, NodeJS v0.10.40, npm -v 1.4.28, MongoDB 3.0

Following official instruction (http://docs.meteor.com/#/full/deploying) :

npm install
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data

> fibers@1.0.5 install /var/www/bundle/programs/server/node_modules/fibers
> node ./build.js

sh: node: command not found

npm ERR! fibers@1.0.5 install: `node ./build.js`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the fibers@1.0.5 install script.
npm ERR! This is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.10.0-229.el7.x86_64
npm ERR! command "/root/.nvm/v0.10.40/bin/node" "/root/.nvm/v0.10.40/bin/npm" "install"
npm ERR! cwd /var/www/bundle/programs/server
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

**Comment by sjmcdowall** [comment]
sh: node: command not found

This line is very suspicious -- are you sure you have node 0.10.40 in your path when you try this? i.e. if you just do 

node --version

is works?

**Comment by dmitrika** [comment]
> it works? 

Yep: node --version
v0.10.40

**Comment by sjmcdowall** [comment]
Ok -- that's odd!  Maybe try a "npm install --loglevel verbose" and see what the output is?

**Comment by dmitrika** [comment]
Thanks for reply.
I switched to use meteor-please from Kevin van Guldenaar hellstad
