### ISSUE TITLE
Cannot install Fibers 

### ISSUE THREAD

**Issue by icphoton** [laverdet/node-fibers#259]
Im having difficulty installing fibers via npm, the error is below. Any help is much appreciated!

C:\Users\Iain\Steambot>npm install fibers
> fibers@1.0.8 install C:\Users\Iain\Steambot\node_modules\fibers
> node build.js || nodejs build.js
C:\Users\Iain\Steambot\node_modules\fibers>if not defined npm_config_node_gyp (node "C:\Users\Iain\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )  else (node  rebuild --release )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: The build tools for v120 (Platform Toolset = 'v120') cannot be found. To build using the v120 build tools, please install v120 build tools.  Alternatively, you ma
y upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [C:\Users\Iain\Steambot\node_modules\fibers\build\fibers.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Iain\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Iain\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd C:\Users\Iain\Steambot\node_modules\fibers
gyp ERR! node -v v4.2.3
gyp ERR! node-gyp -v v3.2.0
gyp ERR! not ok
Build failed
'nodejs' is not recognized as an internal or external command,
operable program or batch file.
C:\Users\Iain\Steambot
├── make@0.0.0
├── mysql@2.9.0
├── node-gyp@3.2.1
├── rebuild@0.1.2
├── socket.io@1.3.7
├── steam-market-pricing@1.0.4
├── steam-tradeoffer-manager@1.13.0
├── steam-user@2.0.3
└── winston@2.1.1

npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Iain\Steambot\package.json'
npm WARN Steambot No description
npm WARN Steambot No repository field.
npm WARN Steambot No README data
npm WARN Steambot No license field.
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Iain\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "fibers"
npm ERR! node v4.2.3
npm ERR! npm  v3.5.1
npm ERR! code ELIFECYCLE

npm ERR! fibers@1.0.8 install: `node build.js || nodejs build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fibers@1.0.8 install script 'node build.js || nodejs build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js || nodejs build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fibers
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Iain\Steambot\npm-debug.log

**Comment by bisubus** [comment]
Probably related to #260.

**Comment by sjmcdowall** [comment]
Fibers only has certain pre-compiled binaries available for various node versions.  Node every version is pre-compiled.  The only way I figured out which versions are available was to actually download the github package and look at the bin (?) area to see which versions are pre-compiled for what platforms.  Otherwise, you do indeed need to have a VC command line build environment available for it to compile.

**Comment by gavinengel** [comment]
I may have a similar issue on my Ubuntu host:

```
npm ERR! fibers@0.6.9 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fibers@0.6.9 install script 'node ./build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fibers
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.

gavin:~/bin/node/lib$ npm -v
3.5.1
gavin:~/bin/node/lib$ node -v
v4.2.3

```

Does the above advice apply to my situation as well?

**Comment by laverdet** [comment]
1.0.9 should contain binaries for your system.
