### ISSUE TITLE
No precompiled Windows binaries on Node 4

### ISSUE THREAD

**Issue by bisubus** [laverdet/node-fibers#260]
I've found that installation fails on Node 4 (currently v4.2.3, both x86 and x64) on Windows because it tries to compile the binaries and fails if VC was not found.

But it installs fine on Node 5 (v5.1.1) with precompiled binaries, no dependency on VC.

npm v2.14.8 in both cases.

**Comment by christian-bromann** [comment]
@laverdet we just integrated fibers in webdriverio to make e2e tests easy to run. You did awesome work here! Unfortunately this package doesn't compile in Node v3 and v4 which is sad because v4 was released with a LTS.

What does it need to publish the binaries for v4? How can I help?

**Comment by laverdet** [comment]
4.x is supported in npm now.

**Comment by christian-bromann** [comment]
@laverdet you're killing it! Thanks so much!
