### ISSUE TITLE
Runtime Error - isolate_key != 0x7777

### ISSUE THREAD

**Issue by donaldhook** [laverdet/node-fibers#262]
I am running Node 4.23 on a Windows x64 machine and getting an error on startup. I have VS2015 installed as well.  Here is the error popup I get when starting my Node server.js

Assertion Failed
Program ...node_modules\fibers\bin\win32-x64-v8-4.5\fibers.node\file: ..\src\coroutine.cc
line 72

Expression: isolate_key != 0x7777

Any insight would be appreciated.

**Comment by laverdet** [comment]
Could you try applying this patch: https://github.com/meteor/node-fibers/commit/d519f0c5971c33d99c902dad346b817e84bab001

Recompiling and trying again?

**Comment by donaldhook** [comment]
That worked like a champ!!

Thank you for your quick response and help!!

**Comment by laverdet** [comment]
Could you do me a favor and do:

```
std::cout <<(void*)isolate_key <<"\n";
std::cout <<(void*)thread_data_key <<"\n"
std::cout <<(void*)thread_id_key <<"\n"
```

At the end of `find_thread_id_key` (couroutine.cc, line ~99) and tell me what that outputs when you load the extension? Would be helpful in fixing this for other users.

**Comment by donaldhook** [comment]
Marcel

ok, may not have worked, I did not remove the commented code to get around
the issue. In order to apply the patch what steps do I need to do?
I am using node from the command line  (npm install fibers --save
--msvs_version=2015).  So how to I unpack the code, make the change and
re-compile?

I need to do the same to put in the output statements you are requesting so
that I can provide you with the output

Thanks!!

**Comment by donaldhook** [comment]
I opened up the VS solution in the fibers folder under node_modules.  I
made the change per the patch, recompiled and it did not make any
difference.  When compiling, the build was looking for a
\Debug\node.lib.... that folder did not exist so I created the \Debug
folder and added the node.lib into it in order to get the project to
compile.....

I put in the 3 STD lines of code and received compile errors:

cout is not a member of std
cout is undeclared

Please let me know next steps to get past the issue.

Thanks!

**Comment by donaldhook** [comment]
Marcel

I had to copy the newly generated fibers.node file from the Release folder
to the fibers bin x32-64 folder .... the file I copied (that was built) was
1819KB, while the original file was around 200KB... thoughts?

Thanks

**Comment by laverdet** [comment]
Compile by running `node build.js` in the fibers folder (where binding.gyp is located). If it's complaining about cout not being defined you need to add #include <iostream> to the top of the file.

**Comment by donaldhook** [comment]
Ok, ran node.build.js and it ran fine.  I am still getting the error ....

C:\Boelter\BoelterIntegrationServer\node_modules\fibers>node build.js
`win32-ia32-v8-4.5` exists; testing
Binary is fine; exiting

C:\Boelter\BoelterIntegrationServer\node_modules\fibers>

**Comment by donaldhook** [comment]
I renamed the existing files so that it would force a build().... now I get
past the compilation error ...

**Comment by laverdet** [comment]
Try `node build.js -f` instead

**Comment by matt4446** [comment]
@laverdet I had the same problem (while getting nativescript cli to install/run)...
the meteor patch also worked for me 

Two reasons why @donaldhook could not compile...
1. coroutine.h needs: #include <iostream>
2. two missing semi colons in the debug statements. 

Here is a result from me at least: 
C:\Users\barmy\AppData\Roaming\npm\node_modules\fibers>node fibers.js
000000000000000F
0000000000000012
0000000000000011

Need any more help then im happy to. Reverting the lines back makes it fail still.

**Comment by rosen-vladimirov** [comment]
HI @laverdet ,
Sooo, is the patch required, should we add it in our fibers code? @matt4446  is using some of the packages that we are working on and I would like to provide a fix for him, so he will not have to manually rebuild fibers after every upgrade. What do you think - is it safe to use this patch in our fibers fork?

**Comment by matt4446** [comment]
@laverdet any further progress/updates? 

@rosen-vladimirov ... yes! Today is one of those days where i need to manually make that patch :)

**Comment by matt4446** [comment]
@laverdet  ... today's values are different though:
000000000000000D
000000000000000F
000000000000000E

**Comment by laverdet** [comment]
A similar patch is compiled in npm now. Please reopen if it doesn't work.
