### ISSUE TITLE
Process crash on 5.2

### ISSUE THREAD

**Issue by BobDickinson** [laverdet/node-fibers#263]
We are running into a bug where one of our processes crashes, and the stack trace indicates that maybe this is related to fibers (no user code of ours is in the trace).  The amount of code and the steps required to reproduce the crash don't provide me with a reproducible case to post here (I'll work on it, but I'm not optimistic).

If I had to guess, this code from fibers.cc seems to be where it goes bad:

	// Workaround for v8 issue #1180
	// http://code.google.com/p/v8/issues/detail?id=1180
	Script::Compile(uni::NewLatin1String(that.isolate, "void 0;"));

The failure comes as part of a unit test suite that we've been running on a regular basis for quite a while.  We noticed the failure on Node 5.2.0 (it does not repro on 4.0.0 or 4.2.1, but does repo on two different machines using 5.2.0 that did not fail with previous node versions and the same test suite).  

In our app, we have a main command router process that routes commands to child processes.  When we run our app in a mode where everything is on one process, the crash doesn't occur.  The unit test that precedes the crash causes our handler code running in a fiber to throw a custom Error (a user class extending Error) and catch it.  If we don't do that in our handler code, then the crash doesn't occur.  We have some other test cases that cause similar Error objects to be created/thrown/caught, and they don't trigger the crash.

I'm kind of scratching my head as to what my code could be doing to cause the sigtramp handling logic to go sideways, but I'm not coming up with anything.

Crash log attached.

[node_2015-12-14-190401_Blakes-MacBook-Pro .txt](https://github.com/laverdet/node-fibers/files/62053/node_2015-12-14-190401_Blakes-MacBook-Pro.txt)

**Comment by laverdet** [comment]
Indeed it might be a problem with fibers. Are you running node in debug mode [i.e. per this documentation](https://nodejs.org/api/debugger.html) or otherwise with another debugged attached?

**Comment by BobDickinson** [comment]
Yes, we are running in debug mode.  I just ran the test suite with debug off and it passed, then ran again with debug on and it failed per the description above.

The test suite that triggers the failure is an iOS client test suite hitting a test server.  We have 200+ tests in our server side test suite that run fine, but we're not running those tests in debug.  Let me see if I can make a server side test that fails, and if so, that might be something you can repro.

**Comment by BobDickinson** [comment]
OK, I was actually able to create a pretty isolated test case.

[FiberCrash.zip](https://github.com/laverdet/node-fibers/files/63863/FiberCrash.zip)

You have to run the attached Node app in debug mode.  You can trigger the crash by hitting the server twice with curl (reports as a segfault, crash dump stack traces look the same as what I posted before).

**Comment by BobDickinson** [comment]
And FWIW, I tried half a dozen different ways of subclassing Error (including util.inherits), and they all resulted in the crash.

**Comment by BobDickinson** [comment]
I have now seen this in a case where we were not subclassing Error.  We have a case where we exec the JS compiler via module._compile and a ReferenceError is thrown.  If we catch that error anywhere, even if we then do nothing with it, the process crashes in the same way (under debug only, same stack trace as previously reported).  That makes it seem less likely that we can work around this issue on our end.

**Comment by BobDickinson** [comment]
I guess it's also worth noting that the processing of the precondition (in any of the cases above) actually completes.  In the most recent case, the ReferenceError is thrown/caught, logged, sent back to the parent process, and then to the browser.  It is not until the next time we attempt to launch a fiber that we get the process crash.  We're using wait.for, and we see that we are calling `wait.launchFiber()`, but the process crashes before the function being run in the fiber is entered.

**Comment by laverdet** [comment]
If you change line 42 in binding.gyp from CORO_SJLJ to CORO_PTHREAD fibers will be stable while running in debug mode, at the cost of performance (or if not running on OS X, find the CORO_* definition for your platform). The real solution here is actually fairly hairy.

**Comment by BobDickinson** [comment]
We're big fans of fibers and have built a lot of our project around it (I prefer the fibers approach even to the forthcoming async/await).  Our project is a mobile app development platform (where the mobile app logic runs on the server side, under our node app).  We allow the dev to update and debug their app code live on the running server, meaning that running that node process in debug mode is a fairly normal use case that we need to support.

I'm wondering if the hairy solution is something that might be coming reasonably soon.  I'm also wondering why we're only seeing this now, and only on Mac.  Are we just getting "lucky" and seeing something that was there all along?

I could see a path where we run in development mode using PTHREAD (stable in debug mode, maybe slower, but don't really care in this usage) and in production mode using SJLJ (fast and stable when not in debug mode).  I don't see an easy way to make this switch at runtime, short of maybe building both versions and requiring the appropriate one.  Anyway, I think maybe a solution along these lines exists, but it's not smelling great to me right now.  Any guidance would be appreciated (either in the form of whether a fix is coming, or maybe recommending a way to support CORO switching that you like).

**Comment by laverdet** [comment]
Here is an idea.. Could you tell me if you still get the error if you comment out lines 144 - 146 in coroutine.cc, the `pthread_setspecific` calls.

**Comment by BobDickinson** [comment]
I tried that, but it didn't help.  I threw in some asserts (undefined NDEBUG so I could see them in release) and verified that that pthread code doesn't get hit in my failing test anyway.

**Comment by laverdet** [comment]
Ok I traced this back to node commit [a5094a35](https://github.com/nodejs/node/commit/a5094a35a0ef416bc95aafb530e92a5aa78ee239). It wasn't actually a problem with fibers at all.

I was unable to reproduce the crash on node 5.4.0. I compiled a fresh binary of node with and without that commit and confirmed that it does fix your case. It seems that this was broken some time between 5.0.0 and 5.2.0, though I didn't feel like finding the exact commit that broke it in the first place. Solution: upgrade to node 5.4.0 :)

Earlier in this thread I alluded to some fears that v8's debugging mode may reduce fiber's stability.. so I looked into that a little more closely as well and I don't think it'll actually cause any issues. Though you may run into a very tiny memory leak while running in debug mode with a large number of simultaneously waiting fibers (200+).

Thanks for the helpful repro case, it definitely made tracking this down a lot easier.
