### ISSUE TITLE
fibers install issue 

### ISSUE THREAD

**Issue by edwardsmarkf** [laverdet/node-fibers#265]
hello - sorry to bother you with this, but i wish to install a package which requires fibers and i cant seem to get it installed (below)

i am wondering if my gcc is too outdated. the git method didnt work for me either - same error

>> gcc -v  ;
Using built-in specs.
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.4.7 20120313 (Red Hat 4.4.7-16) (GCC)

>> uname -a ;
Linux edwardsmarkf[dot]info 2.6.32-573.7.1.el6.x86_64 #1 SMP Tue Sep 22 22:00:00 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

>>  npm  install fibers
|
> fibers@1.0.8 install /root/node_modules/fibers
> node build.js || nodejs build.js

(node) child_process: options.customFds option is deprecated. Use options.stdio instead.
make: Entering directory `/root/node_modules/fibers/build'
  CXX(target) Release/obj.target/fibers/src/fibers.o
In file included from /root/.node-gyp/4.2.3/src/node.h:42,
                 from ../src/coroutine.h:1,
                 from ../src/fibers.cc:1:
/root/.node-gyp/4.2.3/deps/v8/include/v8.h:336: error: expected unqualified-id before 'using'
/root/.node-gyp/4.2.3/deps/v8/include/v8.h: In constructor 'v8::MaybeLocal<T>::MaybeLocal()':
/root/.node-gyp/4.2.3/deps/v8/include/v8.h:353: error: 'nullptr' was not declared in this scope
/root/.node-gyp/4.2.3/deps/v8/include/v8.h: In member function 'bool v8::MaybeLocal<T>::IsEmpty() const':
/root/.node-gyp/4.2.3/deps/v8/include/v8.h:360: error: 'nullptr' was not declared in this scope
/root/.node-gyp/4.2.3/deps/v8/include/v8.h: In member function 'bool v8::MaybeLocal<T>::ToLocal(v8::Local<S>*) const':
/root/.node-gyp/4.2.3/deps/v8/include/v8.h:364: error: 'nullptr' was not declared in this scope
/root/.node-gyp/4.2.3/deps/v8/include/v8.h: In member function 'bool v8::WeakCallbackInfo<T>::IsFirstPass() const':
/root/.node-gyp/4.2.3/deps/v8/include/v8.h:430: error: 'nullptr' was not declared in this scope
/root/.node-gyp/4.2.3/deps/v8/include/v8.h: At global scope:
/root/.node-gyp/4.2.3/deps/v8/include/v8.h:469: error: expected unqualified-id before 'using'
/root/.node-gyp/4.2.3/deps/v8/include/v8.h: In constructor 'v8::Global<T>::Global()':
/root/.node-gyp/4.2.3/deps/v8/include/v8.h:790: error: 'nullptr' was not declared in this scope
/root/.node-gyp/4.2.3/deps/v8/include/v8.h: In constructor 'v8::Global<T>::Global(v8::Global<T>&&)':
/root/.node-gyp/4.2.3/deps/v8/include/v8.h:815: error: 'nullptr' was not declared in this scope
/root/.node-gyp/4.2.3/deps/v8/include/v8.h: In member function 'v8::Global<T>& v8::Global<T>::operator=(v8::Global<S>&&)':
/root/.node-gyp/4.2.3/deps/v8/include/v8.h:827: error: 'nullptr' was not declared in this scope
/root/.node-gyp/4.2.3/deps/v8/include/v8.h: At global scope:
/root/.node-gyp/4.2.3/deps/v8/include/v8.h:852: error: expected unqualified-id before 'using'
/root/.node-gyp/4.2.3/deps/v8/include/v8.h:1089: error: 'nullptr' was not declared in this scope
/root/.node-gyp/4.2.3/deps/v8/include/v8.h:1095: error: 'nullptr' was not declared in this scope
/root/.node-gyp/4.2.3/deps/v8/include/v8.h: In member function 'v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const':
/root/.node-gyp/4.2.3/deps/v8/include/v8.h:3205: error: 'nullptr' was not declared in this scope
/root/.node-gyp/4.2.3/deps/v8/include/v8.h: In member function 'v8::Local<T> v8::MaybeLocal<T>::ToLocalChecked()':
/root/.node-gyp/4.2.3/deps/v8/include/v8.h:7164: error: 'nullptr' was not declared in this scope
../src/fibers.cc: At global scope:
../src/fibers.cc:40: error: 'Handle' has not been declared
../src/fibers.cc:40: error: expected ',' or '...' before '<' token
../src/fibers.cc: In function 'void uni::Reset(v8::Isolate*, v8::Persistent<T, v8::NonCopyablePersistentTraits<T> >&, int)':
../src/fibers.cc:41: error: 'handle' was not declared in this scope
../src/fibers.cc: At global scope:
../src/fibers.cc:63: error: variable or field 'SetInternalPointer' declared void
../src/fibers.cc:63: error: 'Handle' was not declared in this scope
../src/fibers.cc:63: error: expected primary-expression before '>' token
../src/fibers.cc:63: error: 'handle' was not declared in this scope
../src/fibers.cc:63: error: expected primary-expression before 'int'
../src/fibers.cc:63: error: expected primary-expression before 'void'
../src/fibers.cc:67: error: template declaration of 'void* uni::GetInternalPointer'
../src/fibers.cc:67: error: 'Handle' was not declared in this scope
../src/fibers.cc:67: error: expected primary-expression before '>' token
../src/fibers.cc:67: error: 'handle' was not declared in this scope
../src/fibers.cc:67: error: expected primary-expression before 'int'
../src/fibers.cc:72: error: expected constructor, destructor, or type conversion before '<' token
../src/fibers.cc:77: error: variable or field 'Return' declared void
../src/fibers.cc:77: error: 'Handle' was not declared in this scope
../src/fibers.cc:77: error: expected primary-expression before '>' token
../src/fibers.cc:77: error: 'handle' was not declared in this scope
../src/fibers.cc:77: error: expected primary-expression before 'const'
../src/fibers.cc:81: error: variable or field 'Return' declared void
../src/fibers.cc:81: error: 'Handle' was not declared in this scope
../src/fibers.cc:81: error: expected primary-expression before '>' token
../src/fibers.cc:81: error: 'handle' was not declared in this scope
../src/fibers.cc:81: error: expected primary-expression before 'info'
../src/fibers.cc:89: error: expected constructor, destructor, or type conversion before '<' token
../src/fibers.cc:93: error: expected constructor, destructor, or type conversion before '<' token
../src/fibers.cc:97: error: expected constructor, destructor, or type conversion before '<' token
../src/fibers.cc:101: error: expected constructor, destructor, or type conversion before '<' token
../src/fibers.cc:105: error: expected constructor, destructor, or type conversion before '<' token
../src/fibers.cc:109: error: expected constructor, destructor, or type conversion before '<' token
../src/fibers.cc:113: error: expected constructor, destructor, or type conversion before '<' token
../src/fibers.cc:117: error: expected constructor, destructor, or type conversion before '<' token
../src/fibers.cc:127: error: expected constructor, destructor, or type conversion before '<' token
../src/fibers.cc:309: error: expected ';' before '(' token
../src/fibers.cc:315: error: expected ';' before 'Fiber'
../src/fibers.cc:315: error: expected ')' before '<' token
../src/fibers.cc:581: error: ISO C++ forbids declaration of 'Handle' with no type
../src/fibers.cc:581: error: expected ';' before '<' token
../src/fibers.cc:823: error: expected ';' at end of input
../src/fibers.cc:823: error: expected '}' at end of input
../src/fibers.cc: In static member function 'static void Fiber::DestroyOrphans()':
../src/fibers.cc:396: error: 'Deref' is not a member of 'uni'
../src/fibers.cc: In static member function 'static uni::FunctionType Fiber::New(const uni::Arguments&)':
../src/fibers.cc:418: error: 'ThrowException' is not a member of 'uni'
../src/fibers.cc:418: error: 'NewLatin1String' is not a member of 'uni'
../src/fibers.cc:418: error: return-statement with a value, in function returning 'void'
../src/fibers.cc:420: error: 'ThrowException' is not a member of 'uni'
../src/fibers.cc:420: error: 'NewLatin1String' is not a member of 'uni'
../src/fibers.cc:420: error: return-statement with a value, in function returning 'void'
../src/fibers.cc:422: error: 'Handle' was not declared in this scope
../src/fibers.cc:422: error: expected primary-expression before '>' token
../src/fibers.cc:422: error: 'argv' was not declared in this scope
../src/fibers.cc:423: error: 'Deref' is not a member of 'uni'
../src/fibers.cc:423: error: return-statement with a value, in function returning 'void'
../src/fibers.cc:426: error: 'Handle' was not declared in this scope
../src/fibers.cc:426: error: expected primary-expression before '>' token
../src/fibers.cc:426: error: 'fn' was not declared in this scope
../src/fibers.cc:426: error: expected primary-expression before '>' token
../src/fibers.cc:426: error: '::Cast' has not been declared
../src/fibers.cc:427: error: 'GetCurrentContext' is not a member of 'uni'
../src/fibers.cc:428: error: no matching function for call to 'Return(v8::Local<v8::Object>, const v8::FunctionCallbackInfo<v8::Value>&)'
../src/fibers.cc:428: error: return-statement with a value, in function returning 'void'
../src/fibers.cc: In static member function 'static uni::FunctionType Fiber::Run(const uni::Arguments&)':
../src/fibers.cc:436: error: 'Unwrap' was not declared in this scope
../src/fibers.cc:442: error: 'ThrowException' is not a member of 'uni'
../src/fibers.cc:442: error: 'NewLatin1String' is not a member of 'uni'
../src/fibers.cc:442: error: return-statement with a value, in function returning 'void'
../src/fibers.cc:444: error: 'ThrowException' is not a member of 'uni'
../src/fibers.cc:444: error: 'NewLatin1String' is not a member of 'uni'
../src/fibers.cc:444: error: return-statement with a value, in function returning 'void'
../src/fibers.cc:452: error: 'RunFiber' was not declared in this scope
../src/fibers.cc:455: error: 'ThrowException' is not a member of 'uni'
../src/fibers.cc:455: error: 'NewLatin1String' is not a member of 'uni'
../src/fibers.cc:455: error: return-statement with a value, in function returning 'void'
../src/fibers.cc:465: error: no matching function for call to 'Reset(v8::Isolate*&, v8::Persistent<v8::Value, v8::NonCopyablePersistentTraits<v8::Value> >&, v8::Local<v8::Value>)'
../src/fibers.cc:467: error: 'Undefined' is not a member of 'uni'
../src/fibers.cc:471: error: 'class Fiber' has no member named 'ReturnYielded'
../src/fibers.cc:471: error: return-statement with a value, in function returning 'void'
../src/fibers.cc: In static member function 'static uni::FunctionType Fiber::ThrowInto(const uni::Arguments&)':
../src/fibers.cc:478: error: 'Unwrap' was not declared in this scope
../src/fibers.cc:481: error: 'ThrowException' is not a member of 'uni'
../src/fibers.cc:481: error: 'NewLatin1String' is not a member of 'uni'
../src/fibers.cc:481: error: return-statement with a value, in function returning 'void'
../src/fibers.cc:483: error: 'Undefined' is not a member of 'uni'
../src/fibers.cc:485: error: no matching function for call to 'Reset(v8::Isolate*&, v8::Persistent<v8::Value, v8::NonCopyablePersistentTraits<v8::Value> >&, v8::Local<v8::Value>)'
../src/fibers.cc:487: error: 'ThrowException' is not a member of 'uni'
../src/fibers.cc:487: error: 'NewLatin1String' is not a member of 'uni'
../src/fibers.cc:487: error: return-statement with a value, in function returning 'void'
../src/fibers.cc:491: error: 'class Fiber' has no member named 'ReturnYielded'
../src/fibers.cc:491: error: return-statement with a value, in function returning 'void'
../src/fibers.cc: In static member function 'static uni::FunctionType Fiber::Reset(const uni::Arguments&)':
../src/fibers.cc:499: error: 'Unwrap' was not declared in this scope
../src/fibers.cc:502: error: 'Undefined' is not a member of 'uni'
../src/fibers.cc:502: error: return-statement with a value, in function returning 'void'
../src/fibers.cc:504: error: 'ThrowException' is not a member of 'uni'
../src/fibers.cc:504: error: 'NewLatin1String' is not a member of 'uni'
../src/fibers.cc:504: error: return-statement with a value, in function returning 'void'
../src/fibers.cc:506: error: 'ThrowException' is not a member of 'uni'
../src/fibers.cc:506: error: 'NewLatin1String' is not a member of 'uni'
../src/fibers.cc:506: error: return-statement with a value, in function returning 'void'
../src/fibers.cc:514: error: 'Handle' was not declared in this scope
../src/fibers.cc:514: error: expected primary-expression before '>' token
../src/fibers.cc:514: error: 'val' was not declared in this scope
../src/fibers.cc:514: error: 'Deref' is not a member of 'uni'
../src/fibers.cc:517: error: 'ThrowException' is not a member of 'uni'
../src/fibers.cc:517: error: return-statement with a value, in function returning 'void'
../src/fibers.cc:519: error: return-statement with a value, in function returning 'void'
../src/fibers.cc: In member function 'void Fiber::UnwindStack()':
../src/fibers.cc:536: error: 'Handle' was not declared in this scope
../src/fibers.cc:536: error: expected primary-expression before '>' token
../src/fibers.cc:536: error: 'NewLatin1String' is not a member of 'uni'
../src/fibers.cc:537: error: no matching function for call to 'Reset(v8::Isolate*&, v8::Persistent<v8::Value, v8::NonCopyablePersistentTraits<v8::Value> >&, v8::Persistent<v8::Value, v8::NonCopyablePersistentTraits<v8::Value> >&)'
../src/fibers.cc:538: error: no matching function for call to 'Reset(v8::Isolate*&, v8::Persistent<v8::Value, v8::NonCopyablePersistentTraits<v8::Value> >&, v8::Persistent<v8::Value, v8::NonCopyablePersistentTraits<v8::Value> >&)'
../src/fibers.cc:551: error: 'Undefined' is not a member of 'uni'
../src/fibers.cc: At global scope:
../src/fibers.cc:576: error: expected unqualified-id at end of input
make: *** [Release/obj.target/fibers/src/fibers.o] Error 1
make: Leaving directory `/root/node_modules/fibers/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 2.6.32-573.7.1.el6.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /root/node_modules/fibers
gyp ERR! node -v v4.2.3
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
Build failed
sh: nodejs: command not found
npm ERR! Linux 2.6.32-573.7.1.el6.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "fibers"
npm ERR! node v4.2.3
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! fibers@1.0.8 install: `node build.js || nodejs build.js`
npm ERR! Exit status 127
npm ERR!
npm ERR! Failed at the fibers@1.0.8 install script 'node build.js || nodejs build.js'.
npm ERR! This is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js || nodejs build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log
You have mail in /var/spool/mail/root
[root@edwardsmarkf ~]#    npm owner ls fibers
laverdet <marcel.npm@laverdet.com>

**Comment by laverdet** [comment]
There are some tips for fixing your build environment on #248. Specifically you may want to check out [this comment](https://github.com/laverdet/node-fibers/issues/248#issuecomment-146316386). The issue could be an old version of gcc or something related to nvm. Alternatively if you use node v5 you won't have this issue.
