### ISSUE TITLE
Errors when trying to install node fibers

### ISSUE THREAD

**Issue by ilapko** [laverdet/node-fibers#266]
I'm trying to install node fibers for use with my Meteor app on a Windows server that does not have an internet connection. I've manually copied the fibers files from github to the `programs/server/node_modules/fibers` directory as per the package readme. I'm now trying to run `npm install --verbose` from that directory. I'm receiving the following error:

    gyp verb get node dir no --target version specified, falling back to host node version: v0.10.40
    gyp verb command install [ 'v0.10.40' ]
    gyp verb install input version string "v0.10.40"
    gyp verb install installing version: 0.10.40
    gyp verb install --ensure was passed, so won't reinstall if already installed
    gyp verb install version not already installed, continuing with install 0.10.40
    gyp verb ensuring nodedir is created C:\Users\xilapko\.node-gyp\0.10.40
    gyp verb created nodedir C:\Users\xilapko\.node-gyp\0.10.40
    gyp http GET http://nodejs.org/dist/v0.10.40/node-v0.10.40.tar.gz
    gyp http 503 http://nodejs.org/dist/v0.10.40/node-v0.10.40.tar.gz
    gyp WARN install got an error, rolling back install
    gyp verb command remove [ '0.10.40' ]
    gyp verb remove using node-gyp dir: C:\Users\xilapko\.node-gyp
    gyp verb remove removing target version: 0.10.40
    gyp verb remove removing development files for version: 0.10.40
    gyp ERR! configure error
    gyp ERR! stack Error: 503 status code downloading tarball
    gyp ERR! stack     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\nod
    e-gyp\lib\install.js:246:14)
    gyp ERR! stack     at Request.emit (events.js:117:20)
    gyp ERR! stack     at Request.onResponse (C:\Program Files\nodejs\node_modules\npm\node_modules\requ
    est\request.js:1085:10)
    gyp ERR! stack     at ClientRequest.g (events.js:180:16)
    gyp ERR! stack     at ClientRequest.emit (events.js:95:17)
    gyp ERR! stack     at HTTPParser.parserOnIncomingClient (http.js:1689:21)
    gyp ERR! stack     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)
    gyp ERR! stack     at Socket.socketOnData (http.js:1584:20)
    gyp ERR! stack     at TCP.onread (net.js:528:27)
    gyp ERR! System Windows_NT 6.1.7601
    gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\
    node-gyp.js" "rebuild" "--release"

Note that I already have node v0.10.40 installed on the server (`node -v` confirms this) so I don't understand why it's trying to download this version again from the internet.

**Comment by sjmcdowall** [comment]
Meteor actually has it's OWN copy/build of fibers that is somewhat independent of the main Fibers build. Make sure you use that version (which is pulled from the meteor github repo, not fibers) . However, and alas, at least last I checked they don't provide a nice Windows V0.10.40 build version already :( 

So -- the question is -- what exactly are you trying to do?  If you are trying to deploy to Windows -- have you looked / tried demeteorizer?  Not going to help though on the lack of internet connection... that's going to be a royal pain to solve I think. ;(

**Comment by ilapko** [comment]
The issue started from me needing to downgrade Node on the server from v0.12.x to v0.10.40 because I upgraded Meteor from v1.0 to v1.2, which isn't compatible with Node v0.12.x. After downgrading Node on the server, I started encountering issues with fibers version incompatibility. Node seems to want fibers version win32-x64-v8-3.14 but my Meteor bundle contains version win32-x64-v8-3.28. It's already been a real pain, but I'm not sure which direction I should go in now...

**Comment by ilapko** [comment]
Also, this Meteor-only build of fibers...how do I get it included in my bundle?

**Comment by laverdet** [comment]
To be honest I have no idea. You'll probably want to open this up on meteor, or better yet just reinstall meteor using the instructions on their website. Failing that, fibers does compile just fine on Windows if you follow the instructions for setting up a build environment via https://github.com/nodejs/node-gyp
