### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by rw08clan** [laverdet/node-fibers#268]
Having issues installing fibers :

$ npm install fibers
npm WARN package.json appx-test@1.0.0 No repository field.

> fibers@1.0.9 install C:\code\gtnexus\platform\test\node_modules\fibers
> node build.js || nodejs build.js

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"  "fibers"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! file n
npm ERR! path n
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn n

npm ERR! fibers@1.0.9 install: `node build.js || nodejs build.js`
npm ERR! spawn n ENOENT
npm ERR!
npm ERR! Failed at the fibers@1.0.9 install script 'node build.js || nodejs build.js'.
npm ERR! This is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js || nodejs build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.

.....

I can link the npm-debug.log if that helps as well

node: 4.3.1
npm: 2.14.12
Windows 8

Thank you

**Comment by sjmcdowall** [comment]
My GUESS -- is that fiber's 1.0.9 isn't pre-compiled for Node 4.3.1 on Windows.  Soooo -- you will have to setup a full C++ command line build environment (from VS Studio 2012 for example) and compile fibers (npm install fibers will try to do this for you).  Maybe the nom-debug.log will help insure that my guess is correct, but it's a pretty good one. :)

**Comment by laverdet** [comment]
Could you attached the debug log? That error message isn't very helpful

**Comment by rw08clan** [comment]
[npm-debug.txt](https://github.com/laverdet/node-fibers/files/146552/npm-debug.txt)

Thank you

**Comment by jbonigomes** [comment]
I'm having the same problem, on Ubuntu 14.04.4 x64, node v5.6.0 and npm version 3.7.5, my npm debug log can be found here [here](https://github.com/laverdet/node-fibers/files/150933/npm-debug.log.zip).

**Comment by sjmcdowall** [comment]
You are doing a Meteor install type thing @jbonigomes .  Meteor only supports node 0.10.40 .

**Comment by jbonigomes** [comment]
Thanks @sjmcdowall but I am having a new problem (node v0.10.40 and npm version 1.4.28)

**My application is throwing this error:**

/var/www/futurefirst/bundle/programs/server/node_modules/fibers/fibers.js:16
	throw new Error('`'+ modPath+ '.node` is missing. Try reinstalling `node-fibers`?');
	^

Error: `/var/www/futurefirst/bundle/programs/server/node_modules/fibers/bin/linux-x64-v8-4.6/fibers.node` is missing. Try reinstalling `node-fibers`?
    at Object.<anonymous> (/var/www/futurefirst/bundle/programs/server/node_modules/fibers/fibers.js:16:8)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/var/www/futurefirst/bundle/programs/server/boot.js:1:75)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)




**The message when running npm install changed slightly and it no longer produces an error log file:**

npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
|
> fibers@1.0.5 install /var/www/futurefirst/bundle/programs/server/node_modules/fibers
> node ./build.js

`linux-x64-v8-3.14` exists; testing
Binary is fine; exiting
ansi-regex@0.2.1 node_modules/ansi-regex

ansi-styles@1.1.0 node_modules/ansi-styles

escape-string-regexp@1.0.3 node_modules/escape-string-regexp

has-ansi@0.1.0 node_modules/has-ansi

strip-ansi@0.3.0 node_modules/strip-ansi

supports-color@0.2.0 node_modules/supports-color

type-of@2.0.1 node_modules/type-of

amdefine@1.0.0 node_modules/amdefine

asap@2.0.3 node_modules/asap

underscore@1.5.2 node_modules/underscore

meteor-promise@0.5.0 node_modules/meteor-promise

promise@7.0.4 node_modules/promise

source-map-support@0.3.2 node_modules/source-map-support

semver@4.1.0 node_modules/semver

source-map@0.1.32 node_modules/source-map

fibers@1.0.5 node_modules/fibers

**Comment by laverdet** [comment]
I recommend refollowing the meteor installation instructions from start to finish; this is not a problem w/ fibers. Meteor is running on an ancient version of node with a custom build of fibers. I am unable to provide support for you here.

Also your bug is unrelated to the original ticket which I suspect is a windows only issue.

**Comment by jbonigomes** [comment]
thanks @laverdet, I will re-build my server from scratch

**Comment by jbonigomes** [comment]
if the problem persists, where do you recommend I should go to seek for help? Meteor?

**Comment by laverdet** [comment]
Yeah this is an issue with meteor. Check their closed tickets on github, support docs, and whatnot. I've never actually used meteor so I don't have any specific guidance but yours is a fairly common issue.

**Comment by jbonigomes** [comment]
Thanks

**Comment by sjmcdowall** [comment]
BTW -- if this has anything to do with Windows and Meteor, I wrote a pretty good (IMHO) guide on how to deploy Windows guide on the Meteor Forums : 

[](https://forums.meteor.com/t/one-deployment-method-for-a-meteor-application-on-windows/13928)

But the Meteor Forums area should be the place to check

**Comment by jjdonov** [comment]
Can we return to @rw08clan 's original issue? From reading his npm debug, I'm not sure if this is caused by a missing C++ build environment or not.

**Comment by laverdet** [comment]
He shouldn't need a build environment running node 4.x or 5.x, binaries are included. I suspect there's something wrong with his node installation, to be honest.

@rw08clan could you do the following:
- Download the release directly http://registry.npmjs.org/fibers/-/fibers-1.0.10.tgz
- Extract it, there should be one directory named `package`
- cd package
- node build

Paste that output here.

**Comment by rw08clan** [comment]
@laverdet 

$ node build
`win32-x64-v8-4.6` exists; testing
Binary is fine; exiting

Thank you for taking a look at this

**Comment by laverdet** [comment]
Yeah, so the binaries are fine on your system. The "Binary is fine; exiting" check means your system is good to go. If you actually just rename that `package` folder to `fibers` and then move it into your `node_modules` folder everything will work.

Looking at your npm log the line that looks most suspicious is this:
```
stack spawn n ENOENT
```

I suspect you did some kind of weird aliasing thing where "n" is supposed to run "node" -- I have no idea. So I think this is some weird configuration issue with your system. Check your environment variables and aliases to make sure everything is clean.
