### ISSUE TITLE
fibers.node is missing... What did I miss?

### ISSUE THREAD

**Issue by RenaudParis** [laverdet/node-fibers#271]
Hi,

I get this error:

    node_modules\fibers\bin\win32-x64-v8-4.8\fibers.node` is missing

When I check the folder, I only have a "win32-x64-v8-4.6" folder.

What did I miss?

**Comment by sjmcdowall** [comment]
The bin version you need is totally dependent on the node version you are running.  Alas, I don't remember which goes with which, but what node version are you running? Do a node --version and see what one? Somewhere is probably buried a V8 line that says 4.8.  If the only version you have is V8-4.6 you need to find the appropriate node version that has that V8 engine I think.

**Comment by RenaudParis** [comment]
I am trying to use this module with NW.js.

NW.js is version 0.13.0-beta5 using Node v5.4.1 and Chromium 48

Maybe I can download the V8-4.8 version somewhere? Surely I am not the only Windows user out there (at least I hope so :) )

**Comment by sjmcdowall** [comment]
You may find one of the various "nvm" programs for windows helpful -- it basically is a front end and lets you "switch" node versions around fairly easily.  You aren't the ONLY Windows user for fibers, I use it a lot but I use it within the context of Meteor which is on node 0.10.40 :)  

You just need to find an appropriate node version that matches a supported windows / fibers version to make your life much easier.  Fibers doesn't get compiled for various Windows versions as fast/much as it does for Linux .. <shrug> 

Or -- compile it your self -- which is NOT a lot of fun. LOL

**Comment by RenaudParis** [comment]
Mmmh I would like to avoid compiling it myself if possible :) haha I'm not sure I would even succeed...

Otherwise I would have to downgrade nw.js then... Which is not cool, because it's not yet in stable release, and I would probably lose precious bugfixes and improvements.

Or I could... Well I don't know, focus on another part of my app that doesn't require synchronous calls, while praying that version V8-4.8 would be compiled soon! :)

Node and its asynchronous behavior, what an unnecessary pain in the foot, I swear...

**Comment by sjmcdowall** [comment]
Why not use a standard nodejs deploy instead of nw.js ?  Have you looked at any Windows nvm packages to manipulate your node version?  It maybe helpful .. ??

**Comment by RenaudParis** [comment]
I don't understand your question :) How am I to create a portable (Windows/Mac/Linux) desktop application using NW.js if I don't use NW.js? Is there another way using pure node?

**Comment by laverdet** [comment]
Use node 4.x or follow the instructions on https://github.com/nodejs/node-gyp to setup a windows build environment and compile it (this isn't as hard as it sounds)

**Comment by RenaudParis** [comment]
I tried with nw.js v0.12.3, and it apparently uses V8-3.32... The other extreme... I'll have a look at node-gyp, but if you already have a working compilation setup, would it take you a lot of time to compile again with V8-4.8? (or every major version used by nw.js)

If so, then I guess I'll have to try to pull my hair with it :) But I find it a bit redundant that each user should recompile something that should not need to :( Surely there is a way around that

**Comment by laverdet** [comment]
You're using a custom build of node, this is not supported out of the box. I'm already supporting 12 different binary releases, I really can't be bothered to add another release for something non-mainstream :\

You can build fibers yourself, it's really not difficult at all. You have to install 3 things and they're all free downloads.

**Comment by bjouhier** [comment]
Also fibers is just one of many binary add-ons. Most other binary add-ons don't provide pre-compiled binaries, they assume that the developer has the tools to build.
