### ISSUE TITLE
The system cannot find message text for message number

### ISSUE THREAD

**Issue by RenaudParis** [laverdet/node-fibers#272]
I compiled the module for the latest nw.js version, and when I restarted the app, I got:

    [module.js:476] Uncaught Error: The system cannot find message text for message number 0x%1 in the message file for %2.
    \\?\D:\dev\NW.js\Projects\TestProject\node_modules\fibers\bin\win32-x64-v8-4.9\fibers.node

I compiled several times, using these commands:

    node-gyp rebuild
    node-gyp rebuild --target=5.3.0 --arch=x64 --dist-url=https://atom.io/download/atom-shell

But no luck... However, the generated fibers.node file seems to be the adequate weight (192ko). I tried to search the internet (hence the compilation flags I added with a bit of hope in my eyes), but still no luck.

During compilation, I have a few warnings, but no errors. It compiles using "C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe"

Could it be due to the fact that it compiles using Node 5.3.0 (the node version installed on my system) whereas nw.js v0.13.0 RC1 uses Node 5.7.0? If so, should I reinstall Node 5.7.0, or is there a smart way around it? I tried to change the --target flag and put 5.7.0, but it did not work (error 403 while retrieving the file "https://atom.io/download/atom-shell/v5.7.0/node-v5.7.0-headers.tar.gz")

Any idea, Windows users?

**Comment by laverdet** [comment]
Can you try the instructions here--
https://github.com/nwjs/nw.js/wiki/build-native-modules-with-nw-gyp

**Comment by RenaudParis** [comment]
Thank you for the link, I'll try that!
