### ISSUE TITLE
MIPS architecture not supported

### ISSUE THREAD

**Issue by tomasinouk** [laverdet/node-fibers#275]
Hi, I am trying to build on `mips` architecture `MT7688` exactly aka LinkIT Smart. 

I get the error of not supported architecture `Unsupported (?) architecture: 'mipsel'`

Is there a way, that I would be able to build it?
Thank you

```
root@mylinkit:/tmp/usr/node-fibers# npm install --unsafe-perm

> fibers@1.0.10 install /tmp/usr/node-fibers
> node build.js || nodejs build.js

Unsupported (?) architecture: `mipsel`
Unsupported (?) architecture: `mipsel`

npm ERR! Linux 3.18.21
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "--unsafe-perm"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! fibers@1.0.10 install: `node build.js || nodejs build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fibers@1.0.10 install script 'node build.js || nodejs build.js'.
npm ERR! This is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js || nodejs build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/usr/node-fibers/npm-debug.log
root@mylinkit:/tmp/usr/node-fibers# node build -f
Unsupported (?) architecture: `mipsel`
```

**Comment by laverdet** [comment]
Yeah I think you're the first person to ask for MIPS support. You'll have to modify `binding.gyp` and follow the instructions on the readme under "from source". Feel free to submit a pull request if you get it working~

**Comment by roychiang** [comment]
try this, probably works.

diff --git a/binding.gyp b/binding.gyp
index 42fb17d..3f03716 100644
--- a/binding.gyp
+++ b/binding.gyp
@@ -48,6 +48,14 @@
                                                'defines!': ['CORO_UCONTEXT', 'CORO_SJLJ', 'CORO_ASM'],
                                        },
                                ],
+                               ['target_arch == "mipsel"',
+                                       {
+                                               # There's been problems getting real fibers working on mipsel
+                                               'defines': ['CORO_PTHREAD'],
+                                               'defines!': ['CORO_UCONTEXT', 'CORO_SJLJ', 'CORO_ASM'],
+                                       },
+                               ],    
                        ],

**Comment by tomasinouk** [comment]
Will do and report back
