### ISSUE TITLE
Fibers install failure Win7, Node 5.1.0

### ISSUE THREAD

**Issue by davewallace** [laverdet/node-fibers#280]
No log file generated, but console output was: https://gist.github.com/davewallace/baa09ff1d8f97ab8dac334f6185d76c6

**Comment by davewallace** [comment]
When I `npm install fibers` on Win7, Node 5.1.0, it prints this out:

>
$ npm install fibers

> fibers@1.0.10 install c:\wamp\www\codefinger-projects\chromos\node_modules\fibers
> node build.js || nodejs build.js

`win32-x64-v8-4.6` exists; testing
Binary is fine; exiting
chromos@0.0.1 c:\wamp\www\codefinger-projects\chromos
`-- fibers@1.0.10  extraneous

**Comment by sjmcdowall** [comment]
This is obviously an issue with your use of Meteor -- which version?  Meteor has it's own (as you found out) version of Fibers AND Nodejs it uses.  Well you may not know about the NodeJS part -- but meteor bundles it's own set of libraries, etc.  In Meteor 1.2 it was node 0.10.40 and fibers 1.0.5 but a modified one that THEY bundled in ... 

I am not sure in Meteor 1.3 (I'm a 1.2 guy) -- but doing an npm install meteor wasn't supported for Windows and you had to uses the Windows installer ... 

https://www.meteor.com/install

Uses the Windows installer and see how that goes perhaps?

**Comment by davewallace** [comment]
Thanks @sjmcdowall you were right, it was the NodeJS version I missed, I'd tried on a handful of different Node and Fibers version combos to no avail.

The I bounced onto a different issue's answer, noting available binaries - hence I came upon your solution that way. Thanks for your reply, though.
