### ISSUE TITLE
Alpine linux compatibility (musl libc)

### ISSUE THREAD

**Issue by ricoli** [laverdet/node-fibers#285]
Any chance for fibers to become compatible with musl libc? At the moment it relies on symbols that are only present on glibc :(

**Comment by laverdet** [comment]
Can you try this PR: https://github.com/laverdet/node-fibers/pull/269

**Comment by ricoli** [comment]
Just noticed that PR :) Will give it a go

**Comment by ricoli** [comment]
I'm getting ```Assertion failed: isolate_key != 0x7777 (../src/coroutine.cc: find_thread_id_key: 72)```

**Comment by laverdet** [comment]
Can you please check this branch and tell me if it works for you: https://github.com/laverdet/node-fibers/tree/musl

**Comment by laverdet** [comment]
Build commands:

```
git clone https://github.com/laverdet/node-fibers.git
cd node-fibers
git checkout musl
node build
```

The last command may ask you to install some extra stuff for compilation. If so do what it says and rerun it.

**Comment by ricoli** [comment]
Yeah I think that's it - I don't get any messages about symbols not isolate keys from what I could see.

**Comment by laverdet** [comment]
This is in npm now, you should be able to install fibers now with just `npm install fibers`.

**Comment by ricoli** [comment]
Great stuff, thank you very much!
