### ISSUE TITLE
broken package - fibers - prevents installation of Rocket.Chat

### ISSUE THREAD

**Issue by iamrudra** [laverdet/node-fibers#287]
OS - Ubuntu 14.04 LTS

`npm install`

>npm ERR! fibers@1.0.5 install: node ./build.js
>npm ERR! Exit status 1
>npm ERR! 
>npm ERR! Failed at the fibers@1.0.5 install script 'node ./build.js'.
>npm ERR! This is most likely a problem with the fibers package,
>npm ERR! not with npm itself.

**Comment by laverdet** [comment]
Current version of fibers is 1.0.12.
