### ISSUE TITLE
Having a little issue with fiber

### ISSUE THREAD

**Issue by Hyennes** [laverdet/node-fibers#289]
Currently I'm using fiber to iterate over an array and do a 5 secs delay every 40 items.
At the end of it, I recursively call the same function again so it repeats over. But something is wrong with my code, the code just doesn't start att all.
The first time it runs perfectly, but the second time it simply doesn't do anything.

This is what I have:

```
function recursiveCall(){
    Fiber(function() {
        for (var ii = inc.run(0); ii < array.length; ii = inc.run(1)) {
            console.log(ii);

            if(ii % 39 == 0 && ii > 0){
                sleep(5000);
                count = 0;
            }
            else{ count++; }

            if(ii==(array.length-1)){
                setTimeout(function(){
                    recursiveCall();
                }, 5000);
            }
        }
    }).run();
}

function sleep(ms) {
    var fiber = Fiber.current;
    setTimeout(function() {
        fiber.run();
    }, ms);
    Fiber.yield();
}

var inc = Fiber(function(start) {
    var total = start;
    while (true) {
        total += Fiber.yield(total);
    }
});
```

By the way, I took the sleep function and the iteration method from the fiber docs on github.

**Comment by laverdet** [comment]
The code doesn't start because you never actually call inc.run().
