### ISSUE TITLE
TypeError: Fiber is not a function

### ISSUE THREAD

**Issue by 7-paulwong** [laverdet/node-fibers#290]
console.log(Fiber);
{ yield: [Function],
  Fiber: 
   { [Function: Fiber]
     yield: [Function],
     current: undefined,
     poolSize: 120,
     fibersCreated: 0 } }

But when run test/started.js or any script got Error
TypeError: Fiber is not a function

**Comment by laverdet** [comment]
The test scripts are meant to be started with `node test.js`. You also have to require the module before you use it, please see the examples in the readme.
