### ISSUE TITLE
Not supporting 5.1 v8 versions

### ISSUE THREAD

**Issue by arthursfreire** [laverdet/node-fibers#291]
When installing via "npm install" and requiring it as "var fiber = require('fibers')", I get the following error:
.../node_modules/fibers/bin/linux-x64-v8-5.1/fibers.node` is missing. Try reinstalling `node-fibers`?

My current node version is 6.2.1.

**Comment by laverdet** [comment]
node 6.2.1 uses v8 5.0.72, not 5.1.

**Comment by arthursfreire** [comment]
Hi again,

By typing "console.log(process.versions") on the terminal I get the following output:
{ http_parser: '2.7.0',
  node: '6.2.1',
  v8: '5.0.71.52',
  uv: '1.9.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '57.1',
  modules: '48',
  openssl: '1.0.2h' }

However, by running my application, I get this:
{ "http_parser":"2.7.0",
"node":"6.1.0",
"v8":"5.1.281.59",
"uv":"1.9.0",
"zlib":"1.2.8",
"ares":"1.10.1-DEV",
"modules":"48",
"openssl":"1.0.2h",
"electron":"1.2.2",
"atom-shell":"1.2.2",
"chrome":"51.0.2704.84" }

Do you have any idea why is it happening or how can get rid of this?
Thanks in advance.

**Comment by arthursfreire** [comment]
By the way, the app I'm using [Electron](http://electron.atom.io/) to write my app, and I believe that it's related to the fact that I run my app using Electron instead of node. Sorry for bothering.

**Comment by laverdet** [comment]
You'll need to build the binary yourself--
http://stackoverflow.com/questions/31215400/nodejs-sync-cannot-find-fibers-binaries

**Comment by arthursfreire** [comment]
Thanks!

**Comment by dimatter** [comment]
```javascript
{ http_parser: '2.7.0',
  node: '6.5.0',
  v8: '5.3.332.45',
  uv: '1.9.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  modules: '50',
  openssl: '1.0.2h',
  electron: '1.4.2',
  chrome: '53.0.2785.113',
  'atom-shell': '1.4.2' }
```

```
