### ISSUE TITLE
Do not extend Funtion.prototype by future() method.

### ISSUE THREAD

**Issue by nin-jin** [laverdet/node-fibers#297]
This is bad practice.

**Comment by sjmcdowall** [comment]
Would you care to expand and explain this rationale for a module that has been around for years?  And, if you think its "bad practice" -- what would you suggest as to how to change this and not break any backward functionality?

**Comment by nin-jin** [comment]
This functional can be replaced by Future.wrap.

You can increase major version because it is breaking changes.

**Comment by laverdet** [comment]
I probably wouldn't have made the same design choice today as I did in 2011, but you're crazy if you think I'm going to remove a five-year-old utility method used in 1000's of places for functional style points.

**Comment by nin-jin** [comment]
Many developers don't want to use this extensions because it has this "feature".

You can separate 'fibers/future' to 'fibers/future-next' and `fibers/function-ext`, and remain 'fibers/future' as alias for load all of them.
