### ISSUE TITLE
Add thenable interface to Future

### ISSUE THREAD

**Issue by nin-jin** [laverdet/node-fibers#298]
`Future.prototype.resolve` and `Future.prototype.promise` are not user friendly. Futures can support thenable interface which is better and compatible with standarts. https://promisesaplus.com/

**Comment by nin-jin** [comment]
```
Future.task( app ).resolve( error => {
    if( !error ) return
    console.erro( error )
})
```
||
\/
```
Future.task( app ).catch( error => {
    console.error( error )
})
```

**Comment by laverdet** [comment]
You mentioned `Future.prototype.promise`, but I think the ES6 promise interface meets all your criteria. Please see the docs [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise).

For instance with futures + promises you could do:
```js
future.promise().then(function(val) {
  console.log('received', val);
})
.catch(function(err) {
  console.error('error', err);
});
```

**Comment by nin-jin** [comment]
I do not want promises, i want to use future as promise (they are the same abstraction with diffenet names).
