### ISSUE TITLE
Issue when counting values with +=

### ISSUE THREAD

**Issue by mitar** [laverdet/node-fibers#303]
The following program:

```javascript
var Fiber = require('fibers');
var Future = require('fibers/future');

var one = function () {
  var future = new Future();
  setTimeout(function () {
    future.return(1);  
  }, 1000);
  return future.wait();
}

Fiber(function () {
  var i;
  var count = 0;
  var futures = [];
  console.log("start buggy");
  for (i = 0; i < 10; i++) {
    futures.push(Future.task(function () {
      count += one();
      console.log("count", count);
    }));
  }
  while (futures.length) {
    futures.pop().wait();
  }
  console.log("end buggy");

  count = 0;
  futures = [];
  console.log("start correct");
  for (i = 0; i < 10; i++) {
    futures.push(Future.task(function () {
      // By assigning to a local variable counting works.
      var a = one();
      count += a;
      console.log("count", count);
    }));
  }
  while (futures.length) {
    futures.pop().wait();
  }
  console.log("end correct");
}).run();
```

Outputs:

```
start buggy
count 1
count 1
count 1
count 1
count 1
count 1
count 1
count 1
count 1
count 1
end buggy
start correct
count 1
count 2
count 3
count 4
count 5
count 6
count 7
count 8
count 9
count 10
end correct
```

I would expect that it would be:

```
start buggy
count 1
count 2
count 3
count 4
count 5
count 6
count 7
count 8
count 9
count 10
end buggy
start correct
count 1
count 2
count 3
count 4
count 5
count 6
count 7
count 8
count 9
count 10
end correct
```

Node v6.3.0 (but observed also on v4), fibers 1.0.13.

**Comment by laverdet** [comment]
Certainly an interesting case, but this is to spec as far as Javascript is concerned.

You can reproduce this in plain v8 by using generators:
```js
"use strict";
let generators = [];
let count = 0;
for (let ii = 0; ii < 10; ++ii) {
	generators.push(function*() {
		count += yield;
		console.log(count);
	}());
}
generators.forEach(gen => gen.next());
generators.forEach(gen => gen.next(1));
```

Logs "1" ten times. Note that Firefox also agrees with this and logs the same thing.

Or perhaps more abstractly:
```js
let foo = 0;
function bar() {
  ++foo;
  return 1;
}
foo += bar();
console.log(foo);
```

Logs "1"; does not log "2".

Much in the same way `bar()` in the example above has a side-effect, so too does your call to `one()` and my call to `yield`. The specification is very clear about how these side-effects should be resolved.

You can find the relevant details here: [12.15.4 - Runtime Semantics: Evaluation](http://www.ecma-international.org/ecma-262/7.0/index.html#sec-assignment-operators-runtime-semantics-evaluation).

**Comment by mitar** [comment]
Oh. Ah. JavaScript really surprises again and again. Thank you for this great explanation and the time you took for it.

**Comment by bjouhier** [comment]
I got caught by this one earlier. In short, JavaScript evaluates `lhs += rhs` as:

```
v1 = lhs;
v2 = rhs;
v3 = v1 + v2;
lhs = v3;
```
If the first two lines were swapped your _bug_ would go away, but JS specs mandate that `lhs` be evaluated before `rhs`.

FWIW Java specs are similar: https://docs.oracle.com/javase/specs/jls/se8/html/jls-15.html#jls-15.26.2
