### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by null4bl3** [laverdet/node-fibers#304]
x86_64 Linux 4.7.2-1-ARCH
npm 3.10.6
node v6.5.0
------------------------------
> npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
> npm ERR! node v6.5.0
> npm ERR! npm  v3.10.6
> npm ERR! file sh
> npm ERR! code ELIFECYCLE
> npm ERR! errno ENOENT
> npm ERR! syscall spawn
> npm ERR! fibers@1.0.13 install: `node build.js || nodejs build.js`
> npm ERR! spawn ENOENT
> npm ERR! 
> npm ERR! Failed at the fibers@1.0.13 install script 'node build.js || nodejs build.js'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> 

Error occurs if either using npm or cloning the repo and building the package manually. 
 Update:

It seems it shows up when usin the very latest node package. i downgraded a single version, and have no problems on 6.4.0.

**Comment by laverdet** [comment]
Do you have a compiler installed?

**Comment by rosen-vladimirov** [comment]
It looks like Node.js 6.5.0 contains new version of v8 - updated from 5.0.x to 5.1.x. Previously Node.js raised their major version when updating minor version on v8, I'm not sure why this is not the case now.

**Comment by laverdet** [comment]
Apparently 5.1.x and 5.0.x are ABI compatible so I just published a new npm version of fibers with all 5.0 binaries copied to 5.1 as well. I'll want to find a better solution for the long term but this should get everyone up and running on the latest node version.

**Comment by laverdet** [comment]
Instead of using `process.versions.v8` to detect ABI compatibility I suspect I should be using `process.versions.modules`. I'll add that to the list of changes for October when the LTS cycle comes up.
