### ISSUE TITLE
75% of our CPU time is spent in fiber switching

### ISSUE THREAD

**Issue by kentonv** [laverdet/node-fibers#305]
It appears that v8's `Isolate::FindOrAllocatePerThreadDataForThisThread()` and `Isolate::FindPerThreadDataForThisThread()` traverse a linked list looking for the record matching the current "thread" (which I assume is their word for "fiber"?). These are called when switching fibers and hence each fiber switch is O(n) in the number of fibers, making the use of fibers in general O(n^2).

In practice, we've observed our server sitting at 100% CPU usage with about 75% of that being spent inside the inner loop of the linked list scan.

I realize this isn't node-fibers' fault _per se_ since the problem code is in v8, but I wanted to know if this is a known problem and if you have any advice on how to proceed. My guess is "get the v8 people to use a better data structure" but I don't really know what's going on in the code.

Perf screenshots for evidence:

![screenshot from 2016-08-31 19-23-41](https://cloud.githubusercontent.com/assets/4001805/18154242/d02a058c-6fb7-11e6-80f3-77be8b844dfa.png)
![screenshot from 2016-08-31 19-24-22](https://cloud.githubusercontent.com/assets/4001805/18154241/d0282262-6fb7-11e6-8504-e6e7df90d884.png)
![screenshot from 2016-08-31 19-23-11](https://cloud.githubusercontent.com/assets/4001805/18154250/e8af1a8e-6fb7-11e6-9cb9-5a90bf53a1be.png)

**Comment by kentonv** [comment]
v8 issue: https://bugs.chromium.org/p/v8/issues/detail?id=5338

**Comment by laverdet** [comment]
This is #wontfix on v8's end. I reported this years ago.. see: https://bugs.chromium.org/p/v8/issues/detail?id=3777

I would recommend observing `Fiber.fibersCreated`. If that number continues increasing while your process is running, instead of stabilizing then you should increase `Fiber.poolSize`. Let me know if that helps.

**Comment by kentonv** [comment]
Ah hah! Thanks, that should should help.

Why is the pool size static? Why not automatically increase the pool whenever it runs out, such that all fibers are always part of the pool?

**Comment by kentonv** [comment]
Hmm, looking at the code, it looks like if I go ahead and set `poolSize` to SIZE_MAX then I should get exactly that behavior, right?

**Comment by kentonv** [comment]
It looks like what's actually happening for us is that we have some sort of a buggy(?) code path that suddenly spawns 18k fibers at once. Those fibers run their course but from that point on the process is hosed because constantly re-scanning the 18k-element linked list is enough to slow things down to a crawl. Increasing the pool size unfortunately doesn't solve anything since we really are seeing 18k fibers all at once, not leaking gradually over time.

We're still narrowing down exactly what code is spawning the fibers. It's entirely possible that it will turn out to be reasonable code that legitimately wants to do 18k things at once, and would have gotten along just fine if this linked list had been a hashtable instead. We'll see.

**Comment by laverdet** [comment]
Good news.. it seems that since the time I opened that issue and now they've introduced an API to handle this situation. Could you try applying the following patch and let me know if it helps? Be sure to run `node build -f` after applying the patch to rebuild the binary.

```diff
diff --git a/src/fibers.cc b/src/fibers.cc
index df6c44f..c99d9cc 100644
--- a/src/fibers.cc
+++ b/src/fibers.cc
@@ -651,6 +651,8 @@ class Fiber {
                                v8_context->Exit();
                        }
 
+                       that.isolate->DiscardThreadSpecificMetadata();
+
                        // The function returned (instead of yielding).
                        that.started = false;
                        that.this_fiber->finish(*that.entry_fiber);
```

This will make the typical case a little bit slower, but should make your case where you accidentally spawn 18k fibers a lot faster, as long as those fibers eventually exit. If this helps I believe I can make it so both cases are fast, but that will have to wait until next week.

**Comment by kentonv** [comment]
I'd love to test this out but I'm not sure how to reproduce our exact problem without live users -- we haven't figured out exactly how to trigger it. We have, however, worked around the problem in another way (https://github.com/meteor/promise/pull/11), so further testing on live users now would be impolite. :)

That said, it seems highly likely that your patch would in fact allow our processes to recover after a fiber spike. Thanks!

Meanwhile, there has been various tagging activity on my issue https://bugs.chromium.org/p/v8/issues/detail?id=5338 without a "wontfix" yet, so I'm still holding out hope that v8 will switch to a hashtable as well.
