### ISSUE TITLE
Error trying to install security-adventures 

### ISSUE THREAD

**Issue by jprivillaso** [laverdet/node-fibers#307]
Hi, 

I was trying to install security-adventure package, that uses node-fibers. 
https://github.com/toolness/security-adventure

The console errors printed the following messages: 

Tell the author that this fails on your system: node ./build.js
Failed at the fibers@1.0.1 install script 'node ./build.js'.

Is there anything that I am missing? What can I do? 
Thanks in advance

**Comment by laverdet** [comment]
1.0.1 is a very old version of fibers and won't work on modern versions of node. Please install the latest version from npm.
