### ISSUE TITLE
How can I make this async method return a value?

### ISSUE THREAD

**Issue by gurvinder372** [laverdet/node-fibers#309]
Here is the related [SO question ](http://stackoverflow.com/questions/39703197/what-is-the-difference-between-run-vs-yield-in-node-fibers).

I can't find any good documentation (or any question on SO) that explains how exactly **yield** and **run** works.

Consider this  method

```
function findData( param )
  {
    var fiber = Fiber( function(){
      var currentFiber = Fiber.current;
      Model.findOne({ "param" : param}, function (err, data) {
        response = { err : err, data : data };
      });
    });
    return fiber;
  }
```
Model is an object that I get from Mongoose schema class (not sure if it is relevant).

Is this even possible? Please help me out on this.

**Comment by laverdet** [comment]
In that example you never actually call `fiber.run()` so the inner code is never executed.

There's plenty of examples of yield and run in README.md.

**Comment by gurvinder372** [comment]
Can you point me towards the example (In README.md or wherever) in which asynchronous code running inside Fiber returns data to the main event loop?

Also, can you point me towards the documentation which explains the functioning of Fiber.run() and Fiber.Yield?
  -  What does Fiber.run exactly do?
  -  What does Fiber.yield exactly do?
  -  How do they interact with each other?
  -  Where all can you invoke Fiber.run and Fiber.Yield?

Not sure why you closed the question.

**Comment by laverdet** [comment]
> Can you point me towards the example (In README.md or wherever) in which asynchronous code running inside Fiber returns data to the main event loop?

You can't return async data to the main event loop. Async requests need the main loop to be free before they can run, so if you were able to stop the main loop to wait on async data then the async data would never return. The best example of passing data back to the main loop is the fibonacci generator.

If you want to use Fibers to write entirely synchronous style code you'll need to run all your code inside of a main fiber or, for example, one fiber per HTTP request.

A good example of this is [synchronize](http://alexeypetrushin.github.io/synchronize/docs/index.html).

> Also, can you point me towards the documentation which explains the functioning of Fiber.run() and Fiber.Yield?

This should all be touched upon under [API Documentation](https://github.com/laverdet/node-fibers#api-documentation).
