### ISSUE TITLE
Node fibers in a VSCode Extension gives errors

### ISSUE THREAD

**Issue by Jakobud** [laverdet/node-fibers#310]
I am attempting to use `asyncawait` (https://github.com/yortus/asyncawait) which utilizes Fibers in a Visual Studio Code extension. When I attempt to start the extension I get this:

```
Activating extension `MyLaptop.vscode-myextension` failed: `/Users/user1/Repos/vscode-myextension/node_modules/fibers/bin/darwin-x64-v8-4.9/fibers.node` is missing. Try reinstalling `node-fibers`?.
Activating extension `MyLaptop.vscode-myextension` failed:  `/Users/user1/Repos/vscode-myextension/node_modules/fibers/bin/darwin-x64-v8-4.9/fibers.node` is missing. Try reinstalling `node-fibers`?
Here is the error stack:  Error: `/Users/user1/Repos/vscode-myextension/node_modules/fibers/bin/darwin-x64-v8-4.9/fibers.node` is missing. Try reinstalling `node-fibers`?
    at Object.<anonymous> (/Users/user1/Repos/vscode-myextension/node_modules/fibers/fibers.js:16:8)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.L.I.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:12:25921)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/user1/Repos/vscode-myextension/node_modules/asyncawait/src/fibers.js:1:92)
    at Module._compile (module.js:413:34)
```

I tried specifically uninstalling and reinstalling `node-fibers` but it didn't seem to make a difference. Here is my uninstall/reinstall output:

```
user1@User1:~/Repos/vscode-myextension                                                                                               
# npm uninstall fibers                                                                                                                     
- fibers@1.0.14 node_modules/fibers                                                                                                        
npm WARN EPACKAGEJSON vscode-myextension@0.1.0 No repository field.                                                                              
npm WARN EPACKAGEJSON vscode-myextension@0.1.0 No license field.                                                                                 

user1@User1:~/Repos/vscode-myextension                                                                                               
# npm install fibers                                                                                                                       

> fibers@1.0.14 install /Users/user1/Repos/vscode-myextension/node_modules/fibers                                                          
> node build.js || nodejs build.js                                                                                                         

`darwin-x64-v8-4.6` exists; testing                                                                                                        
Binary is fine; exiting                                                                                                                    
vscode-myextension@0.1.0 /Users/user1/Repos/vscode-myextension                                                                                   
└── fibers@1.0.14                                                                                                                          

npm WARN EPACKAGEJSON vscode-myextension@0.1.0 No repository field.                                                                              
npm WARN EPACKAGEJSON vscode-myextension@0.1.0 No license field.                                                                                 

user1@User1:~/Repos/vscode-myextension                                                                                               
#                                                    
```

The Node.js version being used by VSCode under the hood is I think 5.10.x. Does Node Fibers have issues running on certain versions of Node.js? Or is there something else obvious I'm missing here?

**Comment by laverdet** [comment]
Node 5 binaries aren't included by default. Fibers will compile and run just fine on Node 5 but your build process doesn't seem to be invoking the full npm install pipeline. You also seem to have at least 2 different versions of Node installed.. Node 5 like you mentioned and then I would guess Node 4. I would recommend replacing Node 5 with either 4 or 6, since Node 5 was a development release and is no longer supported.

**Comment by Jakobud** [comment]
So, by build process, what do you mean? When I install `asyncawait` it uses `node-fibers` as a dependency and thus npm installs `node-fibers`. Shouldn't it automatically be invoking the full npm install pipeline?

Node 5 is what Visual Studio Code uses internally. No option to "swap it out" with a different version unfortunately.

**Comment by laverdet** [comment]
About the build process, maybe you didn't include all the output.. I don't know. When `npm install fibers` is invoked it should either say the binary exists and is exiting, or that there is something wrong and it needs to rebuild. The first console output you posted has neither of that. Those are just some spooky error messages from vscode.

If you can't replace node 5, then uninstall node 4 from your system and install node 5 instead. The problem in the second console output is that you're using node 4 to install fibers, and then including it with node 5.. it's a different version.

**Comment by Jakobud** [comment]
It looks like the local Node version I am running is 5.1.1:

```
# node -v
5.1.1
```

Okay so I backed up a few steps, deleted my `node_modules` directory. Then:

```
# npm install asyncawait

> fibers@1.0.14 install /Users/jake.wilson/Repos/vscode-cdnjs/node_modules/fibers
> node build.js || nodejs build.js

`darwin-x64-v8-4.6` exists; testing
Binary is fine; exiting
vscode-cdnjs@0.1.0 /Users/jake.wilson/Repos/vscode-cdnjs
├── asyncawait@1.0.6  extraneous
└── fibers@1.0.14 

npm WARN EPACKAGEJSON vscode-cdnjs@0.1.0 No repository field.
npm WARN EPACKAGEJSON vscode-cdnjs@0.1.0 No license field.
```

That is the full output of what I'm seeing in my Terminal. Any thoughts here?

**Comment by laverdet** [comment]
That is the output of a successful install.

**Comment by sjmcdowall** [comment]
Yeah -- that it worked just fine??  Looks like you may have asyncawait twice in your packages.json?  But -- looks like everyone is happy. 

BTW -- what ever makes you think VSCode on Mac doesn't support Node V6.X ??

**Comment by laverdet** [comment]
Also something is very weird about your vscode node as well. It says it's looking for `darwin-x64-v8-4.9` but node 4 uses v8 4.5, node 5 uses v8 4.6, and node 6 uses v8 5.0 or 5.1. I don't know how you got stuck with v8 4.9.

**Comment by Jakobud** [comment]
@sjmcdowall asyncawait is only listed in my package.json once. 

Regarding Node and VSCode, internally, VSCode runs on Node 5.10.x from what I read (https://github.com/Microsoft/vscode/issues/9782#issuecomment-235281859).
