### ISSUE TITLE
npm install fibers-1.0.15 failing at SLES12SP1

### ISSUE THREAD

**Issue by dantran** [laverdet/node-fibers#314]
no problem at 1.0.14

here is the error. Please advice.  Is it a bug?. I am using node 5.6, npm 3.6. The last line seems to be issue

[INFO] 
[INFO] > fibers@1.0.15 install /space/jenkins/dpadswci/workspace/myui/node_modules/fibers
[INFO] > node build.js || nodejs build.js
[INFO] 
[ERROR] gyp: /space/jenkins/dpadswci/workspace/myui/.external-resources/npm/source/common.gypi not found (cwd: /space/jenkins/dpadswci/workspace/myui/node_modules/fibers) while reading includes of binding.gyp while trying to load binding.gyp
[ERROR] gyp ERR! configure error 
[ERROR] gyp ERR! stack Error: `gyp` failed with exit code: 1
[ERROR] gyp ERR! stack     at ChildProcess.onCpExit (/space/jenkins/dpadswci/workspace/myui/.external-resources/node/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
[ERROR] gyp ERR! stack     at emitTwo (events.js:100:13)
[ERROR] gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
[ERROR] gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
[ERROR] gyp ERR! System Linux 3.12.49-11-default
[ERROR] gyp ERR! command "/space/jenkins/dpadswci/workspace/myui/.external-resources/node/node" "/space/jenkins/dpadswci/workspace/myui/.external-resources/node/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
[ERROR] gyp ERR! cwd /space/jenkins/dpadswci/workspace/myui/node_modules/fibers
[ERROR] gyp ERR! node -v v5.6.0
[ERROR] gyp ERR! node-gyp -v v3.2.1
[ERROR] gyp ERR! not ok 
[ERROR] node-gyp exited with code: 1
[ERROR] Please make sure you are using a supported platform and node version. If you
[ERROR] would like to compile fibers on this machine please make sure you have setup your
[ERROR] build environment--
[ERROR] Windows + OS X instructions here: https://github.com/nodejs/node-gyp
[ERROR] Ubuntu users please run: `sudo apt-get install g++ build-essential`
[ERROR] Alpine users please run: `sudo apk add python make g++`
[ERROR] sh: nodejs: command not found

**Comment by laverdet** [comment]
You will need to either upgrade to node 6 or install a compiler (see error message for instructions). I'm no longer including pre-built binaries for node 5, as it is no longer maintained by the node developers (node 6 took its place). For future reference odd-numbered versions of node will receive very little support in the long term. You can find more information here: https://github.com/nodejs/LTS

You also have the option to just stay on fibers 1.0.14.

**Comment by dantran** [comment]
This will break lots builds, not sure why you decide to break  the semantic version contract ie 1.0.14 to 1.0.15

**Comment by dantran** [comment]
btw, I do have g++ compiler.   

[ERROR] sh: nodejs: command not found  

is the real issu

**Comment by laverdet** [comment]
Odd-numbered versions of node are development only and considered unstable. node v5 hasn't seen any updates since July and is abandoned for node v6.

Your build is failing because `node` and `nodejs` are both not found in your PATH. If using an alias please don't do that.

**Comment by dantran** [comment]
It turns out the problem lies in here "[ERROR] gyp: /space/jenkins/dpadswci/workspace/myui/.external-resources/npm/source/common.gypi not found (cwd: /space/jenkins/dpadswci/workspace/myui/node_modules/fibers) while reading includes of binding.gyp while trying to load binding.gyp"

My build uses frontend-maven-plugin to build node projects.  This plugin is configured not writing to home directory ~/.npm  ~/.node-gyp ( CI requirement) but under current assigned workspace  and this triggers failure for filbers-1.0.15.  Still looking...
