### ISSUE TITLE
fibers install error at node ./build.js 

### ISSUE THREAD

**Issue by skumaroh** [laverdet/node-fibers#315]
![image](https://cloud.githubusercontent.com/assets/6601876/19296953/bf880a1c-9005-11e6-830b-ca6d8f3f920f.png)

**Comment by sjmcdowall** [comment]
Are you really trying to use Fibers 0.6.9?  I can't imagine how old that version is -- the latest version is 1.0.15 (I believe).  Perhaps try that one? Also -- maybe look at upgrading to Node V6.X ??  It's a nice version and will be the LTS version very soon .. (if its not already).  Cheers!

**Comment by laverdet** [comment]
^
