### ISSUE TITLE
better error logging

### ISSUE THREAD

**Issue by gsabran** [laverdet/node-fibers#317]
I'm deploying a meteor application, and meteor uses fiber. The deployment is failing, and the only error log I'm getting is:

```
>>  /bundle/bundle/programs/server/node_modules/fibers/future.js:313
>>                          throw(ex);
>>                          ^
>>  [object Object]
```

Would it be possible to log the original error and trace no matter what?

**Comment by laverdet** [comment]
This isn't an issue with fibers. Good luck with your debugging!

**Comment by gsabran** [comment]
You might be right.. Alas! Can you confirm that it's excepted that `ref[1]` is not used in the evaluation here: https://github.com/laverdet/node-fibers/blob/master/future.js#L306 ?

**Comment by laverdet** [comment]
Yeah that code looks like it's working as intended. `ref[1]` is a function that is only called in case of success. Since that is in the `throw` case it would not be called.

**Comment by gsabran** [comment]
thanks!
