### ISSUE TITLE
Unable to install with node.js and Windows 10

### ISSUE THREAD

**Issue by PainKKKiller** [laverdet/node-fibers#320]
When I run in command line 

> npm install fibers

everything OK. But when I trying to install meteor with command

> npm install meteor

meteor try to install fiber, and it gets error, I attach npm log
[npm-debug.zip](https://github.com/laverdet/node-fibers/files/576128/npm-debug.zip)

``

**Comment by sjmcdowall** [comment]
That's not how you install meteor --- [Install Metoer](https://www.meteor.com/install)

Meteor is an odd duck that, at least in the past, bundled it's own Fibers etc. etc.

**Comment by laverdet** [comment]
Yeah this isn't an issue with fibers. If you read the error long you'll see that it's attempting to install fibers 0.6.9 which is 2 years old. Good luck!
