### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by bradvogel** [laverdet/node-fibers#322]
Just a small request: would you mind adding a changelog to the readme? It'll help track important changes.

**Comment by laverdet** [comment]
I'll be better about summarizing changes in the git commit when I update the version number.

**Comment by Heartnett** [comment]
I agree with @bradvogel

**Comment by laverdet** [comment]
Changes can be found in package.json commits: https://github.com/laverdet/node-fibers/commit/93a783985e85dce0ef72709885d9cb68d70f88d7.

I consider fibers to be obsolete so there won't be any new features, just compatibility fixes.

**Comment by Heartnett** [comment]
> I consider fibers to be obsolete so there won't be any new features, just compatibility fixes.

If that's the case, then why not  say that in the readme ?

**Comment by laverdet** [comment]
Hey good point. I've been pretty vocal about it on the issue tracker but never actually put anything on the front page. I wrote a note about that in e2a0ed9c6d985f94c2b1947eaf72d5797e8a3278.
