### ISSUE TITLE
How does the fls_data get initialized for the first time?

### ISSUE THREAD

**Issue by tbodt** [laverdet/node-fibers#324]
I'm reading the code and trying to understand how it works, and there's one thing I don't understand. It appears that the first time the fls_data in a coroutine is used, it hasn't been set to anything yet, so it has the default std::vector value which I believe is NULL. So the three thread-local pieces of data in the isolate get set to 0. Does V8 automatically allocate new things for those variables if they are set to zero?

**Comment by laverdet** [comment]
Yes, it sets the thread-specifics to 0. The default value of a thread-specific is always 0, see pthread_getspecific:

> The pthread_getspecific() function shall return the thread-specific data value associated with the given key. If no thread-specific data value is associated with key, then the value NULL shall be returned.

This is how we fool v8 into thinking it's on many different threads when in reality there's only one. On the v8 side this will look something like:
```
  int thread_id = pthread_getspecific(thread_id_key_);
  if (thread_id == 0) {
    thread_id = AllocateThreadId();
    pthread_setspecific(thread_id_key_, thread_id);
  }
```

You can see this same pattern in [Coroutine& Coroutine::current()](https://github.com/laverdet/node-fibers/blob/8d7e4ffeb5151ade2ef32455080fbb2ffc226e13/src/coroutine.cc#L143).
