### ISSUE TITLE
Error Building on Mac

### ISSUE THREAD

**Issue by FarMcKon** [laverdet/node-fibers#328]
Error when trying to build/install on a OSX as part of meteor install.
[npm-debug.log.txt](https://github.com/laverdet/node-fibers/files/651141/npm-debug.log.txt)

 $> OSX 10.11.4 (15E65)
 $> npm version
{ np

m: '3.10.9',
  ares: '1.10.1-DEV',
  cldr: '30.0.2',
  http_parser: '2.7.0',
  icu: '58.1',
  modules: '51',
  node: '7.2.1',
  openssl: '1.0.2j',
  tz: '2016g',
  unicode: '9.0',
  uv: '1.10.1',
  v8: '5.4.500.44',
  zlib: '1.2.8' }

Thanks.

**Comment by laverdet** [comment]
Please see section "meteor users please read this" in readme.
