### ISSUE TITLE
Error when using fibers/future in an angular meteor project

### ISSUE THREAD

**Issue by kenpachi-zaraki** [laverdet/node-fibers#329]
Hi,

I'm having issues when using fibers/future. 

I'm using :
- Angular2 Meteor: https://angular-meteor.com/tutorials/socially/angular2/bootstrap
- Meteor npm Version: 3.10.9
- Meteor node Version: v4.6.1
- Meteor Release: METEOR@1.4.2

I have successfully installed fibers:

ken@ubuntu:~/projects/myproject$ meteor npm install fibers --save

> fibers@1.0.15 install /home/ken/projects/myproject/node_modules/fibers
> node build.js || nodejs build.js

`linux-x64-46` exists; testing
Binary is fine; exiting
socially@ /home/ken/projects/myproject
└── fibers@1.0.15

In photos.methods.ts, I have :

import { Meteor } from 'meteor/meteor';
import { Future } from 'fibers/future';
// const Future = require('fibers/future');
import { Resizer } from 'meteor/thinksoftware:image-resize-client';

Meteor.methods({
        resize: function(file: File) {
        let future = new Future();
        Resizer.resize(file, {width: 1500, height: 1500, cropSquare: true}, function (err, file) {
            // future["return"](file);
        });
	return future.wait();
    }
});

I manage to launch meteor command successfully (meteor). But when I visite the url: http://localhost:3000, it never loads up. And in the javascript console, I get the following error:

## There is an issue with `node-fibers` ##
`/node_modules/fibers/bin/browser-undefined-undefined/fibers.node` is missing.

Try running this to fix the issue: undefined /node_modules/fibers/build
meteorInstall.node_modules.fibers.fibers.js @ modules.js?hash=0444355…:42060
fileEvaluate @ modules-runtime.js?hash=ab7e8d3…:191
require @ modules-runtime.js?hash=ab7e8d3…:116
meteorInstall.node_modules.fibers.future.js @ modules.js?hash=0444355…:41561
fileEvaluate @ modules-runtime.js?hash=ab7e8d3…:191
require @ modules-runtime.js?hash=ab7e8d3…:116
meteorInstall.both.methods.photos.methods.js @ photos.methods.ts:26
fileEvaluate @ modules-runtime.js?hash=ab7e8d3…:191
require @ modules-runtime.js?hash=ab7e8d3…:116
(anonymous) @ post.model.ts:17

Uncaught Error: Missing binary. See message above.
    at meteorInstall.node_modules.fibers.fibers.js (modules.js?hash=0444355…:42065)
    at fileEvaluate (modules-runtime.js?hash=ab7e8d3…:191)
    at require (modules-runtime.js?hash=ab7e8d3…:116)
    at meteorInstall.node_modules.fibers.future.js (modules.js?hash=0444355…:41561)
    at fileEvaluate (modules-runtime.js?hash=ab7e8d3…:191)
    at require (modules-runtime.js?hash=ab7e8d3…:116)
    at meteorInstall.both.methods.photos.methods.js (photos.methods.ts:26)
    at fileEvaluate (modules-runtime.js?hash=ab7e8d3…:191)
    at require (modules-runtime.js?hash=ab7e8d3…:116)
    at post.model.ts:17

I tried to use either of these:
import { Future } from 'fibers/future';
//OR
const Future = require('fibers/future');

But I get the same error. 

Your help will be very much appreciated.

**Comment by laverdet** [comment]
Please see the "meteor users please read this" section in the readme.
