### ISSUE TITLE
error node ./build.js on Debian Jessie virtual machine when trying to install meteor

### ISSUE THREAD

**Issue by AgedLace** [laverdet/node-fibers#330]
npm version 3.10.10
node version 7.3.0
kernel Linux 3.16.0-4-amd64

When I tried to install meteor via npm, I receive the following output.  

409 verbose pkgid fibers@0.6.9
410 verbose cwd /home/debvm/Dev/project-folder
411 error Linux 3.16.0-4-amd64
412 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "meteor"
413 error node v7.3.0
414 error npm  v3.10.10
415 error code ELIFECYCLE
416 error fibers@0.6.9 install: `node ./build.js`
416 error Exit status 1
417 error Failed at the fibers@0.6.9 install script 'node ./build.js'.
417 error Make sure you have the latest version of node.js and npm installed.
417 error If you do, this is most likely a problem with the fibers package,
417 error not with npm itself.
417 error Tell the author that this fails on your system:
417 error     node ./build.js
417 error You can get information on how to open an issue for this project with:
417 error     npm bugs fibers
417 error Or if that isn't available, you can get their info via:
417 error     npm owner ls fibers
417 error There is likely additional logging output above.
418 verbose exit [ 1, true ]

**Comment by laverdet** [comment]
Please see the section in the readme about meteor
