### ISSUE TITLE
pull/308 issue still on the npm version

### ISSUE THREAD

**Issue by ycscholes** [laverdet/node-fibers#341]
return outside of function error still occurs on the npm version
@laverdet  Could you please publish the latest code to npm?

Thank you

**Comment by laverdet** [comment]
Is this actually causing issues for you other than linter warnings? You can return from top level in node applications.

**Comment by ycscholes** [comment]
@laverdet  Thanks for your reply, it's my webpack config issue.

I use webpack to bundle the code for electron, then it cause the 'return outside of function' error.
After I external the node_modules in the webpack config file. It solves the issue.
