### ISSUE TITLE
Removal of node 4.x binary without bumping versions has broken builds

### ISSUE THREAD

**Issue by sdd** [laverdet/node-fibers#342]
It looks like you have dropped support for the node 4.x binary, but only bumped the patch version.

As a consequence, via flightplan, this has broken our build.

**Comment by brokenmass** [comment]
same issue.

**Comment by krevels** [comment]
I've noticed my 0.12.x and 0.10.x builds suddenly breaking as well.  Could this be related?

**Comment by laverdet** [comment]
Good point, these updates should probably bump the semvar. Though it's kind of a grey area because the code is still compatible, you just would need to compile it. Anyway I've republished as 2.0.0 and opened a ticket w/ npm to unpublish 1.0.16 (since it is more than 24h old you have to go through manual support channels).

**Comment by natesilva** [comment]
Would it be possible to include Node 4.x binaries in `fibers@2`? This could help to prevent fragmentation in downstream projects.

If someone wants to support Node 4.x and Node 8.x, they currently need to ship one version that depends on fibers-1.0.15 and one that depends on fibers-2.0.0.

Of course, they can give up binary compatibility and tell Windows users to install the build tools, etc. But a lot of projects want an easy binary install.

The `fibers` project only provides binaries for LTS releases -- which is understandable -- but Node 4.x is still in LTS maintenance, so it feels like it should be supported until that ends.

**Comment by laverdet** [comment]
No can do. Supporting 3 node versions means I have to ship 18 different binaries which is crazy talk.
