### ISSUE TITLE
`.../node_modules/fibers/bin/darwin-x64-54/fibers.node` is missing.

### ISSUE THREAD

**Issue by jordansitbon** [laverdet/node-fibers#344]
Hi,

When i run "node build"he return "`darwin-x64-48` exists; testing Binary is fine; exiting". But when i start my electron app with "npm start" and i try use **sync** in main.js i've this error :
`.../node_modules/fibers/bin/darwin-x64-54/fibers.node` is missing.

If anyone have ideas?

PS: Sorry for bad english 😅

**Comment by laverdet** [comment]
Electron is support but you'll need to build the binaries yourself. You can find more information here--
https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md
