### ISSUE TITLE
Switch over to N-API

### ISSUE THREAD

**Issue by gunar** [laverdet/node-fibers#345]
It might be a bit early as the `N-API` is still experimental, but we should keep an eye out for it.

- https://medium.com/the-node-js-collection/n-api-next-generation-node-js-apis-for-native-modules-169af5235b06
- https://nodejs.org/api/n-api.html

**Comment by laverdet** [comment]
N-API isn't targeting projects like fibers. fibers uses lots of v8-specific features which you can't do generically.
