### ISSUE TITLE
(sudo) npm install mongo-sync -a terminates with a node-fibers error 

### ISSUE THREAD

**Issue by G-M-F** [laverdet/node-fibers#346]
OS is OpenSuse 13.2

@gawain:~/nodejstutorial/event-example> sudo npm install mongo-sync 
npm WARN package.json event-example@1.0.0 No description
npm WARN package.json event-example@1.0.0 No repository field.
npm WARN package.json event-example@1.0.0 No README data
npm WARN deprecated mongodb@2.0.24: Please upgrade to 2.2.19 or higher

> fibers@2.0.0 install /avalonfs/sammy_stefan/nodejstutorial/event-example/node_modules/mongo-sync/node_modules/fibers
> node build.js || nodejs build.js

gyp: /usr/share/node/common.gypi not found (cwd: /avalonfs/sammy_stefan/nodejstutorial/event-example/node_modules/mongo-sync/node_modules/fibers) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib64/node_modules/npm/node_modules/node-gyp/lib/configure.js:308:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.16.7-53-desktop
gyp ERR! command "/usr/bin/node" "/usr/lib64/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /avalonfs/sammy_stefan/nodejstutorial/event-example/node_modules/mongo-sync/node_modules/fibers
gyp ERR! node -v v4.6.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
Alpine users please run: `sudo apk add python make g++`
sh: nodejs: Kommando nicht gefunden.

> bson@0.2.22 install /avalonfs/sammy_stefan/nodejstutorial/event-example/node_modules/mongo-sync/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)

> kerberos@0.0.23 install /avalonfs/sammy_stefan/nodejstutorial/event-example/node_modules/mongo-sync/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)

gyp: /usr/share/node/common.gypi not found (cwd: /avalonfs/sammy_stefan/nodejstutorial/event-example/node_modules/mongo-sync/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib64/node_modules/npm/node_modules/node-gyp/lib/configure.js:308:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.16.7-53-desktop
gyp ERR! command "/usr/bin/node" "/usr/lib64/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /avalonfs/sammy_stefan/nodejstutorial/event-example/node_modules/mongo-sync/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
gyp ERR! node -v v4.6.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm ERR! Linux 3.16.7-53-desktop
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "mongo-sync"
npm ERR! node v4.6.1
npm ERR! npm  v2.15.9
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! fibers@2.0.0 install: `node build.js || nodejs build.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the fibers@2.0.0 install script 'node build.js || nodejs build.js'.
npm ERR! This is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js || nodejs build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fibers
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /avalonfs/sammy_stefan/nodejstutorial/event-example/npm-debug.log

**Comment by sjmcdowall** [comment]
How about using node v6 or v8 ??

**Comment by laverdet** [comment]
There's something wrong with your node or node-gyp installation. If you [Google this error](https://www.google.com/webhp?q=%22/usr/share/node/common.gypi%22+not+found) you'll find lots of people having the same problem on dozens of other projects. I suggest uninstalling nodejs and reinstalling, perhaps upgrading to node v8 in the process as node v4 is approaching the end of its lifecycle.

**Comment by G-M-F** [comment]
After the latter comment I deleted node_modules and reinstalled everything. Now the problem is gone. 
When deleting I had problems with NFS resources. The resolution required a reboot of the machine and finally of the NAS sever. So potentially an issue with my NFS (NAS) server, that did cause the issue.

**Comment by laverdet** [comment]
Glad to hear you figured it out~
