### ISSUE TITLE
Resolving Promise in Fiber

### ISSUE THREAD

**Issue by Sincap80** [laverdet/node-fibers#347]
Resolving a Promise in a Fiber works, but I cant get it out of the Fiber.
`const Fiber = require("fibers");
const p = Fiber(() => {
  const result = Future.fromPromise(Promise.resolve(5)).wait();
  console.log(result);  //<---- works here
  return result;
}).run();

console.log(p); //<----- doesn't work here
`
p should be the value 5.
Am I doing it wrong or do I need always a Fiber?

Best Regards

**Comment by laverdet** [comment]
What's happening is when you call `Future(...).wait()` on line 3 the fiber yields back to the outer scope and `undefined` is assigned to `const p`. The `console.log` on line 8 then runs and logs "undefined". After that `Promise.resolve(5)` finishes resolving which resolves the Future, and then re-enters the fibers and logs the correct value.

I'm not totally sure what you're trying to do but something like this will work:
```js
const Future = require('future');
const promise = Future.task(() => {
	return Future.fromPromise(Promise.resolve(5)).wait();
}).promise();

promise.then(console.log);
```

Generally you should use either Fiber OR Future, not both.

**Comment by Sincap80** [comment]
Generally I don't want the then block.
I want something like:
```
const dbObj = doAsynctoSync(...)
dbObj.getCursor()
```

**Comment by laverdet** [comment]
Yeah you can't pause the main event loop with fibers. You should use the *sync methods for that, for example `fs.readFileSync` or `child_process.execSync`. There are serious performance problems with those functions though; it is not recommended to pause the main event loop except during startup.
