### ISSUE TITLE
How to use Futures in an Webpack 1.15.0 environment

### ISSUE THREAD

**Issue by wsutter** [laverdet/node-fibers#349]
Hi there

I would like to use Futures within my angular project (I'm gonna call it a "widget") which is built by webpack 1.15.0.

So my widget needs to retrieve data from a remote REST endpoint asynchronously. However, I need to make sure that the data is actually available before continuing and hence make that asynchronous call somewhat synchronous... Futures seem to be just what I need here since they kinda serve as a barrier.

`let future = new Future;

// the subsequent function uses angular's $resource and is therefore asynchronous
dataResourceService
  .getResource(configuration)
  .get({
    // some parameters...
  })
  .$promise
  .then(
    (retrievedData) => {
      future.return(retrievedData);
    },
    () => {
      future.throw('Unable to retrieve data from the configured resource!');
    }
  );

retrievedData = future.wait();`

So the script can only continue after the last line if and only if the future returns some data.

At the top of this file, I imported Futures with the following require statment:

`let Future = require('fibers/future');`

I also added `"fibers": "^2.0.0"` to the dependencies section in my package.json file.

Finally, I have this webpack configuration:

`const ExtractTextPlugin = require('extract-text-webpack-plugin');
const path = require('path');
const webpack = require('webpack');

module.exports = {
  entry: {
    widget: './index.js'
  },
  output: {
    path: path.join(__dirname, 'dist'),
    filename: 'widget.min.js',
    library: 'myWidget',
    libraryTarget: 'umd',
    umdNamedDefine: true
  },
  devtool: 'source-map',
  externals: {
    angular: 'angular',
    jquery: 'jquery',
    lodash: 'lodash'
  },
  module: {
    loaders: [
      {
        test: /\.html$/,
        loader: 'html'
      },
      {
        test: /\.js$/,
        loader: 'babel',
        query: {
          presets: ['es2015']
        }
      },
      {
        test: /\.scss$/,
        loader: ExtractTextPlugin.extract('css!sass')
      }
    ]
  },
  plugins: [
    new ExtractTextPlugin('widget.min.css'),
    new webpack.optimize.UglifyJsPlugin({
      comments: false,
      minimize: true,
      sourceMap: true
    })
  ]
};`

If I now run `webpack.js -d --config webpack-dist.config.js`, compilation fails due to some very perculiar reasons:

ERROR in ./~/fibers/fibers.js
Module not found: Error: Cannot resolve module 'fs' in widget/node_modules/fibers
 @ ./~/fibers/fibers.js 6:10-23

ERROR in ./~/fibers/test/child-process.js
Module not found: Error: Cannot resolve module 'child_process' in widget/node_modules/fibers/test
 @ ./~/fibers/test/child-process.js 7:12-36

ERROR in ./~/fibers/test/exec.js
Module not found: Error: Cannot resolve module 'child_process' in widget/node_modules/fibers/test
 @ ./~/fibers/test/exec.js 11:2-26

ERROR in ./~/fibers/test/future-exception.js
Module not found: Error: Cannot resolve module 'future' in widget/node_modules/fibers/test
 @ ./~/fibers/test/future-exception.js 4:13-30

ERROR in ./~/fibers/test/future.js
Module not found: Error: Cannot resolve module 'future' in widget/node_modules/fibers/test
 @ ./~/fibers/test/future.js 7:10-27

What puzzles me is that not only is webpack trying to compile fibers.js, but also the tests.
That seems completely wrong...

I believe what I should rather be doing is requiring the fibers.node addon in my script. Something like this:

`let Future = require('fibers.node')`

But that doesn't work, of course, since it probably should rather be something like this:

`let Future = require('fibers/bin/linux-x64-51/fibers.node')`

or maybe rather

`let Future = require('bindings')('fibers.node')`

But then, I might also need to enhance the webpack configuration by another loader, like this:

`{
    test: /\.node$/,
    loader: 'node-loader'
}`

So, you see, I'm completely puzzled on how I can make use of fibers in my environment. Help is much appreciated.

Walter

**Comment by sjmcdowall** [comment]
Is there a reason why you can’t use async/await for this?  Just curious.

**Comment by laverdet** [comment]
If you're using webpack to generate server-side code you need to add `target: 'node'` to your config. That'll get you through the build stage but it's still going to fail on runtime. I'd recommend using async/await like sjmcdowall mentioned. If you're set on using fibers for some reason then you'll just have to hardcode the binary.
