### ISSUE TITLE
Failure when packaged with "pkg"

### ISSUE THREAD

**Issue by tysenmoore-xse** [laverdet/node-fibers#353]
I have a project that uses fibers that is ultimately bundled with [pkg](https://www.npmjs.com/package/pkg#assets)  However, when the packaged code executes the fiber code exceptions out as follows:

```
.## There is an issue with `node-fibers` ##
`/snapshot/a2b-analyzer-service/node_modules/fibers/bin/linux-x64-48/fibers.node` is missing.

Try running this to fix the issue: /home/tmoore/work/tmp/a2b-analyzer-service/dist/a2b-analyzer-service /snapshot/a2b-analyzer-service/node_modules/fibers/build
Error: Missing binary. See message above.
    at Object.<anonymous> (/snapshot/a2b-analyzer-service/node_modules/fibers/fibers.js:20:8)
    at Module._compile (pkg/prelude/bootstrap.js:1226:22)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at Module.require (pkg/prelude/bootstrap.js:1136:31)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/snapshot/a2b-analyzer-service/node_modules/synchronize/sync.js:3:13)
```
The error seems to be a result of some error checking to ensure the fibers addon has been compiled/exists, if this file cannot be found it fails.  [pkg](https://www.npmjs.com/package/pkg#assets) bootstraps the executable to "massage" the paths of the required modules/files to match the paths needed by the packaged project so a `require` will succeed.   Since the files are packaged and do not physically exist in their original location the firber.js code always fails.  I have found that if I comment out the try/catch the fiber implementation works as expected.

I have a proposed solution that would attempt the require the fiber code and if it fails it would then do the original check to ensure that the fiber code exists and was compiled.  This code should be backward compatible for any other users as well as better support node packaging tools like: [pkg](https://www.npmjs.com/package/pkg#assets), [nexe](https://www.npmjs.com/package/nexe), etc.

fibers.js
```
try {
    // Pull in fibers implementation
    process.fiberLib = module.exports = require(modPath).Fiber;
} catch (err) {

    // See if the module has even been compiled
    try {
        fs.statSync(modPath+ '.node');
    } catch (ex) {
        // No binary!
        console.error(
            '## There is an issue with `node-fibers` ##\n'+
            '`'+ modPath+ '.node` is missing.\n\n'+
            'Try running this to fix the issue: '+ process.execPath+ ' '+ __dirname.replace(' ', '\\ ')+ '/build'
        );
        throw new Error('Missing binary. See message above.');
    }
}
```
Does this code seem reasonable?  Is this something you would be interested in merging?  If so, do you need a PR or is this issue sufficient?  Thanks for the time.

(Can find the code in the fork: https://github.com/tysenmoore-xse/node-fibers)

**Comment by marcelwolf1989** [comment]
I tried to change the code in the fibers.js but the problem is still there. Do I need to recompile the whole stuff? @tysenmoore-xse

**Comment by tysenmoore-xse** [comment]
I am not sure what you want to "recompile".  I would try a clean (rm -rf ./node_modules, then) `npm install`.  Also, what version of `pkg` are you using?  I have: `"pkg": "^4.2.4"`.  As another note, I have tested this solution in Windows and Linux.

**Comment by laverdet** [comment]
Your suggested is almost ok. It doesn't work in the case where the require fails but the stat succeeds, though. This can happen if a compiled binary exists but can't load for whatever reason.

Does this work for you?

```
diff --git a/fibers.js b/fibers.js
index c858fe9..67a147e 100644
--- a/fibers.js
+++ b/fibers.js
@@ -9,7 +9,8 @@ if (process.fiberLib) {
        // Look for binary for this platform
        var modPath = path.join(__dirname, 'bin', process.platform+ '-'+ process.arch+ '-'+ process.versions.modules, 'fibers');
        try {
-               fs.statSync(modPath+ '.node');
+               // Pull in fibers implementation
+               process.fiberLib = module.exports = require(modPath).Fiber;
        } catch (ex) {
                // No binary!
                console.error(
@@ -17,9 +18,7 @@ if (process.fiberLib) {
                        '`'+ modPath+ '.node` is missing.\n\n'+
                        'Try running this to fix the issue: '+ process.execPath+ ' '+ __dirname.replace(' ', '\\ ')+ '/build'
                );
+               console.error(ex.stack || ex.message || ex);
                throw new Error('Missing binary. See message above.');
        }
-
-       // Pull in fibers implementation
-       process.fiberLib = module.exports = require(modPath).Fiber;
 }
```

**Comment by tysenmoore-xse** [comment]
Thanks for the suggestion, however, I tried to apply your patch to the your code and my fork and both failed.  Are you suggesting to replacing the stat with the require?

**Comment by tysenmoore-xse** [comment]
From an initial test by replacing the stat with the require it seems to work.  for clarity the file is:

```
if (process.fiberLib) {
    module.exports = process.fiberLib;
} else {
	var fs = require('fs'), path = require('path');

	// Seed random numbers [gh-82]
	Math.random();

	// Look for binary for this platform
	var modPath = path.join(__dirname, 'bin', process.platform+ '-'+ process.arch+ '-'+ process.versions.modules, 'fibers');
	try {
		// Pull in fibers implementation
		process.fiberLib = module.exports = require(modPath).Fiber;
	} catch (ex) {
		// No binary!
		console.error(
			'## There is an issue with `node-fibers` ##\n'+
			'`'+ modPath+ '.node` is missing.\n\n'+
			'Try running this to fix the issue: '+ process.execPath+ ' '+ __dirname.replace(' ', '\\ ')+ '/build'
		);
		console.error(ex.stack || ex.message || ex);
		throw new Error('Missing binary. See message above.');
	}
}
```
