### ISSUE TITLE
future.wait() does not wait for promise to finish 

### ISSUE THREAD

**Issue by andypeng2015** [laverdet/node-fibers#354]
I expected the code in test to log
`
20171102 00:00:01
xxx
20171102 00:00:02
`
but the actual log is
`
20171102 00:00:01
20171102 00:00:01
xxx
`
pls advise on this, thx

```javascript
// await.js

const Future = require('fibers/future')

module.exports = function (promise) {
  const future = new Future

  promise
    .then(value => {
      console.log('xxx')
      future.return(value)
    })
    .catch(error => {
      future.throw(error)
    })
  
  return future.wait()
}.future()

//test.js
try {
  console.log(new Date)
  await(sleep(1000))
  console.log(new Date)
} catch (e) {
  console.log(e)
}

```

**Comment by laverdet** [comment]
Yes, that is correct.. they are two different things and `promise` is not part of the fibers library. Fibers provides some convenience methods to wrap either into the other though, see: `Future.fromPromise()` and `Future.prototype.promise` in the documentation. Regardless, your example won't work because your `console.log()` calls are not in a fiber and therefore cannot wait.

**Comment by andypeng2015** [comment]
@laverdet thanks for the advice, may I ask how I can wrap the await.js in a fiber then when I `await(async())` it will wait for async() finish first, basically I try to simulate es7 await function here

**Comment by laverdet** [comment]
I can't answer your question because `async` isn't defined anywhere in the example you've shown me. The documentation in README.md is quite thorough and should answer all of your questions. Please feel free to bump this again if you have more specific questions.

**Comment by andypeng2015** [comment]
@laverdet thanks, please see the async function below, it's a returned Promise, how can I make the await waiting for sleep(1000) finish first before console.log again

```javascript
// await.js

const Future = require('fibers/future')

module.exports = function (promise) {
  const future = new Future

  promise
    .then(value => {
      console.log('xxx')
      future.return(value)
    })
    .catch(error => {
      future.throw(error)
    })
  
  return future.wait()
}.future()

//test.js
const sleep = ms => {
  return new Promise(resolve => {
    setTimeout(resolve, ms)
  })
}

try {
  console.log(new Date)
  await(sleep(1000))
  console.log(new Date)
} catch (e) {
  console.log(e)
}

```

**Comment by laverdet** [comment]
This is a basic example of sleep. Again, this is all in the documentation..

```js
const Future = require('fibers/future');
function sleep(ms) {
	let future = new Future;
	setTimeout(() => future.return(), ms);
	return future;
}

Future.task(function() {
	console.log(new Date);
	sleep(1000).wait();
	console.log(new Date);
}).detach();
```
