### ISSUE TITLE
fibers.node is missing on Mac OS X

### ISSUE THREAD

**Issue by andy2046** [laverdet/node-fibers#355]
Hi, i got the issue below when running on Mac OS X, do I need to rebuild on Mac? Thanks

node version v8.6.0

```
## There is an issue with `node-fibers` ##
`/bin/undefined-undefined-undefined/fibers.node` is missing.

Try running this to fix the issue: undefined //build
```

**Comment by staradayev** [comment]
Hi, I have the same issue.

`/node_modules/fibers/bin/darwin-x64-v8-5.8/fibers.node` is missing`

npm 5.0.0
node 8.0.0
Mac OS Sierra 10.12.6

**Comment by laverdet** [comment]
@andy2046 you need to reinstall fibers
@staradayev you need to update fibers

**Comment by staradayev** [comment]
@laverdet it's doesn't help.
I've tried.

The only one thing helps me - it's downgrade Node JS from 8 to 7 version.
