### ISSUE TITLE
GLIBCXX

### ISSUE THREAD

**Issue by Sincap80** [laverdet/node-fibers#360]
Do you have a version wich supports a lower GLIBCXX_3.4.20? Im currently getting the error "/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found" that may results because of using "gcc-Version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC)"

Any suggestions?

**Comment by laverdet** [comment]
If you install fibers fresh on the target machine it should be impossible to end up with a binary that targets a library that you don't have.

**Comment by sharedprophet** [comment]
I was just able to resolve this issue on CentOS 7 by installing gcc-c++ with yum and then doing `yarn add fibers`.

**Comment by Sincap80** [comment]
@sharedprophet this couldnt help me sorry. Still the error /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20'. gcc-c++ just installed me the 4.8.x version
@benjamn this is the output:
`$ node build.js || nodejs build.js
`linux-x64-57` exists; testing
Problem with the binary; manual build incoming
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.9.4 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/pkg/splunk/etc/apps/mongoexplore/bin/node_modules/fibers/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/pkg/splunk/.node-gyp/8.9.4/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/pkg/splunk/.node-gyp/8.9.4',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/pkg/splunk/.node-gyp/8.9.4/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/pkg/splunk/etc/apps/mongoexplore/bin/node_modules/fibers',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
make: Entering directory `/pkg/splunk/etc/apps/mongoexplore/bin/node_modules/fibers/build'
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/fibers/src/fibers.o
  CXX(target) Release/obj.target/fibers/src/coroutine.o
  CC(target) Release/obj.target/fibers/src/libcoro/coro.o
  SOLINK_MODULE(target) Release/obj.target/fibers.node
  COPY Release/fibers.node
make: Leaving directory `/pkg/splunk/etc/apps/mongoexplore/bin/node_modules/fibers/build'
gyp info ok 
Installed in `/pkg/splunk/etc/apps/mongoexplore/bin/node_modules/fibers/bin/linux-x64-57/fibers.node`
Done in 4.07s.
`

**Comment by aguthrie1190** [comment]
I know you said you did not want to modify your /lib64. But I ran in to this exact error and so far the only workaround I've found is updating libstdc++ to use GLIBCXX_3.4.20

For anyone who needs this, I took this directly from the steps listed for setting up nightmarejs on centos: 
http://endorkins.com/2017/04/26/running-nightmarejs-on-centos-6/

`wget https://github.com/rinogo/gcc-6.3.0-lib-CentOS-6-build/raw/master/libstdc%2B%2B.so.6.0.22-CentOS-6.tar.gz
sudo tar xvzf libstdc++.so.6.0.22-CentOS-6.tar.gz -C /usr/lib64/
cd /usr/lib64
ls -alF libstdc++.so.6*
sudo rm libstdc++.so.6
sudo ln -s libstdc++.so.6.0.22 libstdc++.so.6
sudo ls -alF /usr/lib64/libstdc++.so.6*
strings /usr/lib64/libstdc++.so.6 | grep GLIB`

I'd rather not have to do this. So if you find a different workaround, that would be great.

**Comment by laverdet** [comment]
Hey this is addressed in master right now by commit cfa0f3fd5e0677bdc1df25a85d16162ed740ca06. The compiled binary now only requires glibcxx 3.4.9. I'll leave this issue open until it lands in npm though.

**Comment by laverdet** [comment]
On npm
