### ISSUE TITLE
Azure build error: Module parse failed

### ISSUE THREAD

**Issue by BruceBissett** [laverdet/node-fibers#361]
I'm using this module as a dependency from synchronize.js.  It works locally, but when trying to run it on Azure I'm getting this error:

Exception while executing function: Functions.MyTestHandler
Microsoft.Azure.WebJobs.Host.FunctionInvocationException : Exception while executing function: Functions.RevenuePixelHandler ---> System.AggregateException : One or more errors occurred. ---> Error: Module parse failed: 'return' outside of function (2:1)
You may need an appropriate loader to handle this file type.
| if (process.fiberLib) {
| 	return module.exports = process.fiberLib;
| }
| var fs = require('fs'), path = require('path');
    at Object.<anonymous>

**Comment by benjamn** [comment]
It sounds like Azure is attempting to provide a Node.js-like environment, but not everything is the same. Top-level `return` is definitely allowed in CommonJS modules in Node, and this library is called `node-fibers` for a reason. While this problem could be fixed, I doubt the problems would stop there. A system similar to but not exactly like Node probably won't/can't support all binary npm packages that were designed to work with Node.

**Comment by BruceBissett** [comment]
Thanks @benjamn - it does in fact appear to be an issue with compilation of Native Modules.   I haven't found a solution so I'm removing the synchronize module and going about it another way.

**Comment by laverdet** [comment]
I believe this was fixed in 584e8c32 as well :)
