### ISSUE TITLE
Assignment operator issue

### ISSUE THREAD

**Issue by betandbuzz** [laverdet/node-fibers#363]
Fibers and assignment operators work weirdly! It appears that using the `+=` operator with a function doing a pause causes a bug. In this example, I launch 10 tasks in parallel, each one adds `one` to the `sum`. When work is done, the `sum` should be equal to 10 but I get 1.

Even weirder: if I replace `sum += getOne();` by `var one = getOne(); sum += one;`, it works!

<pre><code>"use strict";

var Fiber = require("fibers");

// returns 1 after a pause of 100ms
var getOne = function() {
    var fiber = Fiber.current;

    // sleep 100ms
    setTimeout(function() {
        fiber.run();
    }, 100);
    Fiber.yield();

    return 1;
};

var bug = true; // change to test

var sum = 0;
var done = 0;

var n = 10;
var i;
for (i=0; i&lt;n; i++) {
    Fiber(function() {
        if (bug) {
            // bug!
            sum += getOne();
        }
        else {
            // no bug
            var one = getOne();
            sum += one;
        }

        if (++done === n) {
            console.log("sum = " + sum);
        }
    }).run();
}</code></pre>

**Comment by laverdet** [comment]
Certainly an interesting case, but this is to spec as far as Javascript is concerned.

You can reproduce this in plain v8 by using generators:

``` js
"use strict";
let generators = [];
let count = 0;
for (let ii = 0; ii < 10; ++ii) {
    generators.push(function*() {
        count += yield;
        console.log(count);
    }());
}
generators.forEach(gen => gen.next());
generators.forEach(gen => gen.next(1));
```

Logs "1" ten times. Note that Firefox also agrees with this and logs the same thing.

Or perhaps more abstractly:

``` js
let foo = 0;
function bar() {
  ++foo;
  return 1;
}
foo += bar();
console.log(foo);
```

Logs "1"; does not log "2".

Much in the same way `bar()` in the example above has a side-effect, so too does your call to `one()` and my call to `yield`. The specification is very clear about how these side-effects should be resolved.

You can find the relevant details here: [12.15.4 - Runtime Semantics: Evaluation](http://www.ecma-international.org/ecma-262/7.0/index.html#sec-assignment-operators-runtime-semantics-evaluation).
