### ISSUE TITLE
Fibers throws when installing meteor in a Clean Ionic project (v3.19)

### ISSUE THREAD

**Issue by cfguimaraes** [laverdet/node-fibers#364]
1. `ionic start whatsapp blank`
- Integrate cordova? Y
2. `npm install --save meteor`

At this moment my project doesn't build and I can't install meteor, npm logs says that the error is coming from fibers.

`ionic info` outputs

cli packages: (/usr/lib/node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v6.13.1
    npm               : 3.10.10 
    OS                : Linux 4.13

**Comment by laverdet** [comment]
Hey I have a note about meteor in the readme. If you're running into issues with meteor please head on over to their repository and make sure you've followed all their troubleshooting instructions.
