### ISSUE TITLE
100% CPU caused by Fiber spike (in Meteor)

### ISSUE THREAD

**Issue by KoenLav** [laverdet/node-fibers#371]
We have been experiencing 100% CPU in production, presumably caused by the use of Fibers by Meteor and the way the data lookup for threads is implemented in V8.

While this issue probably cannot be fixed in this repository it seemed worthwhile to track it here as well, in order to find out whether more users of Fibers are suffering from this issue.

As @kentonv describes the issue in the Meteor repository:
V8 uses a linked list to map thread IDs to some thread-local data. Fibers aren't threads, but the fibers package fakes out V8 into thinking that fibers are threads, so this applies to fibers too. If a large number of fibers are created, the list becomes long, and so every lookup into the table becomes slow, because a lookup in a linked list is O(n). These lookups happen frequently, slowing down everything. Using a hash table makes the lookups O(1).

Issue on Meteor repository:
https://github.com/meteor/meteor/issues/9796

Proposed improvement to Meteor's use of Fibers:
https://github.com/sandstorm-io/sandstorm/blob/0f1fec013fe7208ed0fd97eb88b31b77e3c61f42/shell/server/00-startup.js#L99-L129

Commit which fixes the issue in Node.js (by applying a patch to V8):
https://github.com/nodejs/node/commit/0b882566078cb14537f9f91220f1a58530fa7687

V8 issue:
https://bugs.chromium.org/p/v8/issues/detail?id=5338

Proposed contribution which fixes the issue in V8:
Not available yet.

**Comment by laverdet** [comment]
Isn't this handled by the call to `DiscardThreadSpecificMetadata()` [coroutine.cc:286](https://github.com/laverdet/node-fibers/blob/4786aef736ab8285d29e9476e3615abbd3935d37/src/coroutine.cc#L286)

**Comment by laverdet** [comment]
Yeah the change to `poolSize` won't help in the best case, and will hurt in the worst case. It's stupid that thread data is implemented that way (both a linked list and a shared static lock) and I don't think there's truly any good reason except for the fact that Chrome doesn't hit this path in the same way that we do.

@kentonv hopefully you have luck getting your patch accepted. I actually have an open source implementation of what you guys are doing over at cloudflare with my other project [isolated-vm](https://github.com/laverdet/isolated-vm) and your patch would be helpful for that too.

**Comment by kentonv** [comment]
@laverdet Yeah, I took a look at isolated-vm when I noticed fly.io using it. Cool stuff, funny how we were writing such similar code at the same time. :) I do hope we can open source our version too at some point.

**Comment by KoenLav** [comment]
@laverdet you mention changing the pool size won't help, but what if a server actually does reach that amount of Fibers?

Suppose the server would want to spawn 1000 concurrent Fibers and the poolSize is set to 120, would this not cause any issues?

**Comment by KoenLav** [comment]
Great explanation, thanks!
