### ISSUE TITLE
does node-fibers can use 100% of multi-core

### ISSUE THREAD

**Issue by simon4545** [laverdet/node-fibers#372]
it can use multi-core by using 'go' keyword with golang.Does node-fibers can do this?
Thanks

**Comment by laverdet** [comment]
Fibers are not multi-threaded. If you are interested in running javascript in parallel on all cores you may be interested in my other project: [isolated-vm](https://github.com/laverdet/isolated-vm).

**Comment by simon4545** [comment]
thanks a lot
