### ISSUE TITLE
Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by vishvas-prajapati** [laverdet/node-fibers#373]
/home/agile/.meteor/packages/meteor-tool/.1.6.1_1.c76v6p.io9tw++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
 						throw(ex);
 						^
 
 TypeError: Cannot read property 'name' of undefined
     at packages/reacttech_af-cloudinary.js:19:48
     at packages/reacttech_af-cloudinary.js:26:4
     at packages/reacttech_af-cloudinary.js:32:3
     at /home/agile/workshop/Projects/EMS/eventroom/.meteor/local/build/programs/server/boot.js:411:36
     at Array.forEach (<anonymous>)
     at /home/agile/workshop/Projects/EMS/eventroom/.meteor/local/build/programs/server/boot.js:220:19
     at /home/agile/workshop/Projects/EMS/eventroom/.meteor/local/build/programs/server/boot.js:471:5
     at Function.run (/home/agile/workshop/Projects/EMS/eventroom/.meteor/local/build/programs/server/profile.js:510:12)
     at /home/agile/workshop/Projects/EMS/eventroom/.meteor/local/build/programs/server/boot.js:470:11

I got above error while running meteor command.

Node.js: v8.11.1
Meteor: 1.6.1.1

**Comment by laverdet** [comment]
I recommend taking a look at packages/reacttech_af-cloudinary.js, this isn't an issue with fibers.
