### ISSUE TITLE
npm install error fibers@1.0.15

### ISSUE THREAD

**Issue by fedorovmichael** [laverdet/node-fibers#376]
Hi, 
I have error when trying to run npm install:
> fibers@1.0.15 install /home/tickets/www/tickets_parser/node_modules/fibers
> node build.js || nodejs build.js

gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/tickets/www/tickets_parser/node_modules/fibers/build'
gyp ERR! System Linux 4.4.0-97-generic
gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /home/tickets/www/tickets_parser/node_modules/fibers
gyp ERR! node -v v10.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
Alpine users please run: `sudo apk add python make g++`
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/tickets/www/tickets_parser/node_modules/fibers/build'
gyp ERR! System Linux 4.4.0-97-generic
gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /home/tickets/www/tickets_parser/node_modules/fibers
gyp ERR! node -v v10.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
Alpine users please run: `sudo apk add python make g++`
npm WARN tickets_parser@0.0.0 No description
npm WARN tickets_parser@0.0.0 No repository field.
npm WARN tickets_parser@0.0.0 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fibers@1.0.15 install: `node build.js || nodejs build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fibers@1.0.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tickets/.npm/_logs/2018-05-14T19_08_18_241Z-debug.log

thanks

**Comment by tcf909** [comment]
```
gyp ERR! stack Error: EACCES: permission denied, mkdir 
```
Looks like permission issues in your container.

**Comment by laverdet** [comment]
This looks like your problem:
> gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/tickets/www/tickets_parser/node_modules/fibers/build'

Also I looks like you're probably trying to install meteor because of the old fibers version. This won't work with a modern version of node.

**Comment by fedorovmichael** [comment]
Hi, 
thanks for your answers, I'm run npm install as root and node js last stable (node 10), and do not install meteor specifically, maybe some module has reference to meteor, how can I do checking ?

**Comment by laverdet** [comment]
You could try npm ls.
