### ISSUE TITLE
fibers@2.0.2 installation fails for node v10.x and npm v6.x

### ISSUE THREAD

**Issue by achatt89** [laverdet/node-fibers#390]
Hi..
I am using wdio v2.0.2 which internally installs fibers@2.0.2
Trying to install fibers@2.0.2 fails due to the following issue:

![image](https://user-images.githubusercontent.com/6471211/46961646-1d015380-d099-11e8-8e99-faff31bec8e1.png)

The same version installs fine for node v8.x

The release notes for fibers 2.0.2 states that it will be supported in node v10 as well.

The latest version of fibers@3.x installs fine for the current environment.

OS: Win 10.
Node: v10.12.0
NPM: v6.4.1

attaching the debug log: 
[2018-10-15T15_40_08_604Z-debug.log](https://github.com/laverdet/node-fibers/files/2479465/2018-10-15T15_40_08_604Z-debug.log)

**Comment by laverdet** [comment]
If you're using node 10.x you need to use fibers 3.x or above.
