### ISSUE TITLE
Failure when deploying app.

### ISSUE THREAD

**Issue by Drog1744** [laverdet/node-fibers#394]
Hello,

Trying to deploy an app and receiving the following error. I do have the latest version of node.js and npm installed. 

npm ERR! fibers@1.0.7 install: `node build.js || nodejs build.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the fibers@1.0.7 install script 'node build.js || nodejs
build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js || nodejs build.js

**Comment by tcf909** [comment]
Your project looks to be using a very old version of Fibers. You may want
to consider updating the dependency and seeing if that resolves the issue.

I had a similar problem with syncho and was able to use the Fibers 2.x
releases without making any other changes to Syncho.
