### ISSUE TITLE
Failing to install, possibly MacOS Mojave (10.14) 

### ISSUE THREAD

**Issue by brahmaroutu** [laverdet/node-fibers#395]
When trying to install it fails to compile on my Mac running Mojave.
$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

Please see the failure here.

$               npm install fibers@2

> fibers@2.0.2 install /Users/srbrahma@us.ibm.com/WorkDir/cron-miners/node_modules/fibers
> node build.js || nodejs build.js

  CXX(target) Release/obj.target/fibers/src/fibers.o
../src/fibers.cc:318:3: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
                object->SetAccessor(isolate->GetCurrentContext(), name, (AccessorNameGetterCallback)getter, (AccessorNameSetterCallback)setter);
                ^~~~~~~~~~~~~~~~~~~
../src/fibers.cc:464:24: warning: 'Utf8Value' is deprecated: Use Isolate version [-Wdeprecated-declarations]
                                        String::Utf8Value stack(uni::Deref(that.isolate, fatal_stack));
                                                          ^
/Users/srbrahma@us.ibm.com/.node-gyp/11.1.0/include/node/v8.h:2991:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/srbrahma@us.ibm.com/.node-gyp/11.1.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/fibers.cc:686:66: error: too few arguments to function call, expected at least 2, have 1
                                Script::Compile(uni::NewLatin1String(that.isolate, "void 0;"));
                                ~~~~~~~~~~~~~~~                                              ^
/Users/srbrahma@us.ibm.com/.node-gyp/11.1.0/include/node/v8.h:1359:3: note: 'Compile' declared here
  static V8_WARN_UNUSED_RESULT MaybeLocal<Script> Compile(
  ^
../src/fibers.cc:701:66: error: too few arguments to function call, single argument 'context' was not specified
                                                uni::Reset(that.isolate, fatal_stack, try_catch.StackTrace());
                                                                                      ~~~~~~~~~~~~~~~~~~~~ ^
/Users/srbrahma@us.ibm.com/.node-gyp/11.1.0/include/node/v8.h:8872:3: note: 'StackTrace' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> StackTrace(
  ^
/Users/srbrahma@us.ibm.com/.node-gyp/11.1.0/include/node/v8config.h:418:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
2 warnings and 2 errors generated.

**Comment by laverdet** [comment]
You should be using node v10.x. Odd-numbered versions of nodejs are basically beta.
