### ISSUE TITLE
Yielding across a C++-call boundary 

### ISSUE THREAD

**Issue by l7x** [laverdet/node-fibers#400]
I haven't found anything about this mentioned in documentation or other issues.
Lua coroutines have a limitation which prevents you from yielding across a C-call boundary, does the same limitation exists in node-fibers?

**Comment by laverdet** [comment]
This limitation doesn't exist in fibers but I'd like to point out that it's very rare to have a native frame in the middle of your stack unless you're using other native modules. Is there a specific case you are thinking of?

**Comment by l7x** [comment]
Thank you for your quick reply. I'm trying to decide between using fibers and async/await for a new project.
It's been a while since I worked in lua, but I remember that being a biggest limitation when working with coroutines. Also, I remember reading an article [1] which mentioned that as a big problem for implementing fibers in js.

I'd prefer going with fibers instead of async/await, so I just want to be aware of any possible limitations I may encounter in the future. 
It's such a shame that stackful coroutines still don't officially exits in js (and maybe never will).

[1] http://calculist.org/blog/2011/12/14/why-coroutines-wont-work-on-the-web/

**Comment by l7x** [comment]
OK, just to confirm before closing this issue, to use the example from the above-mentioned article - if node/v8 (in some hypothetical scenario) decides to implement function like Array.prototype.forEach in C++, that won't still be a problem for node-fibers?

Can you add a bit more details (it maybe also useful to someone else who will search this keywords) why this limitation exists in lua coroutines, but it doesn't exists in node-fibers, when they both use setjmp/longjmp "hack" (if I understood it correctly, the problem is that longjmp tosses part of the C stack and you can't easily restore it later)?

**Comment by l7x** [comment]
When I searched this keywords, I stumbled across this thread with some explanations for this setjmp/longjmp limitation from lua's documentation:
https://stackoverflow.com/questions/34303507/lua-coroutines-setjmp-longjmp-clobbering
You'll probably understand it much better, I just skimmed through, as I haven't done any C/C++ programning in a very long time.


Yeah, I understand that JS ecosystem heavily prefers async/await, but after working with both, in my opinion stackful coroutines are far superior, especially when you have rich/deep business logic layer. Stackless coroutines feels more like modern goto and it can be pretty harmful to split your codebase into "colors" of the functions:
http://journal.stuffwithstuff.com/2015/02/01/what-color-is-your-function/

**Comment by laverdet** [comment]
After reading that stackoverflow answer I think the main hint as to what's going on is this excerpt:

> Now you may go, "wait, doesn't the Lua stack know that it went into C and back into Lua"? A bit. But the Lua stack is incapable of doing something that C is incapable of. And C is simply not capable of preserving a stack (well, not without special libraries)

The "special library" in this case is where you implement coroutines. I think Lua is super concerned that their code runs on anything that has a compiler so they don't want to use anything that isn't pure C. I actually didn't know that setjmp/longjmp were defined in the official ISO C standard, I thought they were POSIX functions. [ucontext](https://en.wikipedia.org/wiki/Setcontext) is very similar to setjmp/longjmp except it defines 3 functions: setcontext, swapcontext, and makecontext. The 3rd function, makecontext, is something that can't be expressed in terms of setjmp/longjmp without some tampering with internal data structures.

Fibers uses [libcoro](http://software.schmorp.de/pkg/libcoro.html) on the backend which wraps up all these special cases nicely. On Linux it uses ucontext, on Windows it uses their official [Fibers](https://docs.microsoft.com/en-us/windows/desktop/procthread/fibers) implementation, and on every other OS it just uses assembly code.

**Comment by l7x** [comment]
I see, that makes sense. Thank you for your detailed answers.

I played a bit with fibers/futures today and everything I tried seems to be working fine, even stacktraces. I'll use them instead of async/await - it's the closest thing to goroutines I'm gonna get in JS world.
