### ISSUE TITLE
Issue installing on RHEL7 Machine

### ISSUE THREAD

**Issue by neslieang** [laverdet/node-fibers#405]
I'm getting issues installing on a RHEL7 machine, any thoughts on why i'm getting this issue?

> fibers@3.1.1 install /root/.nvm/versions/node/v8.11.3/lib/node_modules/fibers
> node build.js || nodejs build.js

sh: node: command not found
sh: nodejs: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! fibers@3.1.1 install: `node build.js || nodejs build.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the fibers@3.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by laverdet** [comment]
From your log:
```
sh: node: command not found
sh: nodejs: command not found
```

Your $PATH is setup wrong. nvm is known to do some stupid things. You can probably get around this with `npm install --ignore-scripts fibers`
