### ISSUE TITLE
uncaught thrown errors show up as unhandledRejection instead of uncaughtException

### ISSUE THREAD

**Issue by tcf909** [laverdet/node-fibers#413]
I have an interesting case (since I upgraded to Node 12.6) where uncaught exceptions are showing up as unhandledRejections. I'm handling the events for both, but wondered if there was something funky maybe going on under the covers that I should be concerned about. Wanted to raise an issue to see if you had any thoughts before I go through the process of giving you the info you might need to look in to it further.

Thoughts? Suggestions? Let me know if it's something worth pursuing.

Thanks @laverdet hope your doing well.

**Comment by laverdet** [comment]
Fibers doesn't plug into promises except via `Future..promise()` so I would expect that any `unhandledRejection` events are coming from something else. I know that the nodejs team has been making a lot of moves on promises lately to clean up some technical debt so maybe the behavior changed there.

If you can put together a test case that shows the bug I can take a look.
