### ISSUE TITLE
fibers/bin/linux-x64-79-glibc/fibers.node is missing

### ISSUE THREAD

**Issue by tiofabby** [laverdet/node-fibers#421]
Hello
We just started having such compilation issue (inside a gitlab-runner) we never had in the past:

```
[error] ## There is an issue with `node-fibers` ##
`/builds/...our_project.../node_modules/fibers/bin/linux-x64-79-glibc/fibers.node` is missing.

Try running this to fix the issue: /usr/local/bin/node /builds/HZwev4Bb/0/...our_project.../node_modules/fibers/build

```
Looking at node_modules/fibers, linux-x64-79-glibc folder is indeed missing.
So I tried what was suggested in error message:
```
myMachine:fibers fabrice$ node build
`darwin-x64-64` exists; testing
Binary is fine; exiting
myMachine:fibers fabrice$ 

```
But it does not do much..
Anyone would know how such missing folder could be created?

Thank you
Fabrice

**Comment by laverdet** [comment]
This is addressed in the FAQ you clicked through when you opened this issue:

- If you are having problems with an odd-numbered version of nodejs please try again with an even-numbered version instead. The nodejs team doesn't do a good job of communicating this but odd-numbered versions are basically beta versions.

**Comment by tiofabby** [comment]
Thank you. This is correct indeed, by downgrading node to 12.12.0 version, ut worked back again. Thank you for quick feedback!!
