### ISSUE TITLE
Binaries for IBM POWER (ppc64)

### ISSUE THREAD

**Issue by mdenninghoff** [laverdet/node-fibers#422]
Would it be possible for me to compile the fibers binaries for linux-ppc64 and aix-ppc64 platform-architectures and it be included in the 'fibers' NPM package?

My company distributes a fork of node-fibers, profoundjs-fibers, solely to save our users from compiling binaries of fibers on supported architectures, including IBM POWER CPUs--which Node identifies as ppc64. Our profoundjs package depends heavily on fibers.

**Comment by laverdet** [comment]
Sorry this will make managing the project a lot harder for me. Maintaining a fork with the extra binaries seems like a decent enough solution. Providing instructions for setting up node-gyp's dependencies seems like a better solution.
