### ISSUE TITLE
3.1.0@latest' is not in the npm registry

### ISSUE THREAD

**Issue by leopinzon** [laverdet/node-fibers#431]
Hi guys, I am receiving the following message when trying to install the latest version: 

```
$ npm i fibers@>= 3.1.0
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/3.1.0 - Not found
npm ERR! 404 
npm ERR! 404  '3.1.0@latest' is not in the npm registry.
```
I already installed the 3.1.0, but thought this can be a quick fix for the project. 
Thanks a lot, Best!

**Comment by laverdet** [comment]
You have a space after `@>=`. With this command you are asking npm install `fibers@>=` and also install a package named `3.1.0` which does not exist.

**Comment by leopinzon** [comment]
You're completely right! my bad. Thanks for the quick response.
