### ISSUE TITLE
Install fibers failed on Debian

### ISSUE THREAD

**Issue by juzhiyuan** [laverdet/node-fibers#434]
Error occurred when installing `fibers` on Debian with Node.js 8.12.0, but it's ok on other unix like systems, such as OSX.

![image](https://user-images.githubusercontent.com/2106987/74617900-79332680-516a-11ea-98b9-f3c204017333.png)

## Debian Info
![image](https://user-images.githubusercontent.com/2106987/74618055-286ffd80-516b-11ea-80aa-aa26a996d40d.png)

## Reproduce steps
```sh
$ docker run --rm -it debian:stretch-slim

$ wget https://dist.apache.org/repos/dist/dev/incubator/apisix/dashboard-1.0-rc2/apache-apisix-dashboard-1.0-rc2-incubating-src.tar.gz

$ tar zxvf apache-apisix-dashboard-1.0-rc2-incubating-src.tar.gz

$ cd apache-apisix-dashboard-1.0-incubating

$ yarn
```

**Comment by laverdet** [comment]
You need to upgrade node or downgrade fibers. You can try npm install fibers@3
