### ISSUE TITLE
What about new releases & tags & release notes?

### ISSUE THREAD

**Issue by boneyfantaseas** [laverdet/node-fibers#437]
I was wondering what happened from 3.1.1 to 4.0.2. but I can't find information about what's been changed nor a release or according tag.

Thanks in advance for any advice.

**Comment by jaypalexa** [comment]
https://github.com/laverdet/node-fibers/releases

**Comment by jaypalexa** [comment]
Some info here:
https://github.com/laverdet/node-fibers/releases

**Comment by boneyfantaseas** [comment]
Awesome, thank you!
