### ISSUE TITLE
npm install crashing due to fiber install script

### ISSUE THREAD

**Issue by MiKr13** [laverdet/node-fibers#440]
On Windows, Powershell Terminal:
fibers@4.0.2 install: `node build.js || nodejs build.js`

At line:1 char:15
node build.js || nodejs build.js
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;~~
The token '||' is not a valid statement separator in this version.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : InvalidEndOfLine

Why are scripts like these implemented without caring about the compatibility?

**Comment by laverdet** [comment]
> Why are scripts like these implemented without caring about the compatibility?

This line was written in 2011 before nodejs even supported Windows at all. It was added for compatibility with Ubuntu.

Install fibers via cmd.exe and you won't run into problems. This is the same for many other C++ nodejs projects.
