### ISSUE TITLE
Memory leak when using with Jest

### ISSUE THREAD

**Issue by pelotom** [laverdet/node-fibers#441]
Hi, I'm trying to debug memory leaks in my tests. With the following test:

```ts
require('fibers');
// ^ comment out this line to eliminate the leak

test('leak', () => {});
```

running `jest --detectLeaks` reports a leak:

```
  ● Test suite failed to run

    EXPERIMENTAL FEATURE!
    Your test suite is leaking memory. Please ensure all references are cleaned.

    There is a number of things that can leak memory:
      - Async operations that have not finished (e.g. fs.readFile).
      - Timers not properly mocked (e.g. setInterval, setTimeout).
      - Keeping references to the global scope.
```

As explained in [this article](https://chanind.github.io/javascript/2019/10/12/jest-tests-memory-leak.html) this may not be a memory leak in the real program but just in the tests, due to the way that Jest unloads and reloads modules to ensure isolation between runs. Any idea what might be causing this or how I could work around it?

**Comment by pelotom** [comment]
I've created a repro repo here: https://github.com/pelotom/fibers-jest-memory-leak.

By running `npm test` you can see that 3-4 MB are being leaked with every test:

```
 PASS  ./leak1.test.js (20 MB heap size)
 PASS  ./leak7.test.js (23 MB heap size)
 PASS  ./leak2.test.js (27 MB heap size)
 PASS  ./leak3.test.js (31 MB heap size)
 PASS  ./leak4.test.js (34 MB heap size)
 PASS  ./leak6.test.js (38 MB heap size)
 PASS  ./leak5.test.js (42 MB heap size)
 PASS  ./leak8.test.js (46 MB heap size)
 PASS  ./leak0.test.js (49 MB heap size)
 PASS  ./leak9.test.js (53 MB heap size)
```

If the `require('fibers')` line is commented out in `includes.js`, the memory stays level:

```
 PASS  ./leak1.test.js (57 MB heap size)
 PASS  ./leak7.test.js (57 MB heap size)
 PASS  ./leak5.test.js (57 MB heap size)
 PASS  ./leak6.test.js (57 MB heap size)
 PASS  ./leak3.test.js (57 MB heap size)
 PASS  ./leak2.test.js (57 MB heap size)
 PASS  ./leak9.test.js (57 MB heap size)
 PASS  ./leak4.test.js (57 MB heap size)
 PASS  ./leak8.test.js (57 MB heap size)
 PASS  ./leak0.test.js (58 MB heap size)
```

You can also run `npm test --detectLeaks`.

**Comment by laverdet** [comment]
The article you linked has more information than I could give you. fibers is a native module so you can't unload it. You could try running node with `node -r fibers` which would preload fibers before  jest and theoretically trick whatever tracking it's doing.

**Comment by pelotom** [comment]
> You could try running node with `node -r fibers` which would preload fibers before jest and theoretically trick whatever tracking it's doing.

This actually did the trick, cheers! 😄
