### ISSUE TITLE
Release precompiled versions for Node v15

### ISSUE THREAD

**Issue by nex3** [laverdet/node-fibers#445]
It looks like there aren't any precompiled Fibers packages available for Node v15, which was released on 20 October 2020. The lack of precompiled packages has [broken our CI build](https://travis-ci.org/github/sass/dart-sass/jobs/738431875).

**Comment by laverdet** [comment]
Binaries for odd-numbered versions of nodejs are not released. This is mentioned in the issue template, actually.

Basically the node team is allowed to break binary compatibility whenever they want in these versions. So it's not a matter of supporting v15.x it's more like v15.0, v15.4, v15.7, v15.12.. it's a nightmare.
