### ISSUE TITLE
Binary is not included when installing fibers on Ubuntu 18.04 with Node 15

### ISSUE THREAD

**Issue by BrianHVB** [laverdet/node-fibers#446]
Node 15 is not an LTS release, but it is an important update as it includes a new version of NPM that changes the package-lock file format. As such, many teams such as ours have upgraded to Node 15.

When installing Fibers via NPM, things work correctly on Windows/Node 15. But when running on Ubuntu (and I suspect most other Linux variants), the following error occurs:

`.../node_modules/fibers/bin/linux-x64-88-glibc/fibers.node` is missing`

The suggestion to run `node .../node_modules/fibers/build` does not work.

However, running `node-gyp rebuild` and then manually creating the `/bin/linux-x64-88-glibc/` directory and copying the `build/Release/fibers.node` file seems to have restored functionaltiy. Perhaps the package just needs to have binaries updated for Node 15?

**Comment by laverdet** [comment]
It sounds like you have multiple versions of node installed. This tends to happen when npm is using a different version of node than `node` on your command line.
