### ISSUE TITLE
what to do it does not work on node 16 but I really need this package for the code to work

### ISSUE THREAD

**Issue by iocmet** [laverdet/node-fibers#458]
https://github.com/olegp/mongo-sync/blob/master/lib/mongo-sync.js i really need to get this code to work

**Comment by eric-blue** [comment]
> Update [April 13th, 2021] -- Fibers is not compatible with nodejs v16.0.0 or later. Unfortunately, v8 commit [dacc2fee0f](https://github.com/v8/v8/commit/dacc2fee0f815823782a7e432c79c2a7767a4765) is a breaking change and workarounds are non-trivial.
