### ISSUE TITLE
latest version 5.0.2 won't install

### ISSUE THREAD

**Issue by Globebyte** [laverdet/node-fibers#462]
Environment:
- Ubuntu 22.04
- node v14.18.3
- npm v6.14.15

error:

    # This file contains the result of Yarn building a package (fibers@npm:5.0.2)
    # Script name: install

    Usage Error: Couldn't find a script name "node-gyp" in the top-level (used by fibers@npm:5.0.2).
    This typically happens because some package depends on "node-gyp" to build itself, but didn't list it in their dependencies.
    To fix that, please run "yarn add node-gyp" into your top-level workspace. 
    You also can open an issue on the repository of the specified package to suggest them to use an optional peer dependency.

However, when I update my package.json to lock the version to 5.0.1, and without making any other changes, it installs fine.

    from "fibers" : "^5.0.1"
    to "fibers" : "5.0.1"

**Comment by laverdet** [comment]
@denihs 5.0.2 doesn't include any binaries at all. Do you mind taking a look?

**Comment by laverdet** [comment]
@denihs I republished the 5.0.1 package as 5.0.3. If the diagnostics changes were important to your team please make sure to publish binaries in future releases.
